### ISSUE TITLE
Refactor code to not require Spring JDBC as mandatory dependency

### ISSUE THREAD

**Issue by pull-vert** [spring-projects/spring-data-r2dbc#100]
spring-jdbc is now an optional dependency, wich is a good thing !
But this leads to an error
```
java.lang.NoClassDefFoundError: org/springframework/jdbc/core/SqlProvider
...
at org.springframework.data.r2dbc.function.DefaultSqlResult.<init>(DefaultSqlResult.java:78) ~[spring-data-r2dbc-1.0.0.BUILD-SNAPSHOT.jar:1.0.0.BUILD-SNAPSHOT]
```
In DefaultSqlResult, this line does not compile anymore, because SqlProvider is a spring-jdbc Interface
```java
interface SqlFunction<T, R> extends Function<T, R>, SqlProvider {}
```
Workaround is to add dependency on spring-jdbc in my project, but the fix would be to not depend anymore on spring-jdbc :smile: 

Maybe there are other spring-jdbc remaining uses in r2dbc.

**Comment by mp911de** [comment]
Thanks for reporting the issue. We want to only provide optional features that build on Spring JDBC and we should not have mandatory dependencies in our code.

With the merge of #97 the left-over dependencies became visible.

**Comment by mp911de** [comment]
That's fixed now.
