### ISSUE TITLE
Support mapping of simple types (e.g. to Long/Integer) out of the box

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-data-r2dbc#109]
In Spring Fu samples, we have this kind of `DatabaseClient` usage:
```
class UserRepository(private val client: DatabaseClient) {
    suspend fun count() =
        client.execute().sql("SELECT COUNT(*) FROM users").asType<Long>().fetch().awaitOne()
}
```

But when using it we get a `Couldn't find PersistentEntity for type class java.lang.Long!` error. The related issue is https://github.com/spring-projects/spring-fu/issues/160, it can be reproduced as following:

```
https://github.com/spring-projects/spring-fu.git
cd spring-fu
git checkout r2dbc-count-issue
./gradlew clean build publishToMavenLocal
cd samples/kofu-coroutines-r2dbc
./gradlew clean build
```

I think it would make sense to have this kind of mapping supported out of the box.

**Comment by mp911de** [comment]
Flagging this a bug because we already have simple type support in repositories. The only missing bit is that simple type converters were not considered in all configuration mechanisms.
