### ISSUE TITLE
using a ReactiveRepository to save a new entry with user-provided id doesn't  persists the entity

### ISSUE THREAD

**Issue by cambierr** [spring-projects/spring-data-r2dbc#110]
I just noticed that the `.save(Entity entity` method doesn't actually saves anything if the entity `id` is user-provided instead of created by the database (Postgres in my case).

For now, the only workaround I see is to add another id property that can be auto-generated but this is a hugly workaround.

From my understanding, this seems to be due to `EntityInformation.isNew(T entity)` checking if the id property is different from `null`.

How could we work around this ?

**Comment by mp911de** [comment]
Repositories assume by new/existing state based on the `id`. If the entity is `null`, then we assume the entity is new. You can implement `Persistable` which provides the`isNew()` method which is used then to determine whether your entity is new or whether it should be expected to exist.

We have no support yet for optimistic locking (see #93) where we could use a `@Version` property to determine new/existing state.

**Comment by cambierr** [comment]
Didn't know about that interface ! thank you.
