### ISSUE TITLE
Revisit package structure and naming

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-r2dbc#111]
Right now, `PreparedOperation` resides in `domain` and `Bindings` in `dialect`. `Bindings` has a dependency to `BindMarker`.

Should we find a better package (e.g. `operation`) for these types?

**Comment by odrotbohm** [comment]
Here's a set of steps I took to create a bit more streamlined package structure:

Package renames:

- `….function.convert` -> `convert`
- `….function.connectionfactory` -> `connectionfactory`
- `….domain` -> `….mapping`

Type moves:

- `….dialect.R2dbcSimpleTypeHolder` -> `….dialect.R2dbcSimpleTypeHolder`
- `….mapping.BindTarget` -> `….dialect.BindTarget`
- `….mapping.PreparedOperation` -> `….core.PreparedOperation`
- `….mapping.QueryOperation` -> `….core.QueryOperation`
- `….connectionfactory.ConnectionFactoryTransactionManager` -> `….connectionfactory.R2dbcTransactionManager`
