### ISSUE TITLE
Usage of repositories in a Transactional context

### ISSUE THREAD

**Issue by cambierr** [spring-projects/spring-data-r2dbc#131]
Dear all,

I have been looking at the provided samples and running some of them, and actually have high-perf code using the M1.

But right now, I'm looking at the use of repositories in a transactional context like the save method for instance, or even the delete... Is calling the repo from a `.inTransaction(...)` enough to get it working ? I'm having difficulties to figure how this is working in the background

thank you !

**Comment by mp911de** [comment]
You can use either annotation-based (`@Transactional`) or programmatic transaction management (`TransactionalOperator`). Take a look at [Spring Data R2DBC Examples](https://github.com/spring-projects/spring-data-examples/blob/master/r2dbc/example/src/main/java/example/springdata/r2dbc/basics/TransactionalService.java).

To get it working, you need to configure `R2dbcTransactionManager` and `@EnableTransactionManagement`.
