### ISSUE TITLE
Nested object

### ISSUE THREAD

**Issue by jvaca92** [spring-projects/spring-data-r2dbc#137]
Hello, 

I would like have question if there some plan or if already exist support for mapping similar to JPA such as annotation @ManyToMany. When read the documentation I saw that the nested object are not supported yet. Will be these functions supported in near future ? Thank you for your reponse.

**Comment by mp911de** [comment]
The short answer is no. The longer variant is: Running multiple SQL statements to retrieve objects is less efficient than running a single statement. For now, we recommend to handle resolution of relationships in your application code.

**Comment by jvaca92** [comment]
Thanks for quick reponse. Looking forward in more progress in this repo.
