### ISSUE TITLE
Allow multiple usages of the same named parameter

### ISSUE THREAD

**Issue by roboticscm** [spring-projects/spring-data-r2dbc#138]
Dear Spring Data R2DBC Team,
I have an example SQL like this:
```
String sql = "select * from test where sender = $1 or receiver = $1";
databaseClient()
    		.execute()
    		.sql(sql)
    		.bind("$1", id)
    		.as(Test.class)
    		.fetch()
    		.all();
```
It works fine on Spring Data R2DBC 1.0.0.M1 
And when I migrate to M2, like this
```
String sql = "select * from test where sender = :id1 or receiver = :id2";
databaseClient()
    		.execute()
    		.sql(sql)
    		.bind("id1", id)
			.bind("id2", id)
    		.as(Test.class)
    		.fetch()
    		.all();
```

The code above is not beauty (id1, id2, ...)

Could I do something like this:

```
String sql = "select * from test where sender = :id or receiver = :id";
databaseClient()
    		.execute()
    		.sql(sql)
    		.bind("id", id)
    		.as(Test.class)
    		.fetch()
    		.all();


```
The above code throws Excpetion 
java.lang.IllegalArgumentException: Value [1] must be an Collection with a size of [2]: java.lang.Integer

**Comment by mp911de** [comment]
Thanks for reporting. Using multiple times the native bind parameter is possible out of the box as this is handled on driver level. We should make sure in our named parameter processing that we also can reuse the same named parameter multiple times.

**Comment by mp911de** [comment]
Relabelled to enhancement. Parameter reuse only works if:

* The underlying database supports it (e.g. MySQL uses anonymous placeholders `?` that cannot be properly identified with a name/identifier)
* Parameters for databases using anonymous placeholders are not bound to stream/exhaustible sources such as `Publisher<ByteBuffer>` or `Publisher<CharSequence>` that refer typically to a read-once source.
