### ISSUE TITLE
RETURNING * does not work on H2

### ISSUE THREAD

**Issue by eiswind** [spring-projects/spring-data-r2dbc#14]
#10 gives me a regression on h2:

Syntax error in SQL statement "INSERT INTO NEWS_USER (FIRSTNAME,LASTNAME,USERNAME,PASSWORD)  VALUES($1,$2,$3,$4) RETURNING[*] * "

I guess H2 does support only returning id.

**Comment by gregturn** [comment]
In fact one of my tasks has been to use Spring Data R2dbc with H2, and it has largely driven the need for some form of dialect support.

**Comment by mp911de** [comment]
This issue will be fixed with #20 so closing this one.

**Comment by sroziewski** [comment]
This issue is still present with h2 version 2.2.224.
