### ISSUE TITLE
Refcursor returned from Postgresql not supported

### ISSUE THREAD

**Issue by roboticscm** [spring-projects/spring-data-r2dbc#142]
I have example SQL:

```
CREATE OR REPLACE FUNCTION test_func(ref_cursor REFCURSOR)
RETURNS REFCURSOR AS
$BODY$
DECLARE
	query_text TEXT;
BEGIN	
	query_text = 'select now()';

	OPEN ref_cursor FOR EXECUTE query_text;
	RETURN ref_cursor;
END;	
$BODY$
LANGUAGE 'plpgsql';
```
And SQL for test:

```
select test_func('test_func_cursor');
fetch all in "test_func_cursor";
```
Result:
```
2019-06-25 14:23:21.628411+07
```

But when I call from Spring-Data-R2DBC 1.0.0M2
```
@Transactional
	public Flux<Date> getDateFromStored(Date date){
    	String sql1, sql2;
    	sql1 = " select test_func('test_func_cursor') ";
    	sql2 = " fetch all in \"test_func_cursor\" ";
    	return this.databaseClient()
    		.execute()
    		.sql(sql1)
    		.fetch()
    		.all()
    		.thenMany(this.databaseClient()
				.execute()
				.sql(sql2)
				.as(Date.class)
				.fetch()
				.all());
    }
```
When I run, it throws Exception like this:
```
java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object
```

**Comment by mp911de** [comment]
Thanks for report. It seems there are two issues here, mainly r2dbc-postgresql:

1. We have no support for stored procedures yet
2. The driver needs to understand properly the returned types to iterate over the cursor

Let me rebuild the example with plain R2DBC before moving on.

**Comment by mp911de** [comment]
The result of the first query is `REF_CURSOR` with oid `1790` and r2dbc-postgresql has no codec for that.

An additional issue to remember is that if you don't run your code in a transactional scope, the second query will also fail. The reason is that `DatabaseClient` does not bind the connection to any execution but rather statements can be run on different connections.

Here's the simplified variant:

```java
ConnectionFactory connectionFactory = ConnectionFactories
		.get(…);

Mono.from(connectionFactory.create())
		.flatMapMany(it -> it
				.createStatement("select test_func('test_func_cursor') ")
				.execute())
		.flatMap(it -> it.map((row, metadata) -> row.get(0)))
		.as(StepVerifier::create)
		.expectNextCount(1)
		.verifyComplete();
```

Exception:

```
java.lang.IllegalArgumentException: Cannot decode value of type java.lang.Object
		at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:97)
		at io.r2dbc.postgresql.PostgresqlRow.get(PostgresqlRow.java:88)
		at io.r2dbc.spi.Row.get(Row.java:63)

```

**Comment by mp911de** [comment]
@roboticscm can you open a new ticket in https://github.com/r2dbc/r2dbc-postgresql/issues?

The most sensible thing to do is returning an object that can return a `Publisher<? Result>`. 

See also r2dbc/r2dbc-spi#27 and https://groups.google.com/forum/#!topic/r2dbc/12nq6d1l62Q.

**Comment by mp911de** [comment]
Revisiting this topic, fetching from cursors is a Driver-only concern and needs to be transparent to clients. With `R2dbcTransactionManager` in place, we bind connections to transactions and as soon as R2DBC Postgres supports RefCursor fetching, the outlined use-case will transparently work.

**Comment by nishant-1984** [comment]
I am getting the same error. Looking at the promise shown by library i integrated it and took to production now i am n number of issues. Is this in main agenda of spring project i need clarity on that. Very basic issues keep coming with it. When can this library be expected to be stable?

**Comment by mp911de** [comment]
@nishant-1984 R2DBC Postgres is a community-maintained driver. We're currently working towards merging outstanding pull-requests and fixing known bugs. All R2DBC drivers are young and do not support all the features of their databases. To get to a state which supports all kinds of database-specific features (such as `REFCURSOR`), R2DBC Postgres needs community contributions: Bug reports and pull requests.

I don't think code can ever be free of bugs, but we can work towards eliminating bugs that prevent applications from what they want to achieve.

**Comment by nishant-1984** [comment]
But i am not talking of any complicated scenario just the basic read and type casting to a POJO. Problem is this error doesn't come on every invocation for same dataset its random which is very wierd

**Comment by mp911de** [comment]
Please report any driver-related bugs at https://github.com/r2dbc/r2dbc-postgresql/issues.
