### ISSUE TITLE
EnableR2dbcRepositories and database client 

### ISSUE THREAD

**Issue by mctdi** [spring-projects/spring-data-r2dbc#143]
I think is a bug.
I use spring reactive with r2dbc.

My package structure

```
com.example.gatewayservice
	config
	controller
	dto
	model
	repository
		UserRepository.java
	security
	service
	GatewayServiceApplication.java
```

```
@EnableDiscoveryClient
@SpringBootApplication
@EnableR2dbcRepositories
public class GatewayServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(GatewayServiceApplication.class, args);
	}

}	
```	

```
@Service
public class ReactiveUserDetailsServiceImpl implements ReactiveUserDetailsService{
	@Autowired
    private  UserRepository userRepository;
	...
}

@Repository //remove another i get same issue
public interface UserRepository extends ReactiveCrudRepository<User, Integer>{
}
```
My database information is in the application.properties

If I start application, there are error about

Consider defining a bean named 'databaseClient' in your configuration.

Because I use Interface repository, I don't think I need a DatabaseClient bean.

**Comment by mp911de** [comment]
How does your config look like? Do you have a `ConnectionFactory` and `DatabaseClient` configured? With manual configuration, check out [`AbstractR2dbcConfiguration `](https://docs.spring.io/spring-data/r2dbc/docs/1.0.0.M2/reference/html/#r2dbc.connectionfactory).

**Comment by mctdi** [comment]
I don't use DatabaseClient and factory, I setup database in applicatin.properties

**Comment by mp911de** [comment]
Make sure to include Spring Data for R2DBC extensions, see https://github.com/spring-projects-experimental/spring-boot-r2dbc.

**Comment by mctdi** [comment]
in build.gradle, I have
```
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

    implementation 'io.r2dbc:r2dbc-postgresql:1.0.0.M7'
    compile 'io.r2dbc:r2dbc-pool:1.0.0.BUILD-SNAPSHOT'
    implementation 'org.springframework.boot.experimental:spring-boot-starter-r2dbc:0.1.0.M1'
    implementation 'org.springframework.boot.experimental:spring-boot-starter-data-r2dbc:0.1.0.M1'
```

**Comment by mp911de** [comment]
Please upgrade to all snapshots of Spring Boot R2DBC and Spring Data R2DBC as there were changes in Spring Framework and we hadn't a chance yet to release another set of Spring Data/Spring Boot R2DBC releases.
