### ISSUE TITLE
Incompatible issue with Spring 5.2.0.M3 - NoSuchMethodError

### ISSUE THREAD

**Issue by jmirc** [spring-projects/spring-data-r2dbc#153]
I switched to Spring Boot 2.2.0.M4 and I am getting a NoSuchMethodError Exception due to a change in the `TransactionSynchronizationManager` class. The current version used `TransactionSynchronizationManager.currentTransaction()` which has been replaced by `TransactionSynchronizationManager.forCurrentTransaction()` in Spring 5.2.0.M3

**Comment by mp911de** [comment]
This will be fixed with the next release 1.0 M3.

**Comment by jmirc** [comment]
When are you planning to release it?

**Comment by mp911de** [comment]
See https://github.com/spring-projects/spring-data-r2dbc/milestone/3. We need to await Spring Framework 5.5 RC1 and Spring Data Moore RC2 releases.
