### ISSUE TITLE
Release 1.0 RC1

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-r2dbc#154]

**Comment by sanderino666** [comment]
Since Spring 5.2.0.M3 (released june 13), spring-data-r2dbc 1.0 M2 is broken due to a method rename in TransactionSynchronizationManager. When can we expect 1.0 M3? #askingforafriend

**Comment by jmirc** [comment]
spring cloud Hoxton.M2 has been release. When do we expect a new release of Spring Data R2DBC? Thanks

**Comment by rodolphocouto** [comment]
Guys, any news about this release? :(

**Comment by mp911de** [comment]
See [the RC1 milestone](https://github.com/spring-projects/spring-data-r2dbc/milestone/3) for further details.
