### ISSUE TITLE
No option for configuring connection pooling

### ISSUE THREAD

**Issue by nishant-1984** [spring-projects/spring-data-r2dbc#157]
Configuration class:

@Configuration
class DatabaseConfiguration(
    @Value("\${spring.datasource.host}") val dbhost: String,
    @Value("\${spring.datasource.port}") val dbport: Int,
    @Value("\${spring.datasource.database}") val database: String,
    @Value("\${spring.datasource.username}") val username: String,
    @Value("\${spring.datasource.password}") val password: String
) {

    @Bean
    fun databaseClient(connectionFactory: PostgresqlConnectionFactory): DatabaseClient {
        val factory = PostgresqlConnectionFactory(config)
        val exceptionTranslator = SqlErrorCodeR2dbcExceptionTranslator()
        val dataAccessStrategy = DefaultReactiveDataAccessStrategy(PostgresDialect())
        return DatabaseClient.builder()
            .connectionFactory(connectionFactory)
            .dataAccessStrategy(dataAccessStrategy)
            .exceptionTranslator(exceptionTranslator)
            .build()
    }

    @Bean
    fun connectionFactory(): PostgresqlConnectionFactory {

        val config = PostgresqlConnectionConfiguration.builder() //
            .host(dbhost) //
            .port(dbport) //
            .database(database) //
            .username(username) //
            .password(password) //
            .build()
        return PostgresqlConnectionFactory(config)

    }
}

**************************************************************************

There is no  option to configure connection pooling for connection factory. Please let me how to configure connection pooling.

**Comment by mp911de** [comment]
Check out the docs of [r2dbc-pool](https://github.com/r2dbc/r2dbc-pool#programmatic). Spring Data R2DBC has no configuration support beyond `@Bean` methods.
