### ISSUE TITLE
How to dynamically define the database schema?

### ISSUE THREAD

**Issue by eiswind** [spring-projects/spring-data-r2dbc#160]
Is there a way to dynamically specifiy the database schema for a repository?
I think of a schema-based mutli-tenant approach.

As far as I can see the ```@Table``` does not support expressions.
Do you have any thoughts on this?

Should I try implementing a NamingStrategy?
```getQualifiedTableName``` does not seem to be used.

**Comment by mp911de** [comment]
You define the schema at connection time. Switching databases or schemas isn't supported with R2DBC at runtime. You _could_ use `@Table` but that is a functionality beyond its intention.
