### ISSUE TITLE
@Query definitions with SpEL expressions

### ISSUE THREAD

**Issue by a8t3r** [spring-projects/spring-data-r2dbc#164]
Something like that https://spring.io/blog/2014/07/15/spel-support-in-spring-data-jpa-query-definitions:
```java
@Query("select u from User u where u.firstname = :#{#customer.firstname}")
List<User> findUsersByCustomersFirstname(@Param("customer") Customer customer);
```
I thought this feature is common to all spring data projects, but it seems to be specific to jpa.

**Comment by wixanz** [comment]
Any news when SpEL expressions will be supported?
