### ISSUE TITLE
Add converter for byte to boolean for MySQL

### ISSUE THREAD

**Issue by berry120** [spring-projects/spring-data-r2dbc#166]
Some relational databases (MySQL) don't have a built in boolean type, so the convention is just to use a `tinyint` instead. However, if one tries to then map a boolean to this value (via a `ReactiveCrudRepository` or similar), then this error will occur:

    org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.Byte] to type [java.lang.Boolean]

It's reasonably easy to fix by providing a custom conversion like so:

    @EnableR2dbcRepositories
    @Configuration
    class MySqlR2dbConfiguration extends AbstractR2dbcConfiguration {

        @Override
        @Bean
        public R2dbcCustomConversions r2dbcCustomConversions() {
            return new R2dbcCustomConversions(List.of(new Converter<Byte, Boolean>() {
 
                @Override
                public Boolean convert(Byte s) {
                    if (s == null) {
                        return null;
                    }
                    return s != 0;
                }

            }));
        }

        @Override
        public ConnectionFactory connectionFactory() {
            //...etc...
        }
    }

...but it certainly feels like some boilerplate that an application developer shouldn't be expected to provide. Would it be possible to bundle a similar converter by default?

**Comment by mp911de** [comment]
Thanks for report. It makes sense to register Dialect-specific converters. `R2dbcDialect` is the right place.  We could introduce there a `default Collection<Object> getConverters()` method that returns a `List` of predefined converters.

`AbstractR2dbcConfiguration.getStoreConversions(…)` is already a great place to propagate Dialect-specific converters into `CustomConversions`.

Do you want to turn your example into a pull request?

**Comment by berry120** [comment]
Thanks, I've added a PR referencing this just now. I believe I've followed your guidance and the standards / conventions in place, but if not I'll do my best to fix!

**Comment by mp911de** [comment]
Closed via #168.

**Comment by berry120** [comment]
Thanks very much!
