### ISSUE TITLE
byte[]: Distinguish between binary or a smallint[] column

### ISSUE THREAD

**Issue by gm2552** [spring-projects/spring-data-r2dbc#186]
Moving continuing a conversation from r2dbc-rc.  

https://github.com/r2dbc/r2dbc-h2/issues/79

There is some ambiguity in Spring Data R2DBC around the representing of byte[] within an entity object and how it maps to to a database column:

```
Thanks for your explanation. We have two separate things here: Drivers and Spring Data
R2DBC. Drivers actually should support byte[] for binary column interchange. If that’s
missing somewhere, then we should fix it.

The other one is Spring Data R2DBC. Currently, t[], T[] and Collection (Primitives, Wrappers,
1-dimensional collections) are considered candidates for array-valued types. The question
we need to answer is: how do we distinguish between byte[] being either binary or a smallint[] column in Spring Data R2DBC. I
```

A sample application was posted to demonstrate the issue.  The expectation is that the byte[[] field would be mapped to a BINARY column in the database.

https://github.com/gm2552/r2dbc-binarydata-sample.git

**Comment by mp911de** [comment]
Lacking a good approach and given that `byte[]` is generally assumed to be mapped to binary data types, the best, for now, might be to wire `byte[]` to regular binary payload instead of attempting to create a driver-supported array type.

**Comment by mp911de** [comment]
That's in place now.
