### ISSUE TITLE
Upgrade ConnectionFactoryUtils to new version of spring-tx

### ISSUE THREAD

**Issue by blecua84** [spring-projects/spring-data-r2dbc#187]
Hello,

From version **5.2.0.M3** of _**spring-tx**_, **TransactionSynchronizationManager** has renamed this method:
   **public static Mono<TransactionSynchronizationManager> currentTransaction() {...}**

To this new nomenclature:
   **public static Mono<TransactionSynchronizationManager> forCurrentTransaction() {...}**

The problem here is **ConnectionFactory** class(spring-data-r2bc, v1.0.0.M2), which is using **currentTransaction()**. If you want to use the latest version of spring-data-r2bc with the latest version of Spring Boot, you will not because Spring Boot(v2.2.0.M6 uses v5.2.0.RC2 of Spring) comes with _forCurrentTransaction()_ method, and r2bc looks for _currentTransaction()_ method, which does not exist anymore. 

For using the current version of spring-data-r2bc, I have had to downgrade this Spring Boot's version to **2.2.0.M3**, which is also good but is the only solution I have found.

Please, can you review this issue?

Thanks a lot!

Kind regards,

Jose

**Comment by mp911de** [comment]
We will address that issue with a new milestone release for Spring Data R2DBC. For the time being, please stick with snapshots.

**Comment by mp911de** [comment]
Will be fixed with #154.
