### ISSUE TITLE
@EnableR2dbcRepository is not picking my reactive repos.

### ISSUE THREAD

**Issue by nikkisingh111333** [spring-projects/spring-data-r2dbc#201]
hello there i m getting this error.every time i start my spring boot error .i have tried changing dependency but didnot work.please help me fix this:
`***************************
APPLICATION FAILED TO START
***************************

Description:

Field repo1 in Phase4.Results.MatchDataFetcher required a bean of type 'ResultsRepositories.ResultRepo1' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'ResultsRepositories.ResultRepo1' in your configuration.

`
And heres my pom.xml
[pom.txt](https://github.com/spring-projects/spring-data-r2dbc/files/3665463/pom.txt)
heres what i m doing.same is happening with other 5 repos i ve created.
==================

`public class MatchDataFetcher {
	@Autowired
	private ResultRepo1 repo1; //H2-DATABASE
	@Autowired
	private ResultRepo2 repo2;
	@Autowired
	protected DatabaseClient dc;
    @Autowired
    protected ConnectionFactory conn;
    public  List match1(HttpSession session,Class fetch,String entityName) { 
        
	     List l=(List) dc.select().from(fetch).fetch().all().collectList().cache().block();
              return l;
     }
}`
And at last my application:
====================
`import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.*;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.cloud.client.loadbalancer.LoadBalanced;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.core.task.TaskExecutor;
//import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.data.r2dbc.repository.config.EnableR2dbcRepositories;
import org.springframework.scheduling.TaskScheduler;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.servlet.View;
import org.springframework.web.servlet.view.*;
import org.springframework.web.servlet.view.json.MappingJackson2JsonView;

import CustomProperties.R2DBCProperties;

@EnableAsync  
@EnableAutoConfiguration
@SpringBootApplication
@ComponentScan({"Phase3.Tournaments","Phase2.GamersDatabase","Phase4.Results","Phase5.BigGamesData.PUBG","ResultsRepositories","Phase6.ItsAllAboutMoney","Phase7.AwardsAreLove"})
@EnableTransactionManagement
@EnableScheduling
@EnableEurekaClient
@EnableR2dbcRepositories(basePackages="ResultRepositories")
@EntityScan("ResultsRepositories")
public class GamOneYApplication {

	public static void main(String[] args) {
		SpringApplication.run(GamOneYApplication.class, args);
		System.out.println("I M STARTED");
	}
	@Bean(name="taskExecutor")
	public TaskExecutor threadExecutor() {  //BYDEFAULT SPRING WILL USE SIMPLEASYNCTASKEXECUTOR FOR RUNNY @ASYNC METHODS INSEPERATE THREAD WITH DEFAULT THREAD 1 PER REQUEST IF WE DONT PROVIDE THIS TASKEXECUTOR BEAN.
		ThreadPoolTaskExecutor tps=new ThreadPoolTaskExecutor();
		tps.setThreadNamePrefix("Another Thread");
		tps.setCorePoolSize(10);  //will bydefault create 10 threads in thread pool
		tps.setQueueCapacity(100);  //will hold pending tasts if threads are not available for the 11th request or access 
		tps.setMaxPoolSize(15);  //if queue got full another 9 extra threads will be created 
		tps.initialize();
	//	tps.setThreadPriority(9);
		return tps;
		
	}
	@Bean
    public View jsonTemplate() {
	        MappingJackson2JsonView view = new MappingJackson2JsonView();
	        view.setPrettyPrint(true);
	        return view;
	}
	@Bean
	@LoadBalanced
	public RestTemplate restT() {
		return new RestTemplate();
	}
	     

}`
===
I ve used r2dbc before in my earlier project and there everything wass working smooth.but i dont know why i m strruglling here after doing the same configurations.all the repositories are in resultrepositories package please help me.

**Comment by mp911de** [comment]
I'm not able to read the code as formatting is all over the place. Care to attach a sample project as zip or upload it to GitHub?

**Comment by nikkisingh111333** [comment]
here my project files you can take a look at my classes:
[pom (1).txt](https://github.com/spring-projects/spring-data-r2dbc/files/3665837/pom.1.txt)
[GamOneYApplication.TXT](https://github.com/spring-projects/spring-data-r2dbc/files/3665827/GamOneYApplication.TXT)
[MatchDataFetcher.txt](https://github.com/spring-projects/spring-data-r2dbc/files/3665828/MatchDataFetcher.txt)
[ResultRepo1.txt](https://github.com/spring-projects/spring-data-r2dbc/files/3665829/ResultRepo1.txt)
1.pom.xml with latest springboot boot and spring framework versions
2.springbootapplication main class
3.a class which is using resultrepo1 with autowired enabled but getting this error(below)
4.resultrepo1 interface
ERROR:
`***************************
APPLICATION FAILED TO START

Description:

Field repo1 in Phase4.Results.MatchDataFetcher required a bean of type 'ResultsRepositories.ResultRepo1' that could not be found.

The injection point has the following annotations:
- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'ResultsRepositories.ResultRepo1' in your configuration.

`

**Comment by mp911de** [comment]
The project is quite a mess. The code works for me after cleaning up the pom.
