### ISSUE TITLE
Reading from Postgres hangs forever after upgrading to RC1

### ISSUE THREAD

**Issue by reikje** [spring-projects/spring-data-r2dbc#206]
I recently tried upgrading from M2 to RC1 but are no longer able to read from Postgres DB. The behaviour I am seeing, is that reading from the DB never finishes. I have created a small repo project. It uses the testcontainers with postgres, spring boot and spring-data-r2dbc.

master: https://github.com/reikje/r2dbc-issue
Just run the test for a working version using M2.

branch rc1: https://github.com/reikje/r2dbc-issue/tree/rc1
upgraded to RC1, adapted to new `DatabaseClient` api. Test is no longer working.

**Comment by mp911de** [comment]
Please upgrade also to R2DBC 0.8.0.RC1. Currently, the Postgres driver uses M8 instead of RC1.

**Comment by reik-wargaming** [comment]
@mp911de works, thanks. Issue can be closed.
