### ISSUE TITLE
Kotlin bind extension loses specific type information

### ISSUE THREAD

**Issue by rjaros** [spring-projects/spring-data-r2dbc#209]
I can't execute `.fetch()` after using this `.bind()` extension function:
https://github.com/spring-projects/spring-data-r2dbc/blob/6667f7a2303b721f326428b564b84b5b0099d1c5/src/main/kotlin/org/springframework/data/r2dbc/core/DatabaseClientExtensions.kt#L44

```
import org.springframework.data.r2dbc.core.bind

client.execute("SELECT * FROM tab WHERE column = :v").bind("v", nullableValue).fetch() <- compile error
```
I'm using 1.0.0.RC1

**Comment by sdeleuze** [comment]
Indeed, these extensions should provided not directly at `BindSpec` level but at `TypedExecuteSpec` and `GenericExecuteSpec` ones.

**Comment by IEnoobong** [comment]
Looks like an easy fix. Happy to open a PR for it

**Comment by mp911de** [comment]
Thanks a lot!
