### ISSUE TITLE
Upgrade to r2dbc-postgresql from 0.8.0.RC2 to 1.0.0.M7

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-data-r2dbc#214]
Meanwhile there was 1.0.0.M4, 1.0.0.M5, 1.0.0.M6, 1.0.0.M7. It looks like an upgrade to 1.0.0.M7 could make sense.

**Comment by killaitis** [comment]
Agreed, it looks like an upgrade, but in fact, after 1.0.0.M7 it was decided that the current code base would not fulfil the standards for a 1.0 release, so the team went from 1.0.0.M7 to 0.8.0.M8. Unfortunate versioning, agreed, but that's how it is now. So no, 0.8.0.RC2 is the latest release. You may close the issue.

**Comment by juergenzimmermann** [comment]
@killaitis Thanks for the clarification.
