### ISSUE TITLE
Add lifecycle callbacks and EntityCallback support

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-projects/spring-data-r2dbc#215]
It would be nice if Spring Data R2DBC has hooks like `@PostLoad`, `@PrePersist`, `@PreUpdate` in JPA so that some computation for transient props could take place.

**Comment by mp911de** [comment]
We will add Spring Data-typical Lifecycle callbacks using application event listeners and the `EntityCallback` API in a future version.

**Comment by juergenzimmermann** [comment]
@mp911de Does it mean there will be Interfaces like `ReactiveBeforeConvertCallback` like in _Spring Data MongoDB_? If so this would be even better than JPA-like annotations.

**Comment by mp911de** [comment]
Exactly.

**Comment by LaoTsing** [comment]
Also may be supporting SQL Function around inserting value: https://github.com/spring-projects/spring-data-r2dbc/issues/268

**Comment by schauder** [comment]
Done.
