### ISSUE TITLE
Issue with databaseClient.execute("SELECT CAST(NEXT VALUE FOR TestSeq AS BIGINT)")

### ISSUE THREAD

**Issue by vlipovetskii** [spring-projects/spring-data-r2dbc#221]
r2dbc-mssql 0.8.0.RC2
spring-boot-starter-data-r2dbc: 0.1.0.M2

Expected 1, 2, 3, ...
Actual: 2, 4, 6, ...
...
    @Autowired
    private lateinit var databaseClient: DatabaseClient

    @Test
    @Order(1)
    fun `give TestSeq RESTART WITH 1 when SELECT CAST(NEXT VALUE FOR TestSeq AS BIGINT) then 1 returned`() {

        /*
        -- DROP SEQUENCE TestSeq
        -- CREATE SEQUENCE TestSeq START WITH 1 INCREMENT BY 1
         */

        databaseClient
                .execute("ALTER SEQUENCE TestSeq RESTART WITH 1")
                .fetch().first().block()

        databaseClient
                .execute("SELECT CAST(NEXT VALUE FOR TestSeq AS BIGINT)")

                .`as`(java.lang.Long::class.java).fetch()

                .first().block() `should equal` 1.toLong()

    }
...

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by vlipovetskii** [comment]
Excuse me.  Please find more details below.

I get next sequence number from MS Sql Server sequence. Code to create sequence in a db is above.
Each call of "SELECT CAST(NEXT VALUE FOR TestSeq AS BIGINT)" should return numbers 1, 2, 3, ...
In fact, it returms 2, 4, 6, ...
Test above reproduces this problem.

P.S. I work with Ms sql sequences without any problems.

**Comment by mp911de** [comment]
I'm able to reproduce the issue using the SQL Server driver directly via:

```java
Flux.from(createConnectionFactory().create()).flatMap(it -> it
		.createStatement("SELECT CAST(NEXT VALUE FOR TestSeq AS BIGINT)")
		.execute())
		.flatMap(it -> it.map((row, rowMetadata) -> row.get(0)))
		.doOnNext(System.out::println)
		.as(StepVerifier::create)
		.expectNextCount(1)
		.verifyComplete();
```

**Comment by mp911de** [comment]
Can you file the issue at https://github.com/r2dbc/r2dbc-mssql/issues and link it here?

**Comment by mp911de** [comment]
FWIW, I was able to reproduce the same behavior with the JDBC driver when using `connection.createStatement(ISQLServerResultSet.TYPE_SS_SERVER_CURSOR_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY)`.

**Comment by vlipovetskii** [comment]
I will register issue to r2dbc-mssql.
I have used JTDS driver. Which JDBC driver have you used ?

**Comment by mp911de** [comment]
I used the Microsoft JDBC driver. It basically boils down to a cursor scroll option that changes the behavior on the server-side. That behavioral change isn't documented at all so it might be a SQL Server feature or a bug. See the referenced ticket in R2DBC MSSQL.
