### ISSUE TITLE
Spring boot R2DC custom mapping issue

### ISSUE THREAD

**Issue by JesusuCano** [spring-projects/spring-data-r2dbc#224]
Hi team, we are having some issue while we are trying to retrieve information through custom bean which have a converter in order to become it in a simple data.

We have been searching around google, last issues in relation with from r2dbc and also the official documentation of spring r2dbc.. but we haven't found any solution for it.

We think that is related with java.util.UUID class.

Our Custom Response Bean

```
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class FollowResponse {
    private UUID followedUuid;
    private String nickname;
}
```

Custom Converter

```
@ReadingConverter
public class GetFollowResponseConverter implements Converter<Row, FollowResponse> {
    @Override
    public FollowResponse convert(Row row) {
        return FollowResponse.builder().followedUuid(row.get("followed_uuid", UUID.class)).nickname(row.get("nickname", String.class)).build();
    }
}
```

R2dbcCustomConversions implementation

```
    @Bean
    @Override
    public R2dbcCustomConversions r2dbcCustomConversions() {

        List<Converter<?, ?>> converterList = new ArrayList<Converter<?, ?>>();
        converterList.add(new GetFollowResponseConverter());
        return new R2dbcCustomConversions(getStoreConversions(), converterList);
    }
```
CustomQuery
```
    @Query("SELECT f.followed_uuid, p.nickname FROM follow f, profile p WHERE f.follower_uuid = :follower and f.followed_uuid = p.usuario_uuid")
    Flux<FollowResponse> findByFollower (@Param("follower") UUID uuid);
```

Stack Trace

> java.lang.NullPointerException
> 
> 	at org.springframework.data.mapping.model.BeanWrapper.getProperty(BeanWrapper.java:114)
> 	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
> Error has been observed at the following site(s):
> 	|_ checkpoint ⇢ Handler com.ourapp.routes.FollowRoute$$Lambda$684/0x00000008404e9040@1a76db46 [DispatcherHandler]
> 	|_ checkpoint ⇢ com.ourapp.configuration.CorsFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
> 	|_ checkpoint ⇢ HTTP GET "/api/followed/c982b10f-043b-4134-a955-485156615de9" [ExceptionHandlingWebHandler]
> Stack trace:
> 		at org.springframework.data.mapping.model.BeanWrapper.getProperty(BeanWrapper.java:114)
> 		at org.springframework.data.relational.repository.query.DtoInstantiatingConverter.lambda$convert$0(DtoInstantiatingConverter.java:99)
> 		at org.springframework.data.mapping.model.BasicPersistentEntity.doWithProperties(BasicPersistentEntity.java:369)
> 		at org.springframework.data.relational.repository.query.DtoInstantiatingConverter.convert(DtoInstantiatingConverter.java:92)
> 		at org.springframework.data.repository.query.ResultProcessor$ChainingConverter.convert(ResultProcessor.java:228)
> 		at org.springframework.data.repository.query.ResultProcessor$ChainingConverter.lambda$and$0(ResultProcessor.java:214)
> 		at org.springframework.data.repository.query.ResultProcessor$ChainingConverter.convert(ResultProcessor.java:228)
> 		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
> 		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
> 		at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:355)
> 		at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:530)
> 		at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:972)
> 		at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
> 		at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:319)
> 		at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:77)
> 		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:650)
> 		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:728)
> 		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:770)
> 		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:249)
> 		at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:107)
> 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
> 		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
> 		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203)
> 		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:650)
> 		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:728)
> 		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:770)
> 		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:249)
> 		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)
> 		at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112)
> 		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
> 		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213)
> 		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:206)
> 		at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:329)
> 		at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:348)
> 		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
> 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
> 		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:315)
> 		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:429)
> 		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
> 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
> 		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
> 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
> 		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
> 		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
> 		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
> 		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
> 		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
> 		at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
> 		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> 		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 		at java.base/java.lang.Thread.run(Thread.java:834)

Could you take a look? 
Thanks in Advance :D

**Comment by mp911de** [comment]
Can you provide the full stack trace of `NullPointerException`? `BeanWrapper.getProperty(…)` indicates that your converter isn't used for mapping.

**Comment by JesusuCano** [comment]
Hi @mp911de thanks for quick response. Yeah, we have realized while trying to debug that our converter isn't being called. We have already reviewed the code and we aren't finding any lack of code or connection between java classes so that our converter isn't being called.
How can we use our converter?

Last trace is the full stack trace of error.

**Comment by mp911de** [comment]
We have a [test](https://github.com/spring-projects/spring-data-r2dbc/blob/bac5c343b72da03118ab7ceddfcef004fc200839/src/test/java/org/springframework/data/r2dbc/repository/ConvertingR2dbcRepositoryIntegrationTests.java#L77) that uses the same approach as you do.

Can you provide a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem so we can trace it down to the reported issue? The code you attached looks good but it does not reproduce the issue for us.

**Comment by JesusuCano** [comment]
We have just found our problem and solve it 💃. Checking the test that you have sent, we have noticed that r2dbcRepository must be the format of response instead the bean like we had it.
That means that we need customRepository for this type of response (we were used until today the "new com.package.proyect.class" in selects in order to return custom response, but i think that's not possible with r2dbcrepository because we tried).

Before

```
@Repository
public interface FollowRepository extends R2dbcRepository<Follow, Long> {
    @Query("SELECT f.followed_uuid, p.nickname FROM follow f, profile p WHERE f.follower_uuid = :follower and f.followed_uuid = p.usuario_uuid")
    Flux<FollowResponse> findByFollower (@Param("follower") UUID uuid);
Others queries... about Follow Entity
}
```

After we maintain @Follow but extract that querie to
```
@Repository

public interface GetFollowRepository extends R2dbcRepository<FollowResponse, Long> {
    @Query("SELECT f.followed_uuid, p.nickname FROM follow f, profile p WHERE f.follower_uuid = :follower and f.followed_uuid = p.usuario_uuid")
    Flux<FollowResponse> findByFollower (@Param("follower") UUID uuid);
}
```

Many thanks for the support, have a good day 👍

**Comment by mp911de** [comment]
Thanks for pointing this out. Still, it would make sense having the repository declare a DTO or a different type as return type than the domain type. I will add a test in our code and see what we can do about it.
