### ISSUE TITLE
Provide read/write traffic segregation

### ISSUE THREAD

**Issue by cambierr** [spring-projects/spring-data-r2dbc#225]
Being able to split master/slave traffic is great since it makes it possible to scale postgres backends.

Here is something quick and dirty I did, given two `ConnectionFactory` objects bound to respectively slave and master servers, I implemented a custom `ConnectionFactory` wrapping the two others, and the most interesting part is:

```java
    @Override
    public Publisher<? extends Connection> create() {
        return TransactionSynchronizationManager
                .forCurrentTransaction()
                .flatMap(a -> a.isCurrentTransactionReadOnly() ? slavePool.create() : masterPool.create())
                .onErrorResume(NoTransactionException.class, e -> slavePool.create());
    }
```

Do you guys have an opinion on this (again, this is quick and dirty) ? If you think this is going in the good direction, we may open a PR with a highly-polished version of this custom `ConnectionFactory`

**Comment by mp911de** [comment]
The initial draft outlines the underlying idea, and for now, that approach could work. R2DBC SPI has a proposal for a revision of the `beginTransaction(…)` method to pass on transaction mutability, isolation, and other properties as when starting a transaction.

We provide already an `AbstractRoutingConnectionFactory` that forms a good basis for what you want to achieve. To enable transaction mutability-based routing, you could override `R2dbcTransactionManager.doBegin(…)` and attach transaction mutability (read-only) from `TransactionDefinition` to the `Context`. A pure `Context` lookup is more lightweight than using `TransactionSynchronizationManager`. You would also get the chance to apply read-only routing without the need to use transactions.

It doesn't make sense to provide utilities beyond what we currently expose.
