### ISSUE TITLE
GraalVM Native Image support

### ISSUE THREAD

**Issue by jvaca92** [spring-projects/spring-data-r2dbc#229]
Is there consideration support for GraalVM ? Would be great to have Webflux app with R2DBC and be able to compile to binary.

**Comment by mp911de** [comment]
Efforts around GraalVM native image compilations are a bigger topic after all that starts with pre-requisites in Spring Framework. Please follow the ticket in Spring Framework (spring-projects/spring-framework#22968) to track that effort.

Once we have all pre-requisites in place, we can consider adding support for an improved experience with native image compilation.

**Comment by mp911de** [comment]
Spring Native contains configuration support for Spring Data R2DBC, see https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/webflux-r2dbc.

Graal Native compatibility is part of https://github.com/spring-projects-experimental/spring-graalvm-native/ hence closing this ticket.
