### ISSUE TITLE
Avoid SQL Injection

### ISSUE THREAD

**Issue by jorgegh** [spring-projects/spring-data-r2dbc#231]
Hello team!

We are checked that if we try to do an sql injection strike versus r2dbc, it execute the query correctly. 

We are looking for the way to avoid this.

The query:
`@Query("SELECT * FROM entity WHERE ID > :entityId")
    Flux<Plan> findEntitiesGreaterThanId(@Param("offset") String entityId);`

Value of entityId variable:

OneEntityId' OR 'A' = 'A

We are looking for this in the documentation, but we are not find any similar thing.

Please, could you help us for avoid this situation?.

If not is possible, we must to implements a filter for special characters and pass each variable for it before execute the query, but is an ugly method. 

Regards and thanks in advanced!! :)

**Comment by mp911de** [comment]
Spring Data R2DBC translates named parameters within a given query to parameter placeholders and binds parameters to the query to avoid SQL injection flaws. See also https://docs.spring.io/spring-data/r2dbc/docs/1.0.0.RC1/reference/html/#r2dbc.datbaseclient.binding
