### ISSUE TITLE
Problem with SQL Injection

### ISSUE THREAD

**Issue by jorgegh** [spring-projects/spring-data-r2dbc#233]
Hello team!

I'm sorry for open the issue #231 again, but we don't find the correct way for avoid sql injection.

About the last issue, I put a wrong query at write the query here, but in our code is fine.

The correct query:

`@Query("SELECT * FROM entity WHERE ID > :entityId")
 Flux<Entity> findEntitiesGreaterThanId(@Param("entityId") Long entityId);`

Value of entityId variable:

5' OR 'A' = 'A

We are using Spring Data R2DBC for execute the query, but with @Query annotation accept SQL Injection.

Is mandatory to use the manual bind for a correct work?

Thanks for your time and sorry for the inconveniences!

**Comment by jorgegh** [comment]
UPDATE:
I'm sorry, was one wrong mine, I wasn't pass the parameter correctly (Put one String inside Long haven't sense by other way).

You can close the issue!! 👍🏻

I'm sorry for all the inconveniences!!! 😔

**Comment by mp911de** [comment]
Thanks for your feedback. Closing as per your comment.
