### ISSUE TITLE
Return rowsUpdated for modifying queries using repository query methods

### ISSUE THREAD

**Issue by anuger** [spring-projects/spring-data-r2dbc#235]
how can i get "rowsUpdated" with "@query" in repository?
``` java
@Query("delete from label where user_id = 3")
    Mono<Integer> deleteTest();

@Test
    public void removeTest() {

        StepVerifier.create(blogRepository.deleteTest())
                .expectNextMatches(ele -> {
                    System.out.println(ele);
                    return true;
                })
                .verifyComplete();
    }
```
![image](https://user-images.githubusercontent.com/24793128/69215640-354d7700-0ba5-11ea-86d4-718fc90cf7f8.png)

**Comment by mp911de** [comment]
Currently, there is no way how to retrieve the affected rows count. We should add a `@Modifying` annotation or extend `@Query` by adding a `modifying` attribute so we can distinguish between the intent to return the first column as a number or by returning the affected rows count.

**Comment by schauder** [comment]
Done.
