### ISSUE TITLE
databaseClient never returns control back

### ISSUE THREAD

**Issue by yuranos** [spring-projects/spring-data-r2dbc#241]
I'm new to r2dbc. Tried multiple samples I found on the Internet and also created my own. Tried different approaches: gradle, maven, coroutines/kotlin, repositories, spring-boot-r2dbs-starter, plain databaseClient, r2dbc-client, r2dbc-proxy and for all of them the call to database just halts even when operation was successfully performed. The database in definitely reachable, even write operations are performed successfully, but the control never returns to the program. As a result http client is jsut waiting for response indefinitely.
That must be something really obvious. Hopefully just a configuration issue. Here is a typical example:
https://github.com/yuranos/spring-boot-r2dbc-sample/tree/master/spring-boot-r2dbc

**Comment by mp911de** [comment]
Please upgrade to `r2dbc-postgres` 0.8.0.RC2`. `M8` has some performance/stability issues.

**Comment by yuranos** [comment]
Well, it doesn't look like a performance issue to be honest because it's not like it returned but slowly. In any case, just updating `r2dbc-postgres` alone doesn't help. If you do that there are some binary incompatibilities:

> java.lang.NoSuchMethodError: io.r2dbc.spi.Row.get(ILjava/lang/Class;)Ljava/lang/Object;

I tried it with another sample where I used Kotlin and databaseClient and the situation is no better. It's even more interesting that before: with 0.0.8.RC2 neither write nor read are completed. With transitively fetched 1.0.0.M7, write is working, but read is halting as before.
https://github.com/yuranos/spring-kotlin-coroutines-sample/tree/master/data-r2dbc

**Comment by yuranos** [comment]
@mp911de

**Comment by mp911de** [comment]
Switching samples isn't helpful when trying to trace down the cause. Looking at https://github.com/yuranos/spring-kotlin-coroutines-sample/tree/master/data-r2dbc, please make sure to use the most recent version of `r2dbc-bom` which is `Arabba-RC2`.

The sample works for me after using the appropriate dependency version.
