### ISSUE TITLE
SimpleR2dbcRepository returns error if call save on an unchanged entity

### ISSUE THREAD

**Issue by maccamlcQ** [spring-projects/spring-data-r2dbc#253]
Spring Boot 2.2.1.RELEASE
Spring Data R2DBC 1.0.0.RELEASE
R2DBC-(Mysql/SPI) 0.8.0.RELEASE

If I call #save on an unchanged entity, then currently, I am getting an error: `Failed to update table [%s]. Row with Id [%s] does not exist.`

I am using the [r2dbc-mysql](https://github.com/mirromutth/r2dbc-mysql) library.

If I alter my path to ensure the item is always actually updated, before save gets called, then it succeeds as expected.

As this is a nested entity, it is being saved as a side-effect of the primary entity.

Is this a bug, as it worked previously for me, or do I need to update the code flow to perform a read and check if anything has changed before I call save?

**Comment by mp911de** [comment]
Thanks for report. The mentioned exception is signaled when a `save(…)` determines that the object is not new and if the `UPDATE` statement executes without updating a row. We added this behavior with #232 if an `UPDATE` returns zero rows were affected by a change to avoid updates that do not exist on the database (e.g. object with an assigned Id is considered not new which is a common bug when someone assumes the row should be inserted).

We haven't considered that MySQL has slightly different behavior by default. The MySQL docs say:

> For `UPDATE` statements, the affected-rows value by default is the number of rows actually changed. If you specify the `CLIENT_FOUND_ROWS` flag to mysql_real_connect() when connecting to mysqld, the affected-rows value is the number of rows “found”; that is, matched by the `WHERE` clause.

/cc @schauder @mirromutth 

I'm not sure whether it would make sense to enable the `CLIENT_FOUND_ROWS` by default for R2DBC MySQL. We have learned also in other environments (e.g. H2) that some database defaults cause a higher obstacle to application portability. R2DBC drivers can override some defaults to achieve a greater level of portability. Happy to discuss options.

**Comment by mirromutth** [comment]
Yes, for R2DBC MySQL, if `x` row(s) found/touched but only `y` row(s) was really changed, it will return the `y` for the count of affected rows instead of found/touched rows.

See https://github.com/mirromutth/r2dbc-mysql/blob/master/src/main/java/dev/miku/r2dbc/mysql/constant/Capabilities.java#L29 , it is commented line, so this flag is disabled now.

It should be enabled by default if this will affect Spring Data R2DBC behavior. I will change it soon.

**Comment by mp911de** [comment]
The issue will be handled in the driver hence closing this ticket.
