### ISSUE TITLE
Using criteria API with typed operations

### ISSUE THREAD

**Issue by yuranos** [spring-projects/spring-data-r2dbc#255]
Would be nice to use typed operations with criteria like:
```
    suspend fun delete(id: Long) {
        databaseClient.update().table<TimeInterval>()
            .using(Update.update(DELETED_COLUMN, true))
            .fetch().rowsUpdated().awaitFirst()
    }
```
Don't fully understand why `TypedUpdateSpec` is used instead of `GenericUpdateSpec`, or rather why `TypedUpdateSpec` can't also have `using(Update update)`.

**Comment by mp911de** [comment]
Thanks for the feedback. We didn't add `using(Update)` in the first iteration to collect feedback whether such a method would be useful at all. As we're seeing demand, we will consider adding the `using(Update)` that continues with a `matching(Query)` API. 

The same goes for the `value`/`nullValue` methods at `insert(Class)`. Calling one of the two methods switches from object-insert to field (property-based) value assignments.

**Comment by mp911de** [comment]
This functionality was introduced with version 1.1 through `ReactiveUpdateOperation`.

**Comment by hurahurat** [comment]
Hi @mp911de , Is there any way to add support for usingAndAwait in ReactiveUpdateOperation?
Currently with insert I can use custom table name like this
```
databaseTemplate.insert<Comment>()
			.into(customTableName)
			.usingAndAwait(comment)
```
But with update I only have 
```
val comment = databaseTemplate.update(comment).awaitSingle()

```
or
```
val updatedRows = databaseTemplate.update<Comment>()
			.inTable(tableName)
			.matching(Query.query(where("column_1").`is`(comment.commentId)))
			.applyAndAwait(Update.update("content", comment.content)
				.set("other_column", comment.otherValue)
			)
```
Would be nice if I can use update as
```
val comment = databaseTemplate.update<Comment>()
			.inTable(tableName)
			.usingAndAwait(comment)
```
like in the insert query.
