### ISSUE TITLE
how to insert array with @query?

### ISSUE THREAD

**Issue by anuger** [spring-projects/spring-data-r2dbc#257]
* table:
![image](https://user-images.githubusercontent.com/24793128/70845639-11bbda80-1e8c-11ea-937e-e08d14772989.png)
* repository:
![image](https://user-images.githubusercontent.com/24793128/70845645-31530300-1e8c-11ea-9798-2fb0f6ab7db7.png)
* test:
![image](https://user-images.githubusercontent.com/24793128/70845653-4334a600-1e8c-11ea-9c1c-cefa820398b6.png)

* result:
   - test()
![image](https://user-images.githubusercontent.com/24793128/70845683-842cba80-1e8c-11ea-96fe-aee6a9d9deff.png)
    > I guess the final sql is "INSERT INTO foo (friends) VALUES($1,$2,$3)"
   - test2()
```
LOG:  execute S_0/B_0: INSERT INTO foo (friends) VALUES ($1) RETURNING *
```

**Comment by anuger** [comment]
I add the "@Modifying" on "insert()", And the result has not changed

**Comment by mp911de** [comment]
Please use `Integer[]` as parameter type in the repository query method as the Postgres driver maps integer array values to the boxed array type (see [R2DBC Postgres Type Mapping](https://github.com/r2dbc/r2dbc-postgresql#data-type-mapping)).

Using a collection type uses actually parameter expansion. Also, Spring Data R2DBC has no way to correlate parameters when using a `@Query`.

Please refrain in the future from pasting code as images cannot be indexed and found if other users experience the same issue.
