### ISSUE TITLE
@Transactional JUnit tests

### ISSUE THREAD

**Issue by jansvajcr** [spring-projects/spring-data-r2dbc#258]
Since we have `@Transactional` working with R2DBC repositories in _1.0 M2_ (as said [here](https://spring.io/blog/2019/05/16/reactive-transactions-with-spring)), I would like to ask if there is a way to make `@Transactional` working with JUnit (integration) tests (the same way we are able to do when using JDBC repositories). Is this currently possible? Will this even be possible? What is the right approach to achieve transactional tests ?

Currently, running a `@Transactional` `@SpringBootTest` gives me `java.lang.IllegalStateException: Failed to retrieve PlatformTransactionManager for @Transactional test` (the same problem as this guy has: http://disq.us/p/2425ot1).

**Comment by mp911de** [comment]
Thanks for bringing up this topic. This ticket rather belongs to [Spring Framework](https://github.com/spring-projects/spring-framework/issues). Can you file there a copy of this ticket?

Right now, we don't have the possibility to use `@Transactional` on test methods when testing reactive transactions. The only supported approach is moving the `Publisher` into a `@Transactional` service method. Clearly, this approach allows testing of transactional flows but it won't roll back.

**Comment by jansvajcr** [comment]
Here's a copy: https://github.com/spring-projects/spring-framework/issues/24226

**Comment by mp911de** [comment]
Thanks a lot. Closing this ticket in favor of the one in Spring Framework.
