### ISSUE TITLE
Add support to write simple type collections as arrays

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-r2dbc#26]
Postgres supports ARRAY columns that allow storing multiple values in a field. #22 allows reading these values. We need a possibility how to store these. The assumption for `Collection`-typed fields is that these values are stored using relations and not within a single column.

**Comment by mp911de** [comment]
Requires #30 as `RelationalConverter` considers `String[].class` and `List.class` as entities.

**Comment by schauder** [comment]
Done.
