### ISSUE TITLE
Custom Criterias Step does not exist

### ISSUE THREAD

**Issue by LaoTsing** [spring-projects/spring-data-r2dbc#265]
Please add custom criterias step with custom comparators:

`Criteria.where(columnName).customStep(comparator as String, value as Any)`

exactly needed it for many inline queries: Json, Array, Range, FTS, Index in PostgreSQL

**Comment by LaoTsing** [comment]
and also many custom inline queries in other database types

**Comment by mp911de** [comment]
Here are two examples (JSON and Range queries) with SQL and pseudo-code using the `Criteria` API:

```sql
CREATE TABLE orders (
   ID serial NOT NULL PRIMARY KEY,
   info json NOT NULL
);

SELECT
   info ->> 'customer' AS customer
FROM
   orders
WHERE
   info -> 'items' ->> 'product' = 'Diaper'
```

```java
criterial.and("info").has("-> 'items' ->> 'product' =", "Diaper")
```

Range queries

```sql
CREATE TABLE orders (
   ID serial NOT NULL PRIMARY KEY,
   score INT NOT NULL
);

SELECT
   *
FROM
   orders
WHERE
   score <@ int4range(1,7)
```

```java
criterial.and("score").has("<@ int4range(1,7)")
```

These types of queries _could_ work for the criteria part but we already stumble upon that we have no way to express the JSON projection `info ->> 'customer' AS customer` in the select list.

Looking at Full-Text queries or HSTORE (to stay within the Postgres realm), we encounter predicates like `to_tsvector('The quick brown fox jumped over the lazy dog') @@ to_tsquery('fox & (dog | clown) & !queen')`, `SELECT * FROM each('aaa=>bq, b=>NULL, ""=>1');` that render our criteria and projection objects unusable again.

All functional enclosing and nested queries isn't quite supported for the Criteria API as we want to keep it simple. We recommend rather using jOOQ or plain SQL to materialize this kind of query.

**Comment by LaoTsing** [comment]
The `has` it is a great function, that to be support inline database operations, but i not see it in Criteria class in 1.1.0-SNAPSHOT. Waiting for commit?

To support any other nested queries (with, inline select), also support and validation of full-text search and great RUM index inline queries syntax - may be to create branch of Spring-Data-R2dbc-Postgres specialized to database type? Advanced Postgres features are keying when choosing a database.

**Comment by mp911de** [comment]
The example above is **pseudo-code** and there is no `has` method yet. We will discuss in our team whether we want to support this kind of feature. Instead of branching, I would suggest investigating what's required to make jOOQ predicates work with Spring Data JDBC.

**Comment by mp911de** [comment]
Criteria went into Spring Data Relational so this ticket isn't valid anymore.
