### ISSUE TITLE
Combined AND and OR predicate in Criteria Builder

### ISSUE THREAD

**Issue by LaoTsing** [spring-projects/spring-data-r2dbc#267]
For example:
 `Criteria.where(column1).is(value1).and(column2).is(value2).or(column3).is(value3)`

return SQL: `where column1=value1 and column2=value2 or column3=value3`

Needed grouping Criteria: 
`where column1=value1 and (column2=value2 or column3=value3)`

may be this way?: 
`val orCriteria = Criteria.groupStep(column2).is(value2)`.or(column3).is(value3)`
`Criteria.where(column1).is(value1).and(orCriteria)`

then OR and AND overloaded by CriteriaGroup type

**Comment by mp911de** [comment]
The issue is going to be addressed with #289 / #307.
