### ISSUE TITLE
Selecting @EnableR2dbcRepositories with repositoryFactoryBeanClass always need to select basePackages or basePackageClasses

### ISSUE THREAD

**Issue by LaoTsing** [spring-projects/spring-data-r2dbc#272]
I wrote a jar-library with another `R2dbcRepository` implementation, which is specified in the parameter repositoryFactoryBeanClass, but it is impossible to connect as library, because required parameters `basePackages` or basePackageClasses needed - I can’t fill them inside the library, please add new parameter to `@EnableR2dbcRepositories` as example `repositoryClass` to scan repositories by selected type as alternatives to `basePackages` and basePackageClasses or find from FactoryBean repository item.

Analogue without base package:

```
@EnableJpaRepositories(repositoryFactoryBeanClass = CustomRepositoryFactoryBean.class,
		queryLookupStrategy = QueryLookupStrategy.Key.CREATE_IF_NOT_FOUND,
		bootstrapMode = BootstrapMode.LAZY)
```

**Comment by mp911de** [comment]
Have you tried annotation aliasing? You can create your own annotation and use `@AliasFor` to forward properties. Example:

```java
@EnableR2dbcRepositories(repositoryFactoryBeanClass = CustomRepositoryFactoryBean.class)
public @interface EnableMyR2dbcLibrary {

	@AliasFor(annotation = EnableR2dbcRepositories.class, value = "basePackages")
	String[] basePackages() default {};

	@AliasFor(annotation = EnableR2dbcRepositories.class, value = "basePackageClasses")
	Class<?>[] basePackageClasses() default {};
}
```

Adding another scanning mechanism would pollute the public API while serving only a single use case.

**Comment by LaoTsing** [comment]
Yes, it work and now custom repository activator is simple:
`@EnableR2dbcDslRepositories(basePackages = ["package.of.repository"])`

But for scanning may be get base class from `getRepositoryBaseClass` method of `RepositoryFactoryBeanSupport` implementation? then `basePackages` variable not needed

**Comment by mp911de** [comment]
> But for scanning may be get base class from `getRepositoryBaseClass` method of `RepositoryFactoryBeanSupport` implementation? then `basePackages` variable not needed

Not sure what you mean. `basePackages` is used during the factory setup phase to identify repository interface candidates. Once bean definitions are registered, `basePackages` is no longer used.

**Comment by LaoTsing** [comment]
At now `basePackages` used to identify repository interface and may be as alternative we can identity with type from registered `RepositoryFactoryBeanSupport` implementation from `getRepositoryBaseClass` method result as repository class?

**Comment by LaoTsing** [comment]
In custom JpaRepositories do not select `basePackages` - all repository identity by type from RepositoryFactoryBeanImpl

**Comment by mp911de** [comment]
I still have trouble understanding the issue here. It seems that you want to limit scanning in addition to `basePackages` also to a subtype of a particular repository type. You can achieve this by specifying include filters through `@EnableR2dbcRepositories(includeFilters = @Filter(classes = MyRepositoryBaseInterface.class, type = FilterType.ASSIGNABLE_TYPE))`.

May I close this ticket or is there anything else I can assist you with?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
