### ISSUE TITLE
How to generate Limit and Offset Queries in Spring Data R2DBC?

### ISSUE THREAD

**Issue by dzou** [spring-projects/spring-data-r2dbc#279]
Hello, just have a question about the usage of spring-data r2dbc -

What calls through using the `DatabaseClient` do you make to generate a limit/offset queries like:
```
SELECT * FROM PRESIDENT LIMIT 5
SELECT * FROM PRESIDENT LIMIT 10 OFFSET 2
```

Was trying to use the `.page(...)` call like below, however it didn't look like the page method was triggering adding the limit clauses to the query.
```
    this.databaseClient.select()
        .from(President.class)
        .page(PageRequest.of(0, 2))
        .fetch()
        .all()
        .doOnNext(stuff -> System.out.println(stuff))
        .as(StepVerifier::create)
        .expectNextCount(2)
        .verifyComplete();
```

Does LIMIT and OFFSET through the `.page(...)` work in general in spring data r2dbc? I ran the code through the debugger, and [this line the call to `getRequiredSql(...)`](https://github.com/spring-projects/spring-data-r2dbc/blob/7ec3d28b17ef4c4a6c77b355c777cccf9519cb10/src/main/java/org/springframework/data/r2dbc/core/DefaultDatabaseClient.java#L708) appears to not generate the limit/offset clause that I need. Other clauses like sorts are added successfully though.

If it works in other databases generally then it might be a problem on my end where I can dig deeper... I am working on an [R2DBC dialect implementation for Spanner database](https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc/pull/210) and might be missing something.

**Comment by mp911de** [comment]
Pagination details are introduced by the dialect. Check out `Dialect.limit()` in  [`PostgresDialect`](https://github.com/spring-projects/spring-data-jdbc/blob/master/spring-data-relational/src/main/java/org/springframework/data/relational/core/dialect/PostgresDialect.java#L36-L84).

**Comment by dzou** [comment]
Thanks for the reference Mark!

We actually implemented the `.limit()` already, but looking at your postgres reference I saw we were also missing extending from the `AbstractDialect` class; i.e.:

```
public class SpannerR2dbcDialect extends AbstractDialect
```

This made the difference for us; thanks! Closing issue.
