### ISSUE TITLE
Add support for auditing

### ISSUE THREAD

**Issue by DVMaslov** [spring-projects/spring-data-r2dbc#281]
**Entity**:
```
@Table("orders")
public class OrdersEntity {
    @Id
    private Long id;
    private String type;
    private String description;
    @CreatedDate @Column("created_date")
    private LocalDateTime createdDate;
    private Integer amount;

   // getter setter
}
```

**Repository**:
```
interface OrderRepository : ReactiveCrudRepository<OrdersEntity, Long>
```

After `repo.save(..)` `createdDate` remains **null**

**Comment by mp911de** [comment]
Thanks for your ticket. Auditing is not yet supported. We first require an entity callback/lifecycle event infrastructure, see #215.

**Comment by sheiy** [comment]
Will support be provided in the future?

**Comment by mp911de** [comment]
Yes, auditing will come to Spring Data R2DBC. The reason we do not support auditing yet is that we do not have a reactive auditing infrastructure that is able to return the auditor.

**Comment by riba2101** [comment]
Would it be benefitial to port auditing as is and convert to reactive at some low level?

**Comment by mp911de** [comment]
Depends on spring-projects/spring-data-commons#458.

**Comment by riba2101** [comment]
Btw, just a question, but wouldn't it make sense to be able to have a SQL database and be able to log audits to somewhere else like ELK?

would it make sense to create such auditing?

**Comment by mp911de** [comment]
The approach sounds similar to Hibernate Envers (while envers stores revisions in the SQL database). The generic `EntityCallback` infrastructure that will be introduced with #215 will allow you to write revisions to any kind of target as reactive callbacks operate on a `Publisher` level.

**Comment by mp911de** [comment]
That's in place now.
