### ISSUE TITLE
Add support for Criteria composition

### ISSUE THREAD

**Issue by huodon** [spring-projects/spring-data-r2dbc#289]
`Criteria.where(Condition)` will support the construction of dynamic where clauses.
 
```
val noCondition = Conditions.just("1 = 1")
val condition = noCondition.and("name = :name").or(...)
client.select()
            .from("table")
            .matching(Criteria.where(condition))
            .fetch()
```

**Comment by mp911de** [comment]
Thanks for the ticket. These are actually two different requirements here. First, `Criteria.where(…)`. The second one deals with the fact of introducing the SQL DSL API into the criteria API.

Spring Data R2DBC uses the SQL DSL on a lower abstraction level to create statements by considering dialect-specifics. The example `name = :name` does not work here. Named parameters are resolved only for plain queries via the `execute(…)` API. Furthermore, 

```
client.select()
            .from("table")
            .matching(Criteria.where(condition))
            .fetch()
```

does not accept parameter bindings as we expect parameters to be passed in through the `Criteria` object. So there's no way how we could bind the parameter.

The Criteria API was built to help with simple use-cases. It makes sense to introduce an empty `Criteria` object via `Criteria.empty()` that allows composition without the code to consider whether you're constructing the first or a subsequent `Criteria` segment.

**Comment by schauder** [comment]
Done.
