### ISSUE TITLE
Question: How to switch the current schema

### ISSUE THREAD

**Issue by eiswind** [spring-projects/spring-data-r2dbc#299]
We have a schema-based multi-tenant approach that I want to move to reactive.

I wonder if there is a possibility how I can switch the current schema based on some state from the reactor context?

It seems slightly hardwired and cached from the startup.

Any hint would be appreciated.

**Comment by mp911de** [comment]
Schema-based means a database (schema) per tenant? 

If so, then take a look at AbstractRoutingConnectionFactory where lookup keys can be obtained from the Reactor Context.

**Comment by eiswind** [comment]
I'll give it a try. Thx!

**Comment by ramneekIncepta** [comment]
AbstractRoutingConnectionFactory facilitates schema switch over for preconfigured schemas.
 How to handle schema switchover on the fly? i.e if I have one connection pool and would like to make the connection work on different schemas as per the request. that's something that can be done in the SQL query too but I would know to avoid updating all the queries if possible and set it up on the connection level before the query gets executed.
