### ISSUE TITLE
Doc: Explicit Converters have to use Boxed Primitives

### ISSUE THREAD

**Issue by hfhbd** [spring-projects/spring-data-r2dbc#303]
Hey,

If you use Kotlin and explicit converters, you have to use the boxed Objects for Java Primitives. Otherwise the following code does not work:

```
@ReadingConverter
class TestReadConverter : Converter<Row, Test> {
    override fun convert(source: Row) = Test(
        name = source.get("name", String::class.java)!!,
        id = source.get("id", Long::class.java) // change to Long::class.javaObjectType
    )
}
```

Maybe the documentation should include this.

**Comment by mp911de** [comment]
Boxed primitives are specific to R2DBC. It makes sense to include this remark in the docs though.
