### ISSUE TITLE
Why R2dbcEntityTemplate  extends BeanFactoryAware

### ISSUE THREAD

**Issue by huodon** [spring-projects/spring-data-r2dbc#309]
Is `setbeanfactory()` an API required by users?

**Comment by mp911de** [comment]
Right now, the entity template uses the context for projections (interface/DTO projections) for SpEL evaluation. In a future version we’re going to add entity callbacks and lifecycle events that require an event publisher and the context for further bean lookup. 

Regarding your second question, it depends on whether you’re interested in these features.
