### ISSUE TITLE
databaseClient.batchUpdate like good old JdbcTemplate

### ISSUE THREAD

**Issue by yuranos** [spring-projects/spring-data-r2dbc#315]
Maybe I missed something but it seems there's no easy way to do it right now via `databaseClient`.
I found several examples with bare `r2dbc` like [this](https://github.com/r2dbc/r2dbc-client/blob/master/src/test/java/io/r2dbc/client/Example.java) one, but it's obviously not ideal.

I don't want to concatenate the entire query into a String because it will mean I also need to provide a manual SQL Injection check.

As an option, I'm currently considering adding indexing to binding names(which is quite succinct in Kotlin), but there should be a better option.

**Comment by mp911de** [comment]
Batching in R2DBC supports either multiple unparametrized statements via `io.r2dbc.Batch` or by running a single parametrized statement multiple times.

Most database implementations concatenate the unparametrized statements to batch into a single query separated with `;`.

Our `DatabaseClient` indeed lacks support for R2DBC's `Statement.add()` to run a parametrized statements with different binding sets. Would that help in your use-case?

**Comment by mp911de** [comment]
We're going to rebase Spring Data R2DBC on top of Spring R2DBC with #368, therefore it would make sense to add support for batch updates in Spring R2DBC (which is part of Spring Framework) directly.
