### ISSUE TITLE
Add support for liquibase

### ISSUE THREAD

**Issue by mbouchenoire** [spring-projects/spring-data-r2dbc#324]
Hi,

I was wondering if liquibase support was planned to avoid juggling between jdbc and r2dbc configuration ?

And what is your recommended "way" of making liquibase and r2dbc cohabitate as of today ?

Thanks in advance.

**Comment by mp911de** [comment]
The liquibase issue tracker is a better place for your question: https://liquibase.jira.com/browse/CORE-3419. Right now, there's no Liquibase R2DBC support which leaves you with the only option of using JDBC for your database initialization.
