### ISSUE TITLE
Add UUID as simple type in org.springframework.data.r2dbc.mapping.R2dbcSimpleTypeHolder

### ISSUE THREAD

**Issue by ErolPeel** [spring-projects/spring-data-r2dbc#334]
Hi.

Neither `org.springframework.data.r2dbc.mapping.R2dbcSimpleTypeHolder#R2DBC_SIMPLE_TYPES`, nor `org.springframework.data.mapping.model.SimpleTypeHolder#DEFAULTS` contains `java.util.UUID`.

Because `java.util.UUID` is also neither in the package `java.lang` nor `java.time` (see the `if` in `org.springframework.data.mapping.model.SimpleTypeHolder#isSimpleType`), it is not recognized as a simple type.

So it is not possible to use `java.util.UUID` in `org.springframework.data.r2dbc.query.Criteria`s or as a query parameter in  `org.springframework.data.repository.reactive.ReactiveCrudRepository`s.

Wouldn't it be possible to add `java.util.UUID` as a simple type?

**Comment by mp911de** [comment]
Which database are you using? 

We register `UUID` for [Postgres, H2](https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/dialect/PostgresDialect.java#L29), and [SQL Server](https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/dialect/SqlServerDialect.java#L17) databases.

**Comment by ErolPeel** [comment]
I am using Postgres.
In which code block occurs the adding of the UUID?

Mark Paluch <notifications@github.com> schrieb am Do., 2. Apr. 2020, 09:46:

**Comment by mp911de** [comment]
Simple types are wired in [`AbstractR2dbcConfiguration`](https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/config/AbstractR2dbcConfiguration.java#L175-L201) via `CustomConversions` which is then used in `R2dbcMappingContext` and `MappingR2dbcConverter`.

How are you configuring Spring Data R2DBC? Standalone or via Spring Boot?

**Comment by ErolPeel** [comment]
Via Spring Boot. We are using Kotlin too.

**Comment by mp911de** [comment]
I just checked, [`R2dbcDataAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/r2dbc/R2dbcDataAutoConfiguration.java#L95) also constructs the converter configuration properly. We need to investigate deeper what's going on and why `UUID` isn't working as expected.

**Comment by ErolPeel** [comment]
When debugging I see that `org.springframework.data.r2dbc.mapping.R2dbcMappingContext` is used when mapping a value in the `org.springframework.data.r2dbc.query.Criteria`. And the `org.springframework.data.r2dbc.mapping.R2dbcMappingContext` only uses. `org.springframework.data.r2dbc.mapping.R2dbcSimpleTypeHolder#HOLDER`.

How should the `PostgresDialect` register simple types in `org.springframework.data.r2dbc.mapping.R2dbcSimpleTypeHolder#HOLDER`?

**Comment by mp911de** [comment]
Dialects create their own `SimpleTypeHolder` instances. We fixed just recently an issue (#318) with built-in type mappings that was shipped with 1.1.0.RC1. If you're not already using 1.1.0.RC1 then please upgrade and retest. How does the issue actually manifest that `UUID` is not usable for you? Can you provide a stack trace or describe the actual problem?

**Comment by ErolPeel** [comment]
The actual manifestation is, that a list of `UUID`s won't get bind as a query parameter. It gets passed as `null`.
Here is the log of the Postgres Docker container:

```
08:25:44.044 [tc-okhttp-stream-1547234075] INFO  i.v.o.u.PostgreSQLContainerExtension - STDERR: 2020-04-02 06:25:44.043 UTC [79] LOG:  execute S_2/B_20: DELETE FROM connection_permission WHERE connection_permission.id IN ($1)
08:25:44.044 [tc-okhttp-stream-1547234075] INFO  i.v.o.u.PostgreSQLContainerExtension - STDERR: 2020-04-02 06:25:44.043 UTC [79] DETAIL:  parameters: $1 = NULL
```

**Comment by mp911de** [comment]
Okay, that are exactly the symptoms we had before fixing  #318. So upgrading to 1.1.0.RC1 should fix the issue.

**Comment by ErolPeel** [comment]
> Okay, that are exactly the symptoms we had before fixing #318. So upgrading to 1.1.0.RC1 should fix the issue.

OK, thank you.
I'll try it as soon as I got time (used a workaround by just passing a `String` with an `is` clause)

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
