### ISSUE TITLE
ReactiveCrudRepository.findAll which always fetch whole table 

### ISSUE THREAD

**Issue by overmike** [spring-projects/spring-data-r2dbc#336]
I have a UserRepository extends ReactiveCrudRepository. When I use inherited findAll function, I expect Reactive Repository fetch record by chunks/records when someone is iterating the Flux<User> object. Is my expectation wrong or my setup is wrong?

Please bear with me if I post to wrong project. maybe I should post to r2dbc

My current setup
- spring boot initializr, spring-boot version 2.3.0.M4
- spring-boot-starter-data-r2dbc
- spring-data-r2dbc 1.1.0.RC1
- r2dbc-spi 0.8.1.RELEASE
- r2dbc-postgres 0.8.2.RELEASE

`2020-04-03 12:34:39.033 DEBUG 1001 --- [actor-tcp-nio-1] io.r2dbc.postgresql.QUERY                : Executing query: SELECT user.* FROM user`

**Comment by mp911de** [comment]
That’s exactly what’s expected. There are a couple things to note here:

1. A single query is more performant than multiple ones. Data could change in between queries (just think of auto-commit). Issuing multiple queries would generate additional load on the server side. 
2. R2DBC drivers typically use cursors to fetch data and to propagate demand towards the database server so the database query execution is backpressure-aware. Some drivers use cursors by default, others may require configuration. 
3. even without cursors, R2DBC drivers are backpressure-aware. If a given database does not support cursors or drivers don’t use cursors execution, data remains outside of the process if your subscriber is slow. That is TCP backpressure. The remote peer is aware that chunks of data weren’t collected from the client TCP buffer so they stop/pause sending. 

Let me know whether this makes sense and whether you have further questions.

**Comment by overmike** [comment]
thanks for the information. 

So Does r2dbc-postgres support cursor based fetching in Reactive Repository? How can I enable it in general?

I think better ask in gitter

**Comment by overmike** [comment]
Just find out that it is not r2dbc or r2dbc postgres caching whole table. I was using curl with default Accept header
`Accept: */*`
 and seems like webflux trying to make a giant response. After using stream json content type, it acts like streaming all the way to the client.
`Accept: application/stream+json`

Hope this helps other people.
