### ISSUE TITLE
Issue with derived query methods using between

### ISSUE THREAD

**Issue by jumal** [spring-projects/spring-data-r2dbc#349]
**Description**

Derived query methods using **between** are not working and throwing:

`java.lang.IllegalArgumentException: Cannot encode parameter of type org.springframework.data.util.Pair`

**Sample project reproducing the issue**

[between-issue.tar.gz](https://github.com/spring-projects/spring-data-r2dbc/files/4497495/between-issue.tar.gz)

**Comment by mp911de** [comment]
Thanks for reporting the issue. That's fixed now.
