### ISSUE TITLE
javax.persistence.Table annotation not picked up

### ISSUE THREAD

**Issue by gabrielshanahan** [spring-projects/spring-data-r2dbc#351]
When a custom table name is specified using javax.persistence.Table, it is not picked up - it needs to be specified using org.springframework.data.relational.core.mapping.Table. This makes it extremely impractical to use r2dbc in a multi-module setting, where one module sets up the database and contains corresponding entities annotated in the classical way and a second, r2dbc base module, wants to pick them up, connect to the database and use them.

In this situation, one has no choice but to extend the corresponding entity in the module using r2dbc, copy paste the fields, and annotate the result with org.springframework.data.relational.core.mapping.Table, which is pretty awful.

**Comment by gregturn** [comment]
That's a JPA annotation. Spring Data R2dbc doesn't observe JPA annotations.

**Comment by gabrielshanahan** [comment]
Be that as it may, I believe the use case I described is a reasonable one. What should one do in this case? Surely duplicating the entities across several modules just to get the table name right isn't the way to go.

**Comment by mp911de** [comment]
Like @gregturn said, Spring Data R2DBC is not tied to JPA at all. JPA uses a very different approach to persistence that is not compatible with Spring Data R2DBC and supporting JPA annotations would create expectations about features that are just not possible. Therefore, please use Spring Data annotations in your domain model.
