### ISSUE TITLE
Support for JPA like features - @ManyToOne, @OneToMany annotations

### ISSUE THREAD

**Issue by dkalaria** [spring-projects/spring-data-r2dbc#352]

**Comment by mp911de** [comment]
Can you elaborate on the actual features you would like to see and tell us a bit about your use-case that you're trying to solve? Referencing JPA and a few annotations can span a pretty huge feature space.

**Comment by dkalaria** [comment]
The spring-data-common and spring-data-relational annotations are available for use but are limited.
If we can enhance current annotation available in JPA and add new ones that would be helpful:

Updating annotations:
- `@Column` to include length of the field and isNullable
-  `@Table` to include schema value along with table name
- `@GeneratedValue` - to select the strategy for generating the unique value like Identity, Sequence or Auto

New Annotations:
- `@Basic` - to use lazy and eager fetching of the field
- `@MappedSuperclass` - to support inheritance for child class
- `@AttributeOverride` - to rename the super class attribute for a child class

**Comment by mp911de** [comment]
Thanks for the details. We do not plan on adding schema generation and lazy fetching isn't an option either as reactive programming does not allow for blocking operations. Introducing additional wrapper types would pollute the domain model for non-blocking, lazy loading. So eager fetching is really the only option.

Also, for eager fetching we cannot come up with something beyond the first level of reference as that is basically the limit of joins in queries. Right now, you can model arbitrary subclass hierarchies where you end up with a table per class. However, polymorphic queries are not supported and I expect us not following that path as polymorphic querying introduces a lot of complexity providing only little value. So what really is then left over is the ID generation strategy.

**Comment by mp911de** [comment]
Can you create a new ticket for ID generation? Closing this ticket as it's too broadly formulated and hard to understand what's left over.
