### ISSUE TITLE
Support Immutable @Id Property

### ISSUE THREAD

**Issue by SingleShot** [spring-projects/spring-data-r2dbc#358]
Consider a Lombok implemented object with `final` properties and a factory:
``` 
@Data
@Builder(toBuilder = true)
public class User {

    @Id
    private final Long id;
    private final String username;
    ... more final properties ...
}
```

Saving a new object (with no id) results in:
```
Cannot set immutable property User.id!
```

Removing the `final` from the id property alone allows new objects to be saved and retrieved - even though the rest of their properties are immutable. This is because `MappingR2dbcConverter` tries to call a setter for the id upon initial save. It would be nice to support fully immutable classes. Can a callback of some kind or be provided to allow fully immutable types to be saved? Perhaps something like this where the object that will be saved but needs an id can be "replaced" by application code:
```
@Override
User preSave(User u, Long id) {
    return return u.toBuilder().id(id).build();
}
```

Thanks.

**Comment by mp911de** [comment]
Fully immutable classes require either a copy constructor, a `withXxx(…)` method (e.g. `User withId(Long)`) or must be defined as Kotlin data class so that Spring Data is able to discover a method to create a new instance that is associated with the new value.

**Comment by mp911de** [comment]
This issue was solved through DATAJDBC-545.
