### ISSUE TITLE
Support optimistic locking in immutable way

### ISSUE THREAD

**Issue by antoine-mulet** [spring-projects/spring-data-r2dbc#365]
I have been playing with spring-data-r2dbc in Kotlin and it's great stuff! One limitation I have noticed though is that optimistic locking that was released just a few days ago in 1.1.0.RC1 doesn't fully work in the following situation:

```
@Immutable
@Table("foo")
data class FooEntity(
    @Id @Column("id") val id: UUID,
    @Version @Column("version") val version: Int?,
    @Column("name") val name: String) {

    constructor(name: String) : this(UUID.randomUUID(), null, name)
}
```

Basically when creating a brand new entity using the secondary constructor, the `version` is initialized to `null`. Thanks to `@Version`, we also get `isNew` to return `true` when `version` is `null` for free, which is great. So as expected calling the repository `save` method will trigger an insert. So far so good. However, because `version` is a `val`, its value cannot be mutated so `setVersionIfNecessary` in `R2dbcEntityTemplate` cannot set it to 0 and it remains `null`. I think  `@Immutable` could be leveraged to solve the problem but I am very new to Spring data I would appreciate if someone more knowledgeable could confirm. 

A very simple workaround that I use for now is to change `version` to be a `var` but it's not ideal since it means that now version can be mutated so I also need to make it private. But since I still want the `version` to be accessible in read-only mode I also need to add a getter for it. It works in the end but it requires adding some boiler plate code so it would be great if `version` could be a `val` like in my example above.

**Comment by mp911de** [comment]
That's fixed now.

**Comment by antoine-mulet** [comment]
Thanks for the very quick fix! I had a look at your commit code and it seems that using side effects was causing the issue here. It also looks like ```@Immutable``` is not actually necessary to make it work.
