### ISSUE TITLE
Add support for basic operations on Repository interface

### ISSUE THREAD

**Issue by gabrieldn** [spring-projects/spring-data-r2dbc#371]
It would be useful if the library provided basic operations like count, exists, delete, findOne and findAll given a criteria, sort or pageable. The interface could look something like this:

```
public interface R2dbcRepository<T, ID> extends ReactiveCrudRepository<T, ID> {
    Mono<Long> count(Criteria criteria);

    Mono<Boolean> exists(Criteria criteria);

    Mono<Void> delete(Criteria criteria);

    Mono<T> findOne(Criteria criteria);

    Flux<T> findAll(Criteria criteria);

    Flux<T> findAll(Sort sort);

    Flux<T> findAll(Criteria criteria, Sort sort);

    Mono<Page<T>> findAll(Pageable pageable);

    Mono<Page<T>> findAll(Criteria criteria, Pageable pageable);
}
```

There is support for this kind of methods on spring-data-jpa. It would be cool if r2dbc also supported it. The implementation should be pretty straight forward using the api available on R2dbcEntityOperations, which is already available on the SimpleR2dbcRepository.

**Comment by odrotbohm** [comment]
{{Criteria}} is a store specific type and thus shouldn't appear in the repositories interface as it would leak the underlying data access technology into clients. The repositories responsibility is to avoid that exactly. {{R2dbcEntityOperations}} are basically that and can be used to *implement* an API like that *inside* a repository.

**Comment by mp911de** [comment]
Closing as per Ollie's comment.

**Comment by gabrieldn** [comment]
I see, I didn't notice it. In that case, would it be considered to provide such functionality with `Example`?

Also, as this is related to the issue, is there any reason why `Sort` and `Pageable` are not provided in the repository interfaces?

If any of those are acceptable I can create separated issues for them, so the issues are more focussed.

**Comment by mp911de** [comment]
We have a reactive QueryByExample executor so we could add support for query by example. Can you file a new ticket to start with a fresh history? We would add query by example support also for Spring Data JDBC.

**Comment by ogomaemmanuel** [comment]
> `Criteria` is a store specific type and thus shouldn't appear in the repositories interface as it would leak the underlying data access technology into clients. The repositories responsibility is to avoid that exactly. `R2dbcEntityOperations` are basically that and can be used to _implement_ an API like that _inside_ a repository

Just for Curiosity sake, I am learning DDD, does this mean that using Specification as used mostly in spring data JPA is not right
