### ISSUE TITLE
Add support for query by example

### ISSUE THREAD

**Issue by gabrieldn** [spring-projects/spring-data-r2dbc#372]
Creating issue as requested on #371

**Comment by gabrieldn** [comment]
It seems like `ReactiveQueryByExampleExecutor` does not support `Pageable` but `QueryByExampleExecutor` does.

Could it be added or should a new ticket be filed on data commons for this to be supported?

**Comment by gcdd1993** [comment]
Is there any progress?

**Comment by Seelam-Ramesh-Reddy** [comment]
Is it possible to use **ReactiveQueryByExampleExecutor**  along with ReactiveCrudRepository ?

**Comment by mp911de** [comment]
Feel free to submit a pull request to speed things up.

**Comment by mp911de** [comment]
Fixed via 9336d09.
