### ISSUE TITLE
Inserting Flux of Items Inserts Only One Item When Retrieving the Number of Rows Updated 

### ISSUE THREAD

**Issue by TheNumberOne** [spring-projects/spring-data-r2dbc#374]
This is caused by line
https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/core/DefaultDatabaseClient.java#L1162.

Line
`return Mono.from(objectToInsert).flatMapMany(toInsert -> exchange(toInsert, mappingFunction).rowsUpdated())
							.collect(Collectors.summingInt(Integer::intValue));`
should be
`return Flux.from(objectToInsert).flatMapMany(toInsert -> exchange(toInsert, mappingFunction).rowsUpdated())
							.collect(Collectors.summingInt(Integer::intValue));`

I can create an example project showing this error and submit a pull request with a fix if you wish.

**Comment by TheNumberOne** [comment]
Here is a minimal repository with the failing code in the test:
https://github.com/TheNumberOne/spring-data-r2dbc-insert-bug

**Comment by mp911de** [comment]
Feel free to submit a pull request.

Please note that our `DatabaseClient` is going to be deprecated once the Spring R2DBC pull request gets merged. You might want to have a look at `ReactiveInsertOperation` as well.

**Comment by m1ngyuan** [comment]
@mp911de 
Is there a best practice for bulk entity insertion? , I only see io.r2 in r2dbc SPI dbc.spi.Connection#createBatch , can it be supported in DatabaseClient

**Comment by mp911de** [comment]
R2DBC's `Batch` is a batch of unparametrized statements. This type of batch uses parametrized statements so the way to go should be `Statement.add()`. Since `DatabaseClient` does not yet expose functionality for batching, we need to create and issue individual statements.

**Comment by TheNumberOne** [comment]
Actually, I want able to get the project to build fully on my machine (had a couple failing integration tests.) Do you have any advice for that? Also, thanks for letting me know it will be deprecated. What database client is it being replaced with?

**Comment by mp911de** [comment]
Superseded by #368. We should reconsider batching with #259.
