### ISSUE TITLE
QueryMapper fails when using Criteria.from(…) with two or more criteria

### ISSUE THREAD

**Issue by peacetrue** [spring-projects/spring-data-r2dbc#383]
Can I use ``Criteria.from`` like this:

![image](https://user-images.githubusercontent.com/38878763/83944262-a9472800-a834-11ea-8e00-ab86969fe573.png)

**Comment by mp911de** [comment]
Please refrain from pasting images into bug reports. Those cannot be indexed.

The actual code causing the issue is the usage of `Criterial.from(…)` when used with two or more elements.

```
Criteria criteria = Criteria.from(Criteria.where("name").is("Foo"), Criteria.where("name").is("Bar") //
						.or("age").lessThan(49));
```

**Comment by mp911de** [comment]
That's fixed and backported now.
