### ISSUE TITLE
Allow returning CompletableFuture from query method

### ISSUE THREAD

**Issue by shadab005** [spring-projects/spring-data-r2dbc#394]
Hi
I am trying to use R2dbcRepository and making an attempt to return CompletableFuture. I know we should ideally use Mono flux but I wanted to use CompletableFuture and ran into few issues. Some comments in code give some idea. Also, attaching exception at the end for findAllAsync method

```
public interface ProductRepository extends R2dbcRepository<Product, Long> {
    /*
    * Create
    * Issue : Works. But looks like it doesn't return the product in return rather it is CompletableFuture<Void> at runtime
    */
    @Async
    @Query("insert into product (name, price) values(:name, :price)")
    CompletableFuture<Product> saveProduct(String name, Double price);
    //read
    @Async
    CompletableFuture<Product> findOneByName(String name); //works
    @Async
    CompletableFuture<Product> findById(String id); //works
    //delete
    @Async
    CompletableFuture<Product> deleteByName(String name); //works

  /*
   * Issue : Throwing exception : Query [select * from product] returned non unique result.
   */
    @Async
    @Query("select * from product")
    CompletableFuture<List<Product>> findAllAsync();
}
```

```
@Table("product")
public class Product {
    @Id
    private Long id;
    private String name;
    private Double price;
}
```

**Issue 1**

```
findAllAsync is throwing the below exception at runtime:
org.springframework.dao.IncorrectResultSizeDataAccessException: Query [select * from product] returned non unique result.
	at org.springframework.data.r2dbc.core.DefaultFetchSpec.lambda$one$0(DefaultFetchSpec.java:61) ~[spring-data-r2dbc-1.1.1.RELEASE.jar:1.1.1.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:378) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxBuffer$BufferExactSubscriber.onNext(FluxBuffer.java:154) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:355) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:535) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:999) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
```

**Note**
findAllAsync worked for JpaRespository

**Issue 2**
I am unable to write Async method for save taking Product like
`@Async CompletableFuture<Product> saveAsync(Product product)`

Git repo : https://github.com/shadab005/product-r2dbc-completablefuture-reactive/blob/master/src/main/java/com/reactive/completablefuture/r2dbc/productr2dbccompletablefuturereactive/repository/ProductRepository.java

Thanks,
Shadab

**Comment by mp911de** [comment]
`CompletableFuture`, `CompletionStage`, and `ListenableFuture` aren't supported return types for reactive query methods.
Reactive repositories inherently work asynchronously so there's no point in adding `@Async`. We can investigate on our side to support futures. As a workaround, define a method returning `Mono<T>` and then call `toFuture()` on the resulting mono.

**Comment by shadab005** [comment]
Hi @mp911de 
Thanks for the information. This helps a lot. Definitely, Mono/Flux is the correct way but I wanted to explore the CompletableFuture support.

Just a follow up question if CompletableFuture is not supported, few methods like below still works:
`CompletableFuture<Product> findOneByName(String name); //works`

Maybe support for these are still under development.

**Comment by silence-coding** [comment]
I would like to add an extension so that we can add the returned supported types, such as CompletableFuture.

**Comment by silence-coding** [comment]
Using the ea - async third - party, the combination of CompletableFuture and await can make our code development more elegant.

**Comment by silence-coding** [comment]
`LocalDateTime start = LocalDateTime.now();
        System.out.println("start in " + start);
        CompletableFuture<List<Integer>> work1 = Flux.just(1, 2)
            .delaySubscription(Duration.ofSeconds(3)) // Simulation service processing duration
            .collect(Collectors.toList())
            .toFuture();
        CompletableFuture<List<Integer>> work2 = Flux.just(3, 4)
            .delaySubscription(Duration.ofSeconds(5)) //Simulation service processing duration
            .collect(Collectors.toList())
            .toFuture();
        System.out.println();
        System.out.println(
            await(work1) + " work1 process use " + (LocalDateTime.now().getSecond() - start.getSecond()));
        System.out.println(
            await(work2) + " work2 process use " + (LocalDateTime.now().getSecond() - start.getSecond()));`

**Comment by mp911de** [comment]
We recommend using Spring Data JDBC with `@Async` if you want to fully leverage `CompletableFuture`. Spring Data R2DBC follows a reactive programming model and going back to `CompletableFuture` goes back to an async/imperative programming model. Therefore, we do not want to adopt this change.
