### ISSUE TITLE
Allow suspend + List in CoroutineCrudRepository

### ISSUE THREAD

**Issue by Tienisto** [spring-projects/spring-data-r2dbc#395]
Hello,

usually when I want a list, I use a function returning a `Flow` followed by `toList()` which is working perfectly.
Here is what I write now:
```
interface UserRepo : CoroutineCrudRepository<User, Long> {
    suspend fun findByEmail(email: String): User?
    fun findByFirstName(firstName: String): Flow<User>
}

// in use:
val users = userRepo.findByFirstName("Max").toList() // toList() is the build-in suspended function
```

What about including this into the repository itself? Then the code is much cleaner and because toList() is a suspended function, the thread is not blocked anyways.
```
interface UserRepo : CoroutineCrudRepository<User, Long> {
    suspend fun findByEmail(email: String): User?
    suspend fun findByFirstName(firstName: String): List<User>
}
```
Currently an exception is thrown when I try the 2nd example.

**Comment by mp911de** [comment]
Sounds a good enhancement. We should be able to perform this change in Spring Data Commons entirely. Any objections @sdeleuze?

**Comment by sdeleuze** [comment]
Sorry for the delay, supporting this kind of construct makes sense since it really depends on the use case for choosing between both and unlike `Mono<List<User>>`, the unwrapped version is pretty pleasant to use thanks to Coroutines. So +1 from my perspective.

**Comment by mp911de** [comment]
Depends also on a change in Spring Data Commons (DATACMNS-1802).

**Comment by mp911de** [comment]
That's in place now.
