### ISSUE TITLE
Repositories: Insert and Update

### ISSUE THREAD

**Issue by Tienisto** [spring-projects/spring-data-r2dbc#396]
I know this kind of breaks the tradition that we only have `save` but why not include `insert` and `update` into the repository interfaces?
The old `save` method does two different things based on the `id` which seems odd to me. Especially when I want to set a custom id, then I am forced to extend `Persistable` and implement `isNew` to archieve what I want. This is even more complicated when I want to update an instance with a custom id (how should `isNew` be implemented in this case?).

My workaround currently is to use `DatabaseClient` which has `insert` and `update` as separate functions.

**Comment by mp911de** [comment]
The idea of a repository is to ask for persisting an object. Insert and save are technical details. Repositories have multiple `IsNew` strategies to determine whether an object is new or whether it's an existing one. Therefore, we generally try to avoid adding additional methods unless there's a very good reason to have these.
