### ISSUE TITLE
kotlin Criteria.CriteriaStep.isEquals deprecation

### ISSUE THREAD

**Issue by juan-medina** [spring-projects/spring-data-r2dbc#405]
HI, I was looking at the Kotlin extensions `Criteria.CriteriaStep.isEquals` that now is deprecated

https://github.com/spring-projects/spring-data-r2dbc/blob/23dbcc13166242792ae576d8e1ebf7092ead210e/src/main/kotlin/org/springframework/data/r2dbc/core/CriteriaStepExtensions.kt#L26-L28

I guess that is because `org.springframework.data.r2dbc.query.Criteria` is as well deprecated and we should use `org.springframework.data.relational.core.query.Criteria` instead, but I can not find and extension similar to the previous `isEquals` for Kotlin. 

Before deprecation, I could do something like:

```kotlin
import org.springframework.data.r2dbc.core.from
import org.springframework.data.r2dbc.core.isEquals
import org.springframework.data.r2dbc.query.Criteria.where

....
    databaseClient
        .select().from<Foo>()
        .matching(where("id").isEquals("bar"))
        .fetch().one()
```
Now I need to do:

```kotlin
import org.springframework.data.r2dbc.core.from
import org.springframework.data.relational.core.query.Criteria.where

....
    databaseClient
        .select().from<Foo>()
        .matching(where("id").`is`("bar"))
        .fetch().one()
```
Maybe there are new extensions for `org.springframework.data.relational.core.query.Criteria` that I not aware of?

I can contribute with some, but that may imply dependency on the Kotlin runtime in `spring-data-relational`, maybe we should have something like https://github.com/reactor/reactor-kotlin-extensions ?

Thanks

**Comment by mp911de** [comment]
Good catch. Spring's Kotlin extensions are hosted in the same artifacts as the main Java code. Feel free to submit a pull request against https://github.com/spring-projects/spring-data-jdbc that contains Spring Data Relational.

**Comment by juan-medina** [comment]
Thanks @mp911de , I've opened a discussion in gitter before moving forward, since I'm not sure that adding kotlin to Spring Data is something that everyone will be happy about it. If people agree I'll proceed with the PR and link it here so it could be track where is coming from

**Comment by mp911de** [comment]
Closing this ticket as it is handled by spring-projects/spring-data-jdbc#240.
