### ISSUE TITLE
Make it possible to write delete/update operations without using matching

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-data-r2dbc#410]
In Kotlin I can write:
 - `op.delete<User>().from("users").matching(Query.empty()).all()`
 - `op.delete<User>().matching(Query.empty()).all()`

But not:
 - `op.delete<User>().from("users").all()`
 - `op.delete<User>().all()`

Same issue for update options.

**Comment by mp911de** [comment]
That's an oversight on our end that we should address.

**Comment by mp911de** [comment]
That change is in place now.
