### ISSUE TITLE
SimpleR2dbcRepository does not support custom subclasses

### ISSUE THREAD

**Issue by duke9509** [spring-projects/spring-data-r2dbc#416]
[This section of the Spring Data Reference Documentation](https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#repositories.customize-base-repository) describes how a custom repository base class can be used.

It notes that, when doing so, one must override/provide a constructor with the signature `(EntityInformation<T, ID>, StoreOperations, ...)`.

In the case of `SimpleR2dbcRepository`, that would be `SimpleR2dbcRepository(RelationalEntityInformation<T, ID>, R2dbcEntityOperations, R2dbcConverter)`. However, [that constructor is package-private.](https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/repository/support/SimpleR2dbcRepository.java#L61)

Attempting to override the public constructor yields an error on bean instantiation saying to provide the other signature. It is also not possible to convert from the desired signature to the public one, as there does not appear to be a publicly-accessible way to pull the `ReactiveDataAccessStrategy` back out of the `R2dbcEntityOperations` (The trick the `R2dbcEntityTemplate` constructor uses to pull it out of the `DatabaseClient` won't work as `DefaultDatabaseClient` is also package-private).

Is there a particular reason that constructor is package-private? The fact that it is seems to me to be the only thing preventing the use of a custom base class. Or is there something else I'm missing?

**Comment by mp911de** [comment]
Waiting for #368.

**Comment by dkublik** [comment]
@duke9509 as a temporary workaround you can always use the second constructor with null value for ReactiveDataAccessStrategy

```
    public BaseRepositoryImpl(RelationalEntityInformation<T, ID> entity, R2dbcEntityOperations entityOperations,
        R2dbcConverter converter) {
        super(entity, entityOperations.getDatabaseClient(), converter, null);
    }
```
I've checked - it's working.

SimpleR2dbcRepository ignores it anyway
```
public SimpleR2dbcRepository(RelationalEntityInformation<T, ID> entity, DatabaseClient databaseClient,
			R2dbcConverter converter, ReactiveDataAccessStrategy accessStrategy) {

		this.entity = entity;
		this.entityOperations = new R2dbcEntityTemplate(databaseClient);
		this.idProperty = Lazy.of(() -> converter //
				.getMappingContext() //
				.getRequiredPersistentEntity(this.entity.getJavaType()) //
				.getRequiredIdProperty());
	}
```

**Comment by duke9509** [comment]
@dkublik You know... I am kind of embarrassed that I didn't think of that, haha. Thank you very much! :joy:
