### ISSUE TITLE
Document optimistic locking using @Version

### ISSUE THREAD

**Issue by eiswind** [spring-projects/spring-data-r2dbc#418]
data-jdbc has this nice Feature, and it would be great if we could see this in r2dbc too.

I found that @Version is supported in
https://github.com/spring-projects/spring-data-r2dbc/issues/93

Having user generated Ids is somewhat cumbersome, because according to the docs one needs to implements Persistable.
Considering version 0 to be new appears quite elegant.

**Comment by mp911de** [comment]
That's already supported since version 1.1. Feel free to file a bug report in case `@Version` isn't working as advertised.

**Comment by eiswind** [comment]
Sorry I didn't see that. Should have looked into the source.
Could it be that it's not in the docs? I also didn't see how immutable entities are handled on version update.

**Comment by mp911de** [comment]
Good catch, we need to update the documentation.

**Comment by mp911de** [comment]
That's done now.

**Comment by eiswind** [comment]
Thx for the great work!
