### ISSUE TITLE
Add support for MariaDB

### ISSUE THREAD

**Issue by dheeraj29** [spring-projects/spring-data-r2dbc#42]
No spring r2dbc for mariadb exists as of today. As said in https://r2dbc.io/ videos there is a support mentioned 2 months back in works. So please do help in providing initial repository (mariadb r2dbc) for community to test and give feedback.

**Comment by mp911de** [comment]
We're a small team and currently, we cannot afford to start a new driver implementation. We're happy to guide you through the technical bits if you want to start building a MariaDB/MySQL driver.

Spring Data R2DBC will pick up a MySQL/MariaDB dialect as soon as a driver is available.

**Comment by krishna81m** [comment]
Curious, how big of a difference is for any JDBC compliant library/driver to work ? 
Wonder if you can guide us by pointing to core classes that need changing to work with MariaDB?

**Comment by schauder** [comment]
There is someone working on a MySql driver and my understanding is that MySql and MariaDB are really similar, so it might be easy to adapt that one.

Take a look at https://github.com/mirromutth/r2dbc-mysql

**Comment by dheeraj29** [comment]
@schauder @mp911de I am closing this issue in favour of #75 . As per MariaDB, it uses the same wire protocol of mysql itself.
https://mariadb.com/kb/en/library/mariadb-wire-protocol/

So it should be compatible without any issues.

**Comment by mp911de** [comment]
Done.
