### ISSUE TITLE
Improve documentation - spring framework version

### ISSUE THREAD

**Issue by Gunthervg** [spring-projects/spring-data-r2dbc#420]
https://docs.spring.io/spring-data/r2dbc/docs/1.1.2.RELEASE/reference/html/#r2dbc.getting-started

_Change the version of Spring in the pom.xml to be
<spring.framework.version>5.2.8.RELEASE</spring.framework.version>_

To override Spring Boot starter parent version use: <spring-framework.version>5.2.8.RELEASE</spring-framework.version> (- instead of .)

**Comment by mp911de** [comment]
Thanks for letting us know. That's fixed now.
