### ISSUE TITLE
MappingException when calling a modifying query method that returns kotlin.Unit

### ISSUE THREAD

**Issue by duke9509** [spring-projects/spring-data-r2dbc#421]
Modifying queries can be declared as returning `Void` if the result count information is not needed, [as shown here](https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#r2dbc.repositories.modifying). The equivalent declaration in Kotlin would be to use `Unit`. Currently, Spring Data R2DBC does not recognize the `Unit` type and attempts to convert the affected row count to `Unit` as if it were a projection, resulting in:
```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.lang.Integer!
```

An example repository method that is affected:
```kt
/** Deletes the association from [userId] to [associatedUserId], if it exists */
@Modifying
@Query("DELETE FROM user_association WHERE user_id = :userId AND associated_user_id = :associatedUserId")
suspend fun deleteUserAssociation(userId: Int, associatedUserId: Int)
```

A workaround is to simply use the Java `Void` type:
```kt
/** Deletes the association from [userId] to [associatedUserId], if it exists */
@Modifying
@Query("DELETE FROM user_association WHERE user_id = :userId AND associated_user_id = :associatedUserId")
suspend fun deleteUserAssociation(userId: Int, associatedUserId: Int): Void
```

I believe I've tracked this down to [`AbstractR2dbcQuery#getExecutionToWrap`](https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/repository/query/AbstractR2dbcQuery.java#L124) and plan to attempt a PR.

**Comment by mp911de** [comment]
Thanks for reporting the issue. Returning `Unit` should be no different from `Void` handling. We probably need some changes in Spring Data Commons to consider `Unit` also a primitive type.

**Comment by mp911de** [comment]
I filed DATACMNS-1779 to provide void type detection. Looking at the pull request, we can simplify it by quite a bit.
