### ISSUE TITLE
Sort sort in ReactiveSortingRepository not working in @Query

### ISSUE THREAD

**Issue by cheungyatho** [spring-projects/spring-data-r2dbc#426]
Am I doing something wrong with my code below?
 I always  got the same result 'asc order' no matter how I change the instance of parameter of fallAll method.
  if I remove the statement "@Query(value="select r.id from room r")", I got an error " RoomRepository.findAll(org.springframework.data.domain.Sort)! No property findAll found for type Room! " on sever start up
@Repository
public interface RoomRepository extends ReactiveSortingRepository<Room, Integer> {

    @Override
    Flux<Room> findAll();

    @Override
    @Query(value="select r.id from room r")
    Flux<Room> findAll(@SortDefault(sort=Room.TABLE_COLUMN_ID,direction= Sort.Direction.DESC)  Sort sort);

}
@RestController
@RequestMapping("/room")
public class RoomController {

    final private RoomRepository roomRepository;

    public RoomController(RoomRepository roomRepository) {
        this.roomRepository = roomRepository;
    }

    @GetMapping("/list")
    public Flux<Room> getRoomList() {

        return roomRepository.findAll(Sort.by(Sort.Direction.DESC,Room.TABLE_COLUMN_ID)).log();
    }

}

**Comment by mp911de** [comment]
Using `Sort` with `@Query` does not work as we would had to analyze and rewrite your query. We don't indent to follow this path as the complexity is hidden in more complex SQL statements where table have aliases or some advanced trickery with joins makes it next to impossible to properly update the desired query.

**Comment by cheungyatho** [comment]
> Using `Sort` with `@Query` does not work as we would had to analyze and rewrite your query. We don't indent to follow this path as the complexity is hidden in more complex SQL statements where table have aliases or some advanced trickery with joins makes it next to impossible to properly update the desired query.

If this is the case,I should remove the @query annotation. 
But if I removed the annotation I would get a warning like "no property found for type" even I did not override the find all method. And make the service shut down. The interface force me to override the method.
What's the proper way to implement the interface?
Do you have any examples for the case? 
Thanks

**Comment by mp911de** [comment]
Sort support was introduced with a recent change, see #407.

**Comment by cheungyatho** [comment]
> Sort support was introduced with a recent change, see #407.

- - Thanks for helps!
