### ISSUE TITLE
Entity callbacks aren't fired for repository methods (1.2.0-M2)

### ISSUE THREAD

**Issue by duke9509** [spring-projects/spring-data-r2dbc#433]
Entity callbacks are not fired for operations on repositories in 1.2.0-M2. They only work for queries made directly with the `R2dbcEntityOperations` from the context. This also breaks auditing (which is how I came across it).

Reproduction: https://github.com/duke9509/spring-data-r2dbc-repository-entity-callback-bug-repro/blob/master/src/main/kotlin/com/example/demo/DemoCallbacks.kt

I believe I've tracked this down to https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/repository/support/R2dbcRepositoryFactory.java#L119

`R2dbcEntityTemplate` discovers entity callbacks in its `setApplicationContext` hook, which requires it be a bean (or for someone to pass in the context manually). The above line constructs a new instance manually for each repository. This leads to `entityCallbacks` being null when the repository operations go through.

That being said, I don't know enough about the big picture of how all these factories are wired together to feel confident attempting a PR right now. I'd be happy to give it a go with some direction, though.

P.S., Thanks for all your hard work on this library/framework!

**Comment by mp911de** [comment]
Thanks a lot. That's fixed with #440 now. Care to give the new snapshot builds a try?
