### ISSUE TITLE
Syntax error in reference documentation at Query with SpEL expressions

### ISSUE THREAD

**Issue by kowhi** [spring-projects/spring-data-r2dbc#434]
website： https://docs.spring.io/spring-data/r2dbc/docs/1.1.3.RELEASE/reference/html/#r2dbc.repositories
`
@Query("SELECT * FROM person WHERE lastname = :#{[0]} }")  
  List<Person> findByQueryWithExpression(String lastname);
`
shoud be 
@Query("SELECT * FROM person WHERE lastname = :#{[0]}")

**Comment by mp911de** [comment]
Good catch, that's fixed now.
