### ISSUE TITLE
Add bind by a map of named parameters.

### ISSUE THREAD

**Issue by YixingCheng** [spring-projects/spring-data-r2dbc#435]
Currently the `bind()` implementations only support bind parameter and value one by one.
I am hoping that there can be something like
```
S bind(Map<String, Object> namedParamters);
```
The drawback of current binding one by one is that it assume that when we pass the the parametrized query to databaseClient's `execute()`, we already know exactly what are the names and indices of the parameters.
But when the queries are generated dynamically (which is our case), we don't know the exactly parameters we will use in the query and wish to use something like a `MapSqlParameterSource` to cache all the parameters and just pass them in.

**Comment by mp911de** [comment]
The drawback is that generics erase to `bind(Map)` so there's no way to distinguish between `Map<Integer, …>` and `Map<Object, …>`. I agree that an interface that accepts all bindings at once would be useful.

Can you file this ticket in https://github.com/spring-projects/spring-framework asking for Batch support? With the current version, we moved large parts of core R2DBC support into Spring Framework directly.
