### ISSUE TITLE
How to use the result of connect.createBatch? - Trying to insert multiple rows as a batch

### ISSUE THREAD

**Issue by neerajsu** [spring-projects/spring-data-r2dbc#436]
I wanted to insert rows in a batch instead of doing row by row. Seems like there is no option to insert a row as a batch via databaseClient, so I tried to insert using connection.createBatch()

```java
ConnectionFactoryUtils.getConnection(connectionFactory)
                .map(connection ->
                    Flux.from(connection.createBatch()
                     .add("insert into Account(iban,balance) values('BR430120980198201982',100.00)")
                     .add("insert into Account(iban,balance) values('BR430120998729871000',250.00)")
                    .execute())
                )
```

How do I map the result into an Account POJO? The result is of Type : `Mono<Flux<? extends Result>>`

**Comment by mp911de** [comment]
Right now, there's no Spring Data support for R2DBC batches. Can you file a ticket in https://github.com/spring-projects/spring-framework asking for Batch support?  With the current version, we moved large parts of core R2DBC support into Spring Framework directly.

**Comment by mp911de** [comment]
To consume batch results, you need to read the query result yourself. Typically, an `INSERT` returns only the generated Id or affected row count, not the actual row itself.
Here's an example how you could go about it:

```java
R2dbcConverter converter = …;

Flux<AccountInsertResponse> insert = Flux.usingWhen(ConnectionFactoryUtils
		.getConnection(connectionFactory), connection -> {
	return Flux.from(connection.createBatch().add(…)
			.execute()).flatMap(result -> result
			.map(new EntityRowMapper<>(AccountInsertResponse.class, converter)));
}, Connection::close, (c, err) -> c.close(), Connection::close);
```

**Comment by neerajsu** [comment]
I have a specific use case where I'm doing shading so I cannot use spring data. Thanks for the help on the code snippet and providing contextual information.

**Comment by mp911de** [comment]
Thanks for letting us know.

> I cannot use spring data

Then this ticket doesn't belong into this repository in the first place since R2DBC is not a Spring project.

**Comment by neerajsu** [comment]
@mp911de : I'm using this library, but not creating JPA repositories since I create multiple databases, tables with the same structure (pods). But what you provided is exactly what I needed, so it worked for me.
