### ISSUE TITLE
how to correct useing  left  join in R2DBC

### ISSUE THREAD

**Issue by yadong2000** [spring-projects/spring-data-r2dbc#437]
When i used left join and executed the sql then column mapping not matched like 
![image](https://user-images.githubusercontent.com/12443375/91379200-b16f9c00-e854-11ea-9c46-a5d81166d537.png)
![image](https://user-images.githubusercontent.com/12443375/91379221-bd5b5e00-e854-11ea-8638-58c6584182bf.png)

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
