### ISSUE TITLE
ERROR:  unterminated dollar-quoted string at or near "$set_timestamp$ BEGIN NEW.last_modified_date = CURRENT_TIMESTAMP" at character 71

### ISSUE THREAD

**Issue by cheungyatho** [spring-projects/spring-data-r2dbc#438]
my trigger is like

CREATE OR REPLACE FUNCTION trigger_set_timestamp()
    RETURNS TRIGGER AS $$
BEGIN
    NEW.last_modified_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

I run it through ConnectionFactoryInitializer.
I am using docker Postgres:latest
Is it a bug?

**Comment by mp911de** [comment]
Thanks for reporting the issue. It's a duplicate of spring-projects/spring-framework#19999
