### ISSUE TITLE
How to use transaction with repository?

### ISSUE THREAD

**Issue by ToffeeLu** [spring-projects/spring-data-r2dbc#44]
As [transaction doc](https://docs.spring.io/spring-data/r2dbc/docs/1.0.0.M1/reference/html/#r2dbc.datbaseclient.transactions) said, we can use transaction with calling the APIs of `TransactionalDatabaseClient`, but how can I do it if I want to use [repository](https://docs.spring.io/spring-data/r2dbc/docs/1.0.0.M1/reference/html/#r2dbc.repositories)?

What a potential solution I thought to approach my goal (**using transaction for multiple repositories' operators**) is:
```
transactionalDatabaseClient.beginTransaction();
userRepository.save(user);
passwordHistoryRepository.save(user.getPassword());
transactionalDatabaseClient.commitTransaction();
```
But it won't work, right? because in the [example](https://docs.spring.io/spring-data/r2dbc/docs/1.0.0.M1/reference/html/#r2dbc.datbaseclient.transactions), transaction is implemented by same `dataClient`, but `Repository` is using another client, How can I customize the `dataClient` in `Repository`?

And I checked the detail code, transaction is implemented based on `Connection`, to approach my goal, how can I let `dataClinet` and `Repository` use same `Connection`?

**Comment by mp911de** [comment]
Right now, transaction support is limited because we cannot use Spring Framework's `@Transactional`. For Repositories and transactions, please create  `TransactionalDatabaseClient` instead of `DatabaseClient` so repositories use the `TransactionalDatabaseClient`. 

When using transactions, you need to enclose calls to your repository with `inTransaction`:

```
UserRepository userRepository = …
TransactionalDatabaseClient transactionalDatabaseClient = …

transactionalDatabaseClient.inTransaction(db -> {
    return userRepository.save(…).then(userRepository.count());
});
```

All calls in  `inTransaction()` will reuse the same database connection.

**Comment by ToffeeLu** [comment]
@mp911de I tried your solution, wrapping repository operations in `inTransaction`, but it doesn't work.
``` java
TransactionalDatabaseClient client = TransactionalDatabaseClient.create(new PostgresqlConnectionFactory(...))
client
    .inTransaction(
        dc ->
            passwordHistoryRepository
                .save(new PasswordHistory(1))
                .then(Mono.error(new RuntimeException("6")))
                .then(passwordHistoryRepository.save(new PasswordHistory(2))
    )
```
The expected result should be no data in table, because this transaction should rollback after the exception throw, but the actual result is `2` is not in table, but `1` is. Why?

Also, I found that there is a filed called `databaseClientRef` in `EnableR2dbcRepositories`, I've tried set it to `TransactionalDatabaseClient` without the code of throwing exception, but an error always occurs:
```
RuntimeException, trace=java.lang.RuntimeException: Async resource cleanup failed after onComplete
	at reactor.core.publisher.FluxUsingWhen$CommitInner.onError(FluxUsingWhen.java:519)
...
Caused by: java.lang.IllegalStateException: Connection is closed!
	at org.springframework.data.r2dbc.function.connectionfactory.SingletonConnectionFactory.create(SingletonConnectionFactory.java:54)
	at org.springframework.data.r2dbc.function.DefaultTransactionalDatabaseClient.lambda$cleanup$7(DefaultTransactionalDatabaseClient.java:142)
```
And the debug log is same as using db client directly, I tried to check the source code, but found nothing, can you help?

**Comment by mp911de** [comment]
Thanks a lot for trying this out. Make sure to reuse the same `TransactionalDatabaseClient` for repository creation and `inTransaction` usage. The easiest approach is subclassing `AbstractR2dbcConfiguration` and overriding the `databaseClient(…)` method.

I will trace the `IllegalStateException` and see how to fix that.

**Comment by eau-de-la-seine** [comment]
Hi, according to the Spring documentation, we can now use `@Transactional`:
https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#r2dbc.datbaseclient.transactions

You have to create a `ReactiveTransactionManager`  bean first, see example 56.
