### ISSUE TITLE
Id is not set after Repository.save for primitive ids

### ISSUE THREAD

**Issue by Tienisto** [spring-projects/spring-data-r2dbc#444]
I am using the primitive id for my entities.
When I call `ReactiveCrudRepository.save(T)` and store the returned object, then the id is still `0`.
Even though in the database it is different than zero.

It is working fine if I use non-primitives as id (`Integer` in Java and `Int?` in Kotlin).

```java
// in Java

@GetMapping("/")
public Mono<Void> test() {
  User user = new User();
  user.setName("Max");
  return repo.save(user).flatMap(saved -> {
      System.out.println(saved.getId()); // still zero
      return Mono.empty();
   });
}
```

```kotlin
// in Kotlin

@Table("my_user")
data class User(@Id var id: Int = 0, var name: String = "") 

// I am using CoroutineCrudRepository here but using ReactiveCrudRepository gives me the same result
val saved = repo.save(User(0, "Max"))
println(saved.id) // id is still zero
```

```sql
-- Postgres table

CREATE TABLE my_user (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);
```

Version: 1.2.0-M2
Database: PostgreSQL

**Comment by mp911de** [comment]
Thanks for reporting the issue. The check whether the ID value should be assigned didn't consider primitive ID values.

**Comment by mp911de** [comment]
That's fixed now.

**Comment by Tienisto** [comment]
Thank you. Looking forward for the next release 🙂
