### ISSUE TITLE
Register R2dbcConverter bean and deprecate ReactiveDataAccessStrategy

### ISSUE THREAD

**Issue by pmaedel** [spring-projects/spring-data-r2dbc#447]
The [docs](https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#mapping.explicit.converters) state that R2dbcConverter is recommended to do most of the work.

R2dbcConverter however must be obtained via ReactiveDataAccessStrategy.
This is fine, but should be documented, as I did expect R2dbcConverter to be readily available as a Bean when being so heavily advertised.

**Comment by mp911de** [comment]
`ReactiveDataAccessStrategy` originates from having `DatabaseClient` using a pluggable data access strategy. Now that `DatabaseClient` went into Spring Framework and we have a proper `R2dbcEntityTemplate`, we no longer need `ReactiveDataAccessStrategy` and can move its parts into `R2dbcConverter`. A good first step would be exposing `getConverter()` on `R2dbcEntityOperations` to align with the other Spring Data modules.

**Comment by mp911de** [comment]
I repurposed this ticket to align our converter infrastructure with the other Spring Data modules. `R2dbcConverter` is now registered as bean and `ReactiveDataAccessStrategy` is deprecated.
