### ISSUE TITLE
Possibly support @Transient fields for Kotlin data classes without  separate persistence constructor

### ISSUE THREAD

**Issue by pmaedel** [spring-projects/spring-data-r2dbc#449]
The necessity to provide a separate persistence constructor for kotlin data classes with `@Transient` properties seems odd to me.

```kotlin
data class Fruit(
    @Id
    val id: Long? = null,
    val treeId: Long,
    val ripeness: Ripeness,
    @Transient
    val joinedTree: Tree? = null
) {

    @PersistenceConstructor
    constructor(
        id: Long?,
        treeId: Long,
        ripeness: Ripeness
    ) : this(
        id = id,
        treeId = treeId,
        ripeness = ripeness,
        joinedTree = null
    )
}
```

I would think it should be possible to exclude a @Transient field during mapping for which default value is defined?

**Comment by mp911de** [comment]
Thanks for raising a ticket. Improving `@Transient` property handling for constructor properties is indeed worth considering. Until that's in place, we should add `@Value` support so the object creation can spawn a `null` value which removes the need for an additional persistence constructor. See #450.

**Comment by mp911de** [comment]
We discussed the issue with our team and concluded that opening persistence constructors for transient properties contributes to ambiguity. The strict behavior allows for exact reasoning what's happening. Language features such as Kotlin's defaulting mechanism allow for graceful defaults. For now, we recommend using `@Value("null")`.
