### ISSUE TITLE
Special chacacter in database password string cannot be split out

### ISSUE THREAD

**Issue by happyfeetw** [spring-projects/spring-data-r2dbc#470]
Hi,
This occurred when I tried to connect database using a password string ends with character '@'. 
The stack trace below shows the reason:

> org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is java.net.UnknownHostException: @localhost:3306: nodename nor servname provided, or not known
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:70) ~[spring-data-r2dbc-1.1.4.RELEASE.jar:1.1.4.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.spike.roedeercarnival.controller.TestFindController#list() [DispatcherHandler]
	|_ checkpoint ⇢ HTTP GET "/testFind/list" [ExceptionHandlingWebHandler]
Stack trace:
		at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:70) ~[spring-data-r2dbc-1.1.4.RELEASE.jar:1.1.4.RELEASE]
		at reactor.core.publisher.Mono.lambda$onErrorMap$30(Mono.java:3286) ~[reactor-core-3.3.10.RELEASE.jar:3.3.10.RELEASE]

So I looked up in source code and found that in `ConnectionUrlParser.java` line 124, code `int atIndex = authorityToUse.indexOf('@');` is able to find index of only the first matched character '@' in `authorityToUse` string. So in the cases of passwords end with the exact character '@',  the next line code will get a wrong password and consequently get a wrong hostname.

Last of all, I'm willing to fix this little bug, with permission :)

**Comment by happyfeetw** [comment]
I personally think that modifying the ` indexOf()` method to `lastIndexOf()` method.
But maybe in the future, it would be better for r2dbc to enable to read db configurations from application.yml or application.properties. :)

**Comment by happyfeetw** [comment]
And BTW, the problem source file is in package `io.r2dbc.spi` but I failed to find its GitHub repo. So sad

**Comment by mp911de** [comment]
Special characters need to be escaped by using url encoding (percent encoding). R2DBC is a general purpose SPI that isn't tied to a particular runtime (Spring, Micronaut, ...) so it doesn't make sense to tie it to a particular config file mechanism.

**Comment by happyfeetw** [comment]
> Special characters need to be escaped by using url encoding (percent encoding). R2DBC is a general purpose SPI that isn't tied to a particular runtime (Spring, Micronaut, ...) so it doesn't make sense to tie it to a particular config file mechanism. 
> 
> You can find the R2DBC repo here: https://github.com/r2dbc/r2dbc-spi

Understood. So probably I need to open an issue to R2DBC repo and make a PR to the spi module?

**Comment by mp911de** [comment]
Closing in favor of r2dbc/r2dbc-spi#183.
