### ISSUE TITLE
Contradictory documentation of DatabaseClient.insert() 

### ISSUE THREAD

**Issue by Ahimsaka** [spring-projects/spring-data-r2dbc#471]
[Section 11.7.2 of the spring reference docs](https://docs.spring.io/spring-data/r2dbc/docs/current-SNAPSHOT/reference/html/#reference ) states: 

> Methods for INSERT operations
>The insert() entry point exposes the following additional methods to provide options for the operation:
>- into (Class<T>): Specifies the target table using a mapped object. **By default, it returns results as T.**

But the [API documentation for DatabaseClient.TypedInsertSpec](https://docs.spring.io/spring-data/r2dbc/docs/1.1.0.M1/api/index.html?org/springframework/data/r2dbc/core/DatabaseClient.TypedInsertSpec.html) shows that both signatures for TypedInsertSpec.using() return DatabaseClient.InsertSpec<Map<String,Object>>. This matches the behavior observed in production: calling TypedInsertSpec.using(new T()) turns it into an InsertSpec, causing a fetch operation to return Map<String, Object>. 

I think it would be ideal if client.insert().into(T.class).using(new T()).fetch().one() returned Mono< T >, but I don't want to submit that as the issue, because the behavior described in the API docs is accurate, functional, and can easily be used to recreate an object of type T. In the short term, I am only suggesting that the reference documentation be updated to say that the default return of an insert operation is Map<String, Object>, and not T.

**Comment by mp911de** [comment]
Thanks for raising the issue. You're right, we should fix the docs. The mentioned section got removed for `master` as `DatabaseClient` was moved into Spring Framework directly and our variant is now deprecated. So we will apply the documentation fix onto the maintenance branch.
