### ISSUE TITLE
Projections doesn't work using data-repositories

### ISSUE THREAD

**Issue by alesikov** [spring-projects/spring-data-r2dbc#475]
Hello,
Unfortunately any kind of projections doesn't work with data-repositories. It's probably caused by https://github.com/spring-projects/spring-data-r2dbc/blob/c3cb70f5ecf983ef54c0e7a7c0d3611f0c726475/src/main/java/org/springframework/data/r2dbc/repository/query/AbstractR2dbcQuery.java#L136 which could be probably solved by the following
`return returnedType.isProjecting() ? returnedType.getReturnedType() :  returnedType.getDomainType();`

The above was tested locally and it worked, please kindly check.

**Comment by mp911de** [comment]
Can you provide a test case that shows that projections are broken? Our [integration tests for projections](https://github.com/spring-projects/spring-data-r2dbc/blob/d3823947aa42e41aff085157f76e6dc58de31ee8/src/test/java/org/springframework/data/r2dbc/repository/AbstractR2dbcRepositoryIntegrationTests.java#L146-L157) pass so it would be good to know in which case projections don't work.

**Comment by alesikov** [comment]
My bad, forgot to mention that the issue is related to `@Query`-annotated methods which produce class-based projections.
Managed to reproduce the same using integration tests your mentioned previously, the proposed fix still works. Please try testing against the following:
```
// Projection
static class NamedDTO {
    String doesntBelongToEntity;
}

// Repository method
@Query("SELECT name as doesnt_belong_to_entity FROM legoset")
Flux<NamedDTO> projectingWithQuery();

**Comment by mp911de** [comment]
DTO projections work actually on top of the repository entity type in the sense that DTO's are a subset of entity properties. Additional properties aren't really expected here.


The following code should explain the underlying assumptions:

```java
class Person {
    @Column("fn")
    String firstName;
}

class PersonDto {
   String firstName;
}
```


Assuming the `firstName` property maps onto the `fn` column in your database, then a derived query would apply proper fieldname mapping:

```java
Flux<PersonDto> findBy();
```

resulting in the SQL:

```sql
SELECT fn FROM person;
```

If we now translate that behavior to String-based queries, what would the select look like for:


```java
@Query("SELECT … FROM person");
Flux<PersonDto> findBy();
```

Is it `SELECT fn FROM person` or would it rather be `SELECT fn AS firstName FROM person`?

**Comment by mp911de** [comment]
Likely, using the domaintype -> DTO for derived query processing and reading directly into the DTO for string-based queries is a good middleground as for string queries the type declaration and `@Query` are pretty close. For derived queries, you typically don't have much control over the projected queries.

**Comment by mp911de** [comment]
That change is in place now.

**Comment by alesikov** [comment]
Thank you for the amazing project
