### ISSUE TITLE
Link to stackoverflow in readme points to incorrect url

### ISSUE THREAD

**Issue by ruffCode** [spring-projects/spring-data-r2dbc#479]
In the "Getting Help" section, the link to stackoverflow has the correct description "spring-data-r2dbc", however, it links to "spring-data". Should be changed to [https://stackoverflow.com/questions/tagged/spring-data-r2dbc](https://stackoverflow.com/questions/tagged/spring-data-r2dbc)

**Comment by mp911de** [comment]
We generally link to the `spring-data` tag for all of our modules. While there is a fair amount of module-specific questions, we found that the majority of questions are generally related to Spring Data.

**Comment by mp911de** [comment]
Sorry, my bad, I missed that this ticket is related to the repository readme.

**Comment by mp911de** [comment]
That's fixed now.
