### ISSUE TITLE
MySQL auto_increment not returned after save()

### ISSUE THREAD

**Issue by mindhaq** [spring-projects/spring-data-r2dbc#486]
As for almost all cases, the id of my entity will not be null, I want to define that field as such in Kotlin:

```kotlin
data class Entity (
    @Id
    val id: Long = 0 
)
```

When I save a new entity with repository's save() method, it gets INSERTed as expected, with a new id auto_generated by the database. However, the returned entity still has an id of 0, and not the generated value.

If I change the entity declaration with a null id, and use null as id for the new entity, this is not the case, and the returned entity has the new id.

```kotlin
data class Entity (
    @Id
    val id: Long? = null 
)
```

Experiments with implementing interface Persistable did not lead to different results.

**Comment by mindhaq** [comment]
I'm not sure, but it sounds similar to spring-projects/spring-data-relational#1274

**Comment by mp911de** [comment]
Auto-generated Id's should be returned by issuing `Statement.returnGeneratedKeys(…)` and then consuming the resultset to populate the Id. We need to investigate/debug what happens here.

**Comment by Tienisto** [comment]
After spring-projects/spring-data-r2dbc#444, non-nullable fields should be working in kotlin.
Did you test it in the latest snapshot?

**Comment by mp911de** [comment]
I wasn't able to reproduce the issue. 
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mindhaq** [comment]
I just ran my test with spring-boot:2.4.0-M4 and spring-data-r2dbc:1.2.0-RC2 and it worked as expected.

Sorry for the duplicate.
