### ISSUE TITLE
Support for multi-tenant

### ISSUE THREAD

**Issue by itzikiusa** [spring-projects/spring-data-r2dbc#496]
Hi, is there good example on how to use multi tenancy application with r2dbc(and pool)
using mysql
is it supported?

**Comment by mp911de** [comment]
You can achieve multi-tenancy using `AbstractRoutingConnectionFactory` where multiple tenants are using their own database/connection/schema.

**Comment by itzikiusa** [comment]
@mp911de thanks, i'm already using it, but having issues configuring r2dbc pool with it(once in a while it is losing connections)
currently i've commented to r2dbc pool options, and using just plain mysql driver

when using single connection factory, i don't have this issue

**Comment by mp911de** [comment]
Please file a bug report against [r2dbc-pool](https://github.com/r2dbc/r2dbc-pool) along with more context so that your issues can be fixed there.

Closing this ticket here since there's nothing we can do here.

**Comment by hantsy** [comment]
@mp911de This `AbstractRoutingConnectionFactory` is easy to build multitenancy applications with multi database, or schemas. 

But how to implement it with a shared database and using a column as tenant discrimination?

**Comment by mp911de** [comment]
There's no such support in Spring Data R2DBC or Spring Data JDBC as each query would have to be augmented and String-based queries would require parsing and rewrite. We don't want to go down that route.

**Comment by hantsy** [comment]
Hope there is a generic solution like GORM provided for Spring Data projects, see: http://gorm.grails.org/latest/hibernate/manual/index.html#multiTenancy
