### ISSUE TITLE
Migration 1.2.0 DatabaseClient.sql

### ISSUE THREAD

**Issue by Camsteack** [spring-projects/spring-data-r2dbc#500]
Hi,

I am trying to migrate my application to 1.2.1 and I am having trouble with the new database client DSL to execute SQL statements. With the previous DatabaseClient you could do 

```
databaseClient.execute(someSql).as(Type.class).fetch().all()
```

But now the `GenericExecuteSpec` doesn't provide an `as` method. What would be the way to achieve the same result now without having to have a custom mapper for each type ?

Thanks a lot

**Comment by tomas-c** [comment]
Just had to do a migration myself, [the upgrade guide was a good starting point](https://docs.spring.io/spring-data/r2dbc/docs/1.2.x/reference/html/#upgrading.1.1-1.2).

Seems the options are:
- Rewrite with Spring Data Repositories (you can use @Query annotation for custom SQL)
- Rewrite with R2dbcEntityTemplate
- Use the GenericExecuteSpe.map() method with MappingR2dbcConverter

For the last option in Kotlin:
```kotlin
databaseClient
    .execute(someSql)
    .as(Type::class.java)
    .fetch()
    .all()
``` 
becomes 
```kotlin
databaseClient
    .sql(someSql)
    .map{ row, meta -> mappingR2dbcConverter.read(Type::class.java, row, meta)}
    .all()
```

**Comment by MuizMahdi** [comment]
I couldn't find any example on using the MappingR2dbcConverter in the [docs](https://docs.spring.io/spring-data/r2dbc/docs/1.2.x/reference/html/#mapping).

1. Do we need to map the row to object manually? 
2. Wasn't it more convenient to use .as(Type.class)?

**Comment by rjaros** [comment]
I have created a small Kotlin project, which addresses this issue:
https://github.com/rjaros/r2dbc-e4k

**Comment by mp911de** [comment]
`DatabaseClient` is now part of Spring Framework and there's already a ticket for this topic with https://github.com/spring-projects/spring-framework/issues/26021 so closing this one as duplicate.
