### ISSUE TITLE
SQL statements not logged anymore in spring-data-r2dbc:1.2.1

### ISSUE THREAD

**Issue by hansdesmet** [spring-projects/spring-data-r2dbc#503]
Spring Boot 2.4.0 uses spring-data-r2dbc:1.2.1
When I add **logging.level.org.springframework.data.r2dbc=DEBUG** to **application.properties**
and run following test:
````java
@SpringBootTest
class SqlstatementsnotloggedTest {
    @Autowired
    PersonRepository personRepository;
    @Test
    void sqlStatementIsNotLogged() {
        var count = personRepository.count();
        StepVerifier.create(count).expectNextCount(1).verifyComplete();
    }
}
````
I don't see the SQL statement logged.

When I switch to Spring Boot 2.3.6.RELASE, which uses spring-data-r2dbc:1.1.5
I see the SQL statement logged:
2020-11-19 13:41:38.732 DEBUG 8688 --- [           main] o.s.d.r2dbc.core.DefaultDatabaseClient   : **Executing SQL statement [SELECT COUNT(persons.id) FROM persons**]

You find a project which shows this on https://github.com/hansdesmet/sqlstatementsnotlogged

**Comment by mp911de** [comment]
With Spring Data R2DBC 1.2, we use Spring R2DBC's `DatabaseClient`. You will need to upgrade your logging config to `logging.level.org.springframework.r2dbc=…` (instead of `logging.level.org.springframework**.data**.r2dbc`).

**Comment by hansdesmet** [comment]
Thanks Mark for the quick reply.
Now it works.
I think the documentation would better be changed.
Now it says:
![image](https://user-images.githubusercontent.com/5030757/99676818-44495c80-2a79-11eb-92b3-3b18391841a3.png)

**Comment by mp911de** [comment]
Good catch, that's updated now.
