### ISSUE TITLE
@Version variable with primitive type does not work

### ISSUE THREAD

**Issue by hansdesmet** [spring-projects/spring-data-r2dbc#504]
Given an entity:
````java
@Table("persons")
class Person {
    @Id
    private final long id;
    private String name;
    @Version
    private final int version;
    Person(long id, String name, int version) {
        this.id = id;
        this.name = name;
        this.version=version;
    }
    public long getId() {
        return id;
    }
    public String getName() {
        return name;
    }
    public int getVersion() {
        return version;
    }
    public void setName(String name) {
        this.name=name;
    }
}
````
and a repository
````java
interface PersonRepository extends ReactiveCrudRepository<Person, Long> {}
````
and a script to create the table in H2 and add a record
````sql
create table persons (
    id serial primary key,
    name varchar(255),
    version int not null
);
insert into persons(name, version) values ('Joe', 0);
````
the following test 
````java
@SpringBootTest
class PersonRepositoryTest {
    @Autowired
    PersonRepository personRepository;
    @Test
    void test() {
        var person = personRepository.findById(1L).block();
        person.setName("Jack");
        personRepository.save(person).block();
    }
}
````
produces following exception:
_io.r2dbc.spi.R2dbcDataIntegrityViolationException: [23505] [23505] Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.PERSONS(ID) [1, 'Joe', 0]"; SQL statement:
INSERT INTO persons (id, name, version) VALUES ($1, $2, $3) [23505-200]_
You see the save method sends an insert **statement** where it should send an **update** statement.

When i use **Integer** for the version variable:
````java
@Table("persons")
class Person {
    @Id
    private final long id;
    private String name;
    @Version
    private final Integer version;
    Person(long id, String name, Integer version) {
        this.id = id;
        this.name = name;
        this.version=version;
    }
    public long getId() {
        return id;
    }
    public String getName() {
        return name;
    }
    public Integer getVersion() {
        return version;
    }
    public void setName(String name) {
        this.name=name;
    }
}
````
there is no exception. The save method sends a correct update statement:
2020-11-20 08:33:46.292 DEBUG 6656 --- [           main] o.s.d.r2dbc.core.DefaultDatabaseClient   : Executing SQL statement [SELECT persons.* FROM persons WHERE persons.id = $1 LIMIT 2]

I tested this with Spring Boot 2.4.0

**Comment by mp911de** [comment]
This works as intended. Spring Data checks whether the version property is set to the default Java value to determine whether the entity is new or should be considered existing. The default for `int` is `0` while the default for `Integer` is `null`.

Loading a row with a version property set to zero using primitives leaves Spring Data no chance to know whether the entity was loaded from the database. If you want to use zero as first version number, then please use `Integer` instead of `int`.  See also the reference documentation on [Entity State Detection Strategies](https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#r2dbc.entity-persistence.state-detection-strategies).

**Comment by hansdesmet** [comment]
Hi Mark,
Thanks for the quick response.

You are right: when i change the last line in my script to
insert into persons(name, version) values ('Joe', **1**);
the test works.

You can close this issue.
