### ISSUE TITLE
Batch inserts options with transactions.

### ISSUE THREAD

**Issue by monishdas82** [spring-projects/spring-data-r2dbc#507]
Hi Team,
 I have a usecase where I have to do bunch of fetchs and inserts and would like find out which option is better with transaction.

1. I tried to create a batch in transaction and it just has hangs. Below is the code an not sure why it does that. 
    **@Transactional 
    @GetMapping("/batchFetchData")
    public Flux<Object> batchFetch() {
        long startTime = System.currentTimeMillis();
        Mono.from(databaseConfiguration.connectionFactory().create())
                .flatMapMany(connection -> Flux.from(connection
                        .createBatch() /* **Creating batch***/
                        .add("SELECT * FROM xtable where xId = 232323")
                        .add("SELECT * FROM ytable where yId = 454545")
                        .add("SELECT * FROM ztable where zId = 676767")
                        .execute()));  
//                        .execute())).as(StepVerifier::create)
//                .expectNextCount(3)
//                .verifyComplete();  
        LOGGER.info("Time taken to batchFetch "+(System.currentTimeMillis() - startTime));
    return null;
    }**

2. If not the above approach Do you suggest the below of running batch of sql queries with transaction

   **// Create a list or batch of SQL statements
         List<String> batch = Arrays.asList(
               "CREATE DATABASE IF NOT EXISTS test;",
               "CREATE OR REPLACE TABLE IF NOT EXISTS test.contact_copy(id INT PRIMARY KEY AUTO_INCREMENT,first_name VARCHAR(50),last_name VARCHAR(50),email VARCHAR(250)) ENGINE=InnoDB;",
               "INSERT INTO test.contact_copy SELECT * FROM test.contact;");
         //Run the batch of SQL statements
         batch.forEach(stmt -> client.execute(stmt)
               .fetch()
               .rowsUpdated()
               .as(StepVerifier::create)
               .expectNextCount(1)
               .verifyComplete());**

**Comment by mp911de** [comment]
You want to make use of `ConnectionFactoryUtils.getConnection(…)` to obtain a connection that is bound to the transaction. Please note that you need to consume the results coming from `Batch.execute()` (or `Statement.execute()`) to drain the response from the transport channel. R2DBC is stream-oriented applying backpressure meaning if you don't consume the response, then you won't be able to continue with query execution.
