### ISSUE TITLE
Does R2DBC support Rollback if one query fails?

### ISSUE THREAD

**Issue by sumancoder** [spring-projects/spring-data-r2dbc#516]
```java
primaryClient.execute("INSERT INTO person (id, firstname, lastname) VALUES(1009, 's', 'sds')")
        /*.bind("id", 1089)
        .bind("firstaname", "Joe")
        .bind("lastname", "asdad")*/
        .fetch().rowsUpdated()
        .then(primaryClient.execute("INSERT INTO contacts (id, name) VALUES(1231, 'name')")
               /* .bind("id", "joe")
                .bind("name", "Joe")
                .fetch().rowsUpdated())*/
        .then()
        .as(transactionalOperator::transactional));
```

I have this above code. What I am trying is I would like to see if my second INSERT statement fails then the first INSERT statement should get rollsback . But current behaviour I see is even if the second statement gives me error still the first one persists in DB. COuld you please help?

**Comment by mp911de** [comment]
Rollback on error is supported. In your code, only the second statement runs in a managed transaction. Note the position of `.as(transactionalOperator::transactional)` vs. `.as(transactionalOperator::transactional))`.

To let the first statement participate in the managed transaction, make sure that `.as(transactionalOperator::transactional)` affects the entire reactive sequence, not only the sequence in `.then(…)`.
