### ISSUE TITLE
Duplicate entry for key with ReactiveCrudRepository.save

### ISSUE THREAD

**Issue by lujijiang** [spring-projects/spring-data-r2dbc#517]
By default, the save() method inspects the identifier property of the given entity. If the identifier property is null, then the entity is assumed to be new. Otherwise, it is assumed exist in the datbase.

But got error:Duplicate entry for key,why?

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

Please also verify your expectations against the [Entity State detection strategies](https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#r2dbc.entity-persistence.state-detection-strategies).

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by MVTalent** [comment]
Good day! Such a situation - in the database for the entity (table) MyTestObject there is a unique key - this is a personal account (personalAccount column). There is a method that processes incoming AccountObjects. If several identical AccountObject objects arrive "at once" (according to the personalAccount field), an error occurs 

`23505 duplicate key value violates unique constraint 'personal_account_uindex'. `

```
@Transactional
public Mono<MyTestObject> process(AccountObject accountObject) {
	return myTestObjectService.findById(accountObject.getId())
			.flatMap(myTestObject -> {
				//update myTestObject from accountObject
				return myTestObjectRepository.save(myTestObject)
						.doOnSuccess(response -> logging)
						.doOnError(ex -> logging);
			})
			.switchIfEmpty(Mono.defer(() -> {
				//map accountObject to myTestObject
				return myTestObjectRepository.save(myTestObject)
						.doOnSuccess(response -> logging)
						.doOnError(ex -> logging);
			}));
}
```

myTestObjectService.findById - is findById ReactiveCrudRepository 
myTestObjectService.save - is save ReactiveCrudRepository

```
public class MyTestObject {

    @Id
    //with @GeneratedValue(strategy = GenerationType.IDENTITY) doesn't work either
    private Integer id;

    private String name;

    private String family;

    private String personalAccount;
}
```
Table is
```
CREATE TABLE IF NOT EXISTS my_test_object
(
    id               SERIAL NOT NULL PRIMARY KEY,
    "name"           VARCHAR(50),
    "family"         VARCHAR(50),
    personal_account VARCHAR(50)
);

CREATE UNIQUE INDEX IF NOT EXISTS personal_account_uindex ON my_test_object (personal_account);
```

**Comment by mp911de** [comment]
`@GeneratedValue(strategy = GenerationType.IDENTITY)` is a JPA annotation that isn't considered by R2DBC. 

Please provide a minimal runnable sample that can reproduce your problem so we can investigate what is going on.

**Comment by mp911de** [comment]
With the code above, I'm not able to reproduce the issue, which is why I was asking for a reproducer. Without a way to reproduce the problem, this ticket isn't actionable.
