### ISSUE TITLE
IgnoreCase works only if a String property can be resolved to a column

### ISSUE THREAD

**Issue by hakandilek** [spring-projects/spring-data-r2dbc#518]
Hello everyone,

I have the following select query using `R2dbcEntityTemplate`:

```java
template.select(Book.class)
        .matching(query(where("TITLE").like("%" + matchingTitle + "%").ignoreCase(true)))
        .all();
```

When I run this, it produces the following query:

```sql
SELECT T_BOOK.* FROM T_BOOK WHERE T_BOOK.TITLE LIKE UPPER($1) {1: '%title%'}
```

I would expect that `T_BOOK.TITLE` would also be wrapped with the `UPPER()` function like the following:

```sql
SELECT T_BOOK.* FROM T_BOOK WHERE UPPER(T_BOOK.TITLE) LIKE UPPER($1) {1: '%title%'}
```

but it doesn't. In this case it does not produce real case-insensitive queries.

**Comment by mp911de** [comment]
Our `QueryMapper` validates ignore-case queries against the domain model. If the underlying property is a `String`, then we're wrapping the column name with `UPPER(…)`.

Omitting that check seems to fix the issue.

**Comment by hakandilek** [comment]
@mp911de thanks for the fix!

**Comment by ilkerkocatepe** [comment]
Hello everyone, I'm sorry for writing an old issue, but I didn't want to create new one.
I have a problem about Turkish chars. 
For instance; "ilker" is the query parameter and the name in db is "İlker". These don't match.
Is there a way to use LOWER instead UPPER? I thought this will help me.
