### ISSUE TITLE
Don't depend on MSSQL JDBC driver

### ISSUE THREAD

**Issue by thekalinga** [spring-projects/spring-data-r2dbc#52]
Currently, when I add this library as a dependency, it automatically pulls `mssql-jdbc` driver. I am not sure if this intentional. Can someone please check if this is indeed intentional?

Ref: 
https://github.com/spring-projects/spring-data-r2dbc/blob/3d1041c0c8be84ad3c1805c7a34ea1c8e891d1a5/pom.xml#L241-L245

**Comment by mp911de** [comment]
Good catch. That’s a bug. Care to submit a pull request to make the driver an optional dependency?
Am 20. Jan. 2019, 15:41 +0100 schrieb Ashok Koyi <notifications@github.com>:
