### ISSUE TITLE
Failed to update table [xxxx]  Row with id [12] does not exist when no data was updated

### ISSUE THREAD

**Issue by bigdoubletao** [spring-projects/spring-data-r2dbc#522]
for example 
user:{"id":12,"name":"zt"}
save
user:{"id":12,"name":"zt"}
Failed to update table [xxxx]  Row with id [12] does not exist when no data was updated

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
