### ISSUE TITLE
Connection Pool in ConnectionFactoryInitializer (r2dbc postgresql)

### ISSUE THREAD

**Issue by dericop** [spring-projects/spring-data-r2dbc#527]
Hi, everyone: 

I was trying to configure the connection pool using ConnectionFactoryInitializer Bean but it's not working. The only way that is working to me is modify the maxSize in **spring.r2dbc.url** like: 

```
spring.r2dbc.url=r2dbc:pool:postgres://localhost:5432/postgres?maxSize=11
```

The problem is that I want to do it programmatically. Do you now if is posible use ConnectionFactoryInitializer bean and use a custom pool to r2dbc postgreSQL?

Thanks!!

**Comment by mp911de** [comment]
`spring.r2dbc.url` is a Spring Boot property. If you're using Spring Boot, please file a ticket there.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
