### ISSUE TITLE
Calling a Stored Procedure with input parameters mysql

### ISSUE THREAD

**Issue by upen4a3** [spring-projects/spring-data-r2dbc#536]
I am trying to call Stored Proc using databaseClient which returns a String.But I am getting the below exception.Do I have to add anything to call SP from r2dbc.My stored procedure looks like this.How to call SP using database-client

```
CREATE PROCEDURE usp_get_data(in someId varchar(255),
in someName varchar(255),
out email varchar(255))
BEGIN
	SELECT email  FROM products where id=:someId and name=:someName LIMIT 1;
END //
```

Below is my code.

 String STORED_PROC = "call usp_get_data(:someId,:someName)"
```

 def result = databaseClient.execute(STORED_PROC)
                .bindNull("someId","someId")
                .bindNull("someName", "someName")
                .as(String.class)
                .fetch().one()
```
 Incorrect number of arguments for PROCEDURE usp_get_data expected 3, got 2))

**Comment by mp911de** [comment]
That doesn't look like a Spring Data issue. Have you tried reproducing the issue using R2DBC SPI only against the MySQL driver?

**Comment by upen4a3** [comment]
sorry my SP was wrong .This is how i resolved it 
https://stackoverflow.com/questions/66215142/r2dbccalling-stored-proc-in-mysql-with-in-and-out-parameters
