### ISSUE TITLE
How to insert many (e.g. with a Publisher) via R2dbcEntityTemplate

### ISSUE THREAD

**Issue by gs-husam** [spring-projects/spring-data-r2dbc#545]
Hi,

Is there a recommended replacement of `using(Publisher<T> objectToInsert);` from the deprecated `DatabaseClient.insert().into(...).using(Flux.fromIterable(...))` function in `R2dbcEntityTemplate` or elsewhere? Only able to find `using(T object)` methods which assume a single entity, but I may just be missing something.

Thanks in advance :)

**Comment by mp911de** [comment]
`R2dbcEntityTemplate` does not expose batch operations.

**Comment by gs-husam** [comment]
@mp911de I see, thanks for the color. What is the recommended migration path then for typed bulk inserts? Presume there would be an alternative given the older `DatabaseClient` is deprecated. The documentation still says it is supported as well, perhaps stale? https://docs.spring.io/spring-data/r2dbc/docs/1.2.5/reference/html/#r2dbc.entityoperations.fluent-api.insert

**Comment by gs-husam** [comment]
@mp911de just following up, is there a planned alternative for `insert().into(...).using(somePublisher)` where `somePublisher` can be a `Flux`? As the docs mention that should still be possible to insert many (although may not necessarily be in a single batch).

Thanks!
