### ISSUE TITLE
Reuse Dialect support provided by Spring Data Relational

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-r2dbc#55]
With the introduction of the QueryBuilder API and the renderer in Spring Data Relational we need to move a part of the dialect-specifics into Spring Data Relational (e.g. paging behavior queries).

**Comment by mp911de** [comment]
Depends on spring-projects/spring-data-jdbc#125.

**Comment by schauder** [comment]
The PR is merged.
