### ISSUE TITLE
Paging in Reactive repositories

### ISSUE THREAD

**Issue by kacperfronc** [spring-projects/spring-data-r2dbc#565]
I'm having issues with pagination in repositories. The issue isn't really that it doesn't work, it's just that it requires more work and I would like some of those things to happen automatically.

So first - paging seems like a bit of an afterthought.
In regular spring data, methods like `findAll` accept pageable, in reactive spring those can be added, you can provide a pageable in custom method but it's not there by default (only sort is).

The thing is though, that it doesn't return `Page` or a `Slice`, only `Flux`. And when I try to make it return `Mono<Page>` it says `must not use sliced or paged execution. Please use Flux.buffer(size, skip)` which is a great idea but in my case I need to return the count of all elements (or pages) too.

In blocking spring data I get this out of the box behind the scenes, while in reactive I have to make a separate call to count elements.

Maybe I'm missing something in docs, in this case, please, point me to it.

Is it something you're thinking of, adding support of `Mono<Page>/Mono<Slice>`? I think it would make life a bit easier.

My confusion comes from the fact that it seems half-baked. I can provide `Pageable` to custom methods although no existing one has it by default. But, although I can provide it, I can't get the `Page` or `Slice`, so I can't know how many pages there are, which in many cases isn't good enough.
And on top of that, this error seems a bit confusing too:
`must not use sliced or paged execution. Please use Flux.buffer(size, skip)`
What's the point of allowing the `Pageable` as a parameter then? The error sounds like I shouldn't be providing `Pageable` as a parameter because I can just use `size` and `skip`, but it only throws it when I'm using `Page/Slice` as a returning type.
So if I, for example, use this signature:
```
Mono<Page<Entity>> findAllByParamNotNull(Pageable pageable);
```
I'm getting that error but here I don't:
```
Flux<Entity> findAllByParamNotNull(Pageable pageable);
```
So if I listen to this error and change the return type as above, now it compiles and works but the hint that I got from the error doesn't help at all, I can't use `skip` or `size` on the Flux that I got, because that flux is already paged.
Sounds like this error should be displayed when I provide `Pageable` as a parameter because it better describes that scenario.

Also, in that topic, I can provide a `Pageable` as a parameter but I can't make a `findAll(Pageable)` method.
I understand that I can call `Flux.buffer(skip,size)` but if I do that using h2 then the logged SQL query doesn't have any offset or limit. Can I always trust the drivers to behave correctly behind the scenes and actually pull only what I want?

**Comment by mp911de** [comment]
We deliberately went for the current design. There are a few aspects that come together of which having no proper type for reactive pagination is only the tip of the iceberg. 

A `Page` is constructed from the count (typically) and the actual data. To determine whether a count query is required, the entire result needs to be consumed. Consuming results upfront removes the streaming capability of reactive APIs which is a pretty strong property to enable scalability. The second issue is that an additional query is required to determine the count (or whether there's a next page). Issuing yet another query reduces the overall efficiency because it employs yet another server roundtrip.

We're convinced that using pagination in combination with reactive programming isn't the right thing to do and therefore we do not plan to add support for `Page`.

See also #565.

**Comment by kacperfronc** [comment]
@mp911de 
Alright, thanks for your response. I see your point.
As a user I'd definitely prefer if those two options were both available, as I find myself having to also sometimes expose regular paging APIs.

Thanks!

**Comment by kamalhm** [comment]
hi @kacperfronc , may I know what do you end up using for Paging in r2dbc?

**Comment by kacperfronc** [comment]
Hello @kamalhm.
I married two things, first is that it allows usage of Pageable as a parameter but returns flux, so I'm providing Pageable as a parameter, then I'm doing another count query and I'm joining this together creating a Paged response

**Comment by jiangtj** [comment]
```java
    public static <T> Mono<Page<T>> selectPage(R2dbcEntityTemplate template, Criteria criteria, Pageable pageable, Class<T> clz) {
        Mono<List<T>> list = template.select(clz)
                .matching(query(criteria).with(pageable))
                .all()
                .collectList();
        Mono<Long> count = template.select(clz)
                .matching(query(criteria))
                .count();
        return Mono.zip(list, count)
                .map(tuple -> new PageImpl<>(tuple.getT1(), pageable, tuple.getT2()));
    }
```

This is my helper, It may be helpful to you. @kamalhm
