### ISSUE TITLE
Should spring.io Spring Data documentation reflect the new Spring R2DBC `DatabaseClient` class?

### ISSUE THREAD

**Issue by elefeint** [spring-projects/spring-data-r2dbc#569]
https://spring.io/projects/spring-data-r2dbc still shows examples with the now-deprecated `DatabaseClient.execute()` approach. Should it mention that this is deprecated in favor of Spring R2DBC `DatabaseClient.sql()`, similar to the [migration guide](https://github.com/elefeint/spring-data-r2dbc/blob/f2507858b060ae9748d590612d255f7c510f486c/src/main/asciidoc/reference/r2dbc-upgrading.adoc#upgrading-from-11x-to-12x)?

**Comment by mp911de** [comment]
Yeah, it would make sense to update the sample to use `R2dbcEntityTemplate`.

**Comment by mp911de** [comment]
The documentation is updated now.
