### ISSUE TITLE
Add R2DBC-specific exception translation

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-r2dbc#57]
Right now, we're using Spring Framework's JDBC module to apply exception translation. Spring JDBC is heavily based on JDBC API and it makes little sense to pull JDBC API into R2DBC, especially when running in modularized Java 9+ environments.

We should provide our own exception translation mechanism that is built along the lines of Spring JDBC's `SQLErrorCodes` without using JDBC API.

**Comment by mp911de** [comment]
See [SPR-17618](https://jira.spring.io/browse/SPR-17618) (#22150).

**Comment by mp911de** [comment]
R2DBC decided to introduce an exception hierarchy that simplifies exception translation for client libraries. We're going to adopt subclass-based exception translation once that's in place.

See r2dbc/r2dbc-spi#47.

**Comment by schauder** [comment]
Done.
