### ISSUE TITLE
JSON converter no longer working

### ISSUE THREAD

**Issue by JoeBalduz** [spring-projects/spring-data-r2dbc#575]
A ReadingConverter that converts Json to a List of an object started failing when upgrading from 1.2.3 to 1.2.4 with the following exception:

```org.springframework.data.mapping.MappingException: Could not read property private final java.util.List com.example.JsonConverterNoLongerWorking.database.House.pets from column pets!```

I have created a small demo of the issue: https://github.com/JoeBalduz/r2dbc-json-converter-no-longer-working

The demo works fine on 1.2.3 but fails when spring-data-r2dbc is upgraded to 1.2.4. Is there something new that has to be done with the converters starting in 1.2.4 or is this a bug?

**Comment by mp911de** [comment]
Converters are generally required to retain the property multiplicity. It's not possible to convert an entire `List<…>` to `SomethingElse`, rather you`d convert `T` of `List<T>` to `List<SomethingElse>`. Previously, the issue worked by accident and not by intent.
