### ISSUE TITLE
Please provide example for using ReactiveEvaluationContextProvider

### ISSUE THREAD

**Issue by RobertHeim** [spring-projects/spring-data-r2dbc#576]
As I notice from the [blog entry ](https://spring.io/blog/2020/11/06/spring-data-2020-0-new-and-noteworthy-a-general-overview#reactive-spring-expression-language-ldquo-spel-rdquo-context-extensions) it should be possible to put stuff on the context for SpEL expressions, but I was not able to implement it.

```
@Configuration
class MyConfig {
  class X : EvaluationContextExtension{
    override fun getRootObject(): Any? {
      return "de"
    }
    override fun getExtensionId(): String {
      return "myExtension"
    }
  }

  class Y : ReactiveEvaluationContextExtension {
    override fun getExtensionId(): String {
      return "myExtension"
    }

    override fun getExtension(): Mono<out EvaluationContextExtension> {
      return  Mono.just(X())
    }
  }
  @Bean
  fun reactiveEvaluationContextExtension() : ReactiveEvaluationContextExtension? {
    return Y()
  }
}
```

When using it in a `@Query` like this:

```
interface TaskRepository : CoroutineCrudRepository<Task, Long> {
  @Query("SELECT * FROM task t WHERE t.locale = ?#{myExtension}")
  fun findWithLocale(): Flow<Task>
}
``` 
I see
```
EL1008E: Property or field 'myExtension' cannot be found on object of type 'java.lang.Object[]' - maybe not public or not valid?
```

In the end I would like to access the request's locale without putting it as a parameter to all controllers and services, e.g. 
```
@Query("... WHERE tl10n.locale = ?#{locale.language}"
```

**Comment by mp911de** [comment]
Take a look at https://github.com/spring-projects/spring-data-mongodb/blob/ad6d2c97b7b03e14fe3233509fd13588fc33db92/spring-data-mongodb/src/test/java/org/springframework/data/mongodb/repository/query/ReactiveStringBasedMongoQueryUnitTests.java#L306-L338.
