### ISSUE TITLE
Custom converter for constructor creation no longer applied

### ISSUE THREAD

**Issue by tomas-c** [spring-projects/spring-data-r2dbc#585]
I was previously using version 1.2.3 and just upgraded to 1.2.6 and noticed an issue when using a custom converter to map Postgres json columns to Kotlin data classes.

<details>
<summary>Here's my entity object:</summary>

```
@Table("test")
data class TestEntity(
    val data: TestData,    // JSON column in the database
    @Id
    val id: UUID = UUID.randomUUID()
)
```

</details>

<details>
<summary>Here's my custom converter:</summary>

```
@ReadingConverter
class R2dbcJsonToObjectConverter(
    private val objectMapper: ObjectMapper
) : GenericConverter, ConditionalConverter {

    override fun getConvertibleTypes(): Set<GenericConverter.ConvertiblePair>? {
        return setOf(GenericConverter.ConvertiblePair(Json::class.java, Object::class.java))
    }

    override fun convert(source: Any?, sourceType: TypeDescriptor, targetType: TypeDescriptor): Any? {
        if (Json::class.java.isAssignableFrom(sourceType.type)) {
            return objectMapper.readValue((source as Json).asString(), targetType.type)
        } else {
            return null;
        }
    }

    override fun matches(sourceType: TypeDescriptor, targetType: TypeDescriptor): Boolean {
        return Json::class.java.isAssignableFrom(sourceType.type)
    }
}
```
</details>

It looks like version 1.2.6 calls MappingR2dbcConverter.readFrom [here ](https://github.com/spring-projects/spring-data-r2dbc/blob/d9715297c39599aa2ad40ecaba8a9fadc54293f0/src/main/java/org/springframework/data/r2dbc/convert/MappingR2dbcConverter.java#L698) which considers TestEntity.data field as an entity [here](https://github.com/spring-projects/spring-data-r2dbc/blob/d9715297c39599aa2ad40ecaba8a9fadc54293f0/src/main/java/org/springframework/data/r2dbc/convert/MappingR2dbcConverter.java#L165) and tries to create an instance of TestData instead of using the conversion service. 

In version 1.2.3 the conversion was performed instead by calling MappingR2dbcConverter.resultSet.get [here](https://github.com/spring-projects/spring-data-r2dbc/blob/4365c7c142d6175aa9c2ee4900b0708dfaa621c0/src/main/java/org/springframework/data/r2dbc/convert/MappingR2dbcConverter.java#L727) and using the conversion service, without a call to MappingR2dbcConverter.readFrom.

So far I can think of two solutions:
- do not use complex types in entity objects - make TestEntity.data field of type Json and manually convert to the TestData object
- add TestData to a list of simple types such that MappingR2dbcConverter does not consider it an entity

Is there a better way?

Thanks for this library and all the work so far!

**Comment by mp911de** [comment]
Thanks for reporting the issue. With a refactoring, we unified code paths. The previous approach to obtain values for object instantiation used a slightly different approach than property population which surfaced this problem. We're going to fix that.

**Comment by Inego** [comment]
Unfortunately, the fix doesn't cover the case when the converted value is `null`.

Suppose I have the following type:

```kotlin
data class MyRow(
    val id: String,
    @Column("json_data")
    val jsonData: JsonNode?
)
```

...and a custom converter for r2dbc's `Json` to Jackson's `JsonNode`:

```kotlin
@ReadingConverter
object JsonConverter : Converter<Json?, JsonNode?> {
    override fun convert(source: Json?): JsonNode? {
        return source.parse()
    }
}

... elsewhere:

val objectMapper = ObjectMapper()

fun Json?.parse(): JsonNode? = if (this == null) null else objectMapper.readTree(asArray())

```

In case when the corresponding DB column value is null, the custom converter is ignored and, since this property is considered an "Entity", it tries to reflectively create an instance of an abstract class `JsonNode`, which fails.

Should I file a new issue for that, or ask a question on StackOverflow instead?
