### ISSUE TITLE
Fluent API to select DISTINCT column for r2dbcEntityTemplate.select() while using projection with select.as()

### ISSUE THREAD

**Issue by nsargar** [spring-projects/spring-data-r2dbc#586]
Hi,
Is there any support yet to select distinct columns while using template.select() flow?
Explored around but could not find anything and Flux.distinct() did not make sense.

**Comment by mp911de** [comment]
No, there is not. `DISTINCT` is a functionality commonly used with aggregations while the entity template is for entities.
