### ISSUE TITLE
Custom converters using ConverterBuilder not working in kotlin

### ISSUE THREAD

**Issue by hurahurat** [spring-projects/spring-data-r2dbc#588]
I'm using springboot version 2.4.5 with kotlin and try to use custom converters for mapping between tiny integer in mariadb to an enum.

If using @ReadingConverter with custom class I can confirm it's work but when I try to use ConverterBuilder it is not working in kotlin although it works well in java.

```
@Configuration
class CustomR2dbcConfig : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        return ConnectionFactories.get("...")
    }

    /*@Bean
    override fun getCustomConverters(): MutableList<Any> {
        return arrayListOf(StatusToByte(), ByteToStatus())
    }*/

    @Bean
    override fun r2dbcCustomConversions(): R2dbcCustomConversions {
        val converters: Set<GenericConverter> = ConverterBuilder
            .writing(Status::class.java, Byte::class.java) { userStatus -> userStatus.status }
            .andReading { status -> Status.from(status) }
            .converters

        return R2dbcCustomConversions(storeConversions, converters)
    }
}
```

```
enum class Status(var status: Byte) {
    ONLINE(1),
    OFFLINE(2);

    companion object {
        fun from(status: Byte) : Status = Status.values().first { it.status == status }
    }
}
```

```
@Table("user")
data class User(
    @Id
    var userId: Int = 0,
    var userStatus: Status = Status.ONLINE
)
```

When debugging I found that readingPairs is generated with right class name if using @ReadingConverter 

![제목 없음](https://user-images.githubusercontent.com/78128232/115658167-31fa8400-a373-11eb-9450-680b23147e14.png)

But it shows only "byte" in the case of using ConverterBuilder

![제목 없음2222](https://user-images.githubusercontent.com/78128232/115658622-1348bd00-a374-11eb-8180-e65d82f280aa.png)

**Comment by mp911de** [comment]
Make sure to use `Byte::class.javaObjectType`. Converters operate only on boxed types, not primitives.
