### ISSUE TITLE
MySQL dialect converts all `byte` properties to `boolean`

### ISSUE THREAD

**Issue by hurahurat** [spring-projects/spring-data-r2dbc#589]
I found that spring-data-r2dbc can read tinyint field as Byte type but I got 0 or 1 for tinyint fields in mysql/maridb database when inserting data.
It seems like byte field is converted to Boolean because of ByteToBooleanConverter in MySqlDialect class.

**Comment by mp911de** [comment]
`ByteToBooleanConverter` converts `byte` to `boolean` values when reading data from the database. 

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by hurahurat** [comment]
Thank you for your response. Please look at this minimal sample.
[demo.zip](https://github.com/spring-projects/spring-data-r2dbc/files/6376748/demo.zip)

These are scripts to create a sample database and table
```
CREATE DATABASE IF NOT EXISTS `test-db` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `test-db`;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `state` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

```

When hitting "/user/add" I got the response with a state value is 3 but the actual value saved in the database is 1.

**Comment by mp911de** [comment]
Thanks for the report and the example. The `ByteToBooleanConverter` in `MySQL` dialect, which is also used for MariaDB, converts all `byte` properties to `boolean`. The converter should actually be used only for reading.
