### ISSUE TITLE
Consider custom conversion in EntityRowMapper and MappingR2dbcConverter

### ISSUE THREAD

**Issue by asavov** [spring-projects/spring-data-r2dbc#59]
https://github.com/spring-projects/spring-data-r2dbc/blob/2dfb1ff20e29cb124af623370fe1f5e45f812668/src/main/java/org/springframework/data/r2dbc/function/convert/EntityRowMapper.java#L72

Reading of Map entity property is intentionally blocked by above line. 

How about allowing it and then delegate to the client's custom DBStoredValue-To-Map converter. Similar to:

```
    static class Config extends AbstractR2dbcConfiguration {

        @Override @Bean public R2dbcCustomConversions r2dbcCustomConversions() {
            ...
            return new R2dbcCustomConversions(
                    storeConversions,
                    Arrays.asList(new JsonStringToMapConverter()));
        }

        class JsonStringToMapConverter implements Converter<String, Map<String, Object>> {
             ...
        }

```

**Comment by asavov** [comment]
Seems kind of related to #39 
Still `if (property.isMap()) throw new UnsupportedOperationException();` needs special attention which is orthogonal to #39

**Comment by mp911de** [comment]
The mentioned guard above will be removed with the implementation of #39.

**Comment by mp911de** [comment]
That's in place now.
