### ISSUE TITLE
#{#entityName} or similar alternative to resolve the Table/Entity name on @Query 

### ISSUE THREAD

**Issue by creativelikeadog** [spring-projects/spring-data-r2dbc#590]
Not sure if this is an issue, probably a feature request.

Currently is not possible to use generic abstractions for the repositories like in `spring-data-jpa`.
For example:
```kotlin
@NoRepositoryBean
interface SoftDeleteRepository<MODEL : Deletable<ID>, ID : Serializable> : R2dbcRepository<MODEL, ID> {

    @Modifying
    @Query("UPDATE #{#entityName} e SET e.deletedAt = now() WHERE e.id = :id")
    override fun deleteById(id: ID): Mono<Void>
}
```

Of course, this fails due to `#{#entityName}` not being resolved, so I'm wondering if there is a way to get that information.

**Comment by mp911de** [comment]
Results of SpEL expressions are bound as parameters to the SQL statement. Table names cannot be bound as parameters and we have no means to distinguish between bindable and non-bindable SpEL expressions. Therefore we do not plan to add such functionality.
