### ISSUE TITLE
Entity callbacks not fired for String-based queries or named query methods

### ISSUE THREAD

**Issue by JoseLion** [spring-projects/spring-data-r2dbc#591]
Hi,

I'm trying to use entity callbacks like `AfterConvertCallback` or `BeforeConvertCallback` in my project, which work great for built-in query methods like `.findAll()` or `findById(ID id)`. However, it seems they are not being fired for String-based queries or named query methods.

I might be missing something, but I tracked the issue a little bit, and it seems the entity callbacks are only called from the `R2dbcEntityTemplate` methods. As far as I could tell, string-based queries and named query methods don't go through these methods (like [select(Query query, Class<T> entityClass)](https://github.com/spring-projects/spring-data-r2dbc/blob/ab1545fef7fbccb4f8419ee55e4cf21130586ce5/src/main/java/org/springframework/data/r2dbc/core/R2dbcEntityTemplate.java#L383) or [insert(T entity)](https://github.com/spring-projects/spring-data-r2dbc/blob/ab1545fef7fbccb4f8419ee55e4cf21130586ce5/src/main/java/org/springframework/data/r2dbc/core/R2dbcEntityTemplate.java#L532)).

I'd be more than happy to help if someone could point me in the right direction. It seems that this could need some design discussion to probably move the callbacks to a higher level, or maybe just call them from the places where other queries run too. In any case, I'm always happy to contribute if possible. 🙂 

### Versions
- **Spring Boot:** v2.4.5
- **JVM:** Java(TM) SE Runtime Environment (build 15.0.2+7-27)

### Code sample
```java
@Configuration
public class EmployeeCallbacks {

  @Bean
  public AfterConvertCallback<Employee> afterConvert() {
    return (employee, table) -> {
      // Do something with the entity
    };
  }
}
```

```java
public interface EmployeeRepository extends ReactiveCrudRepository<Employee, Long> {

  @Query("SELECT * FROM employee WHERE name=:name")
  Mono<Employee> findFirstByName(String name); // This never triggers the callback ❌

  Mono<Employee> findFirstByLastname(String lastname); // This never triggers the callback ❌

  // Mono<Employee> findById(Long id); // This is built-in, this always triggers the callback ✅
}
```

As always, thanks for the great work on this project.

Cheers!

**Comment by mp911de** [comment]
The difference in behavior comes from the differences in running the SQL statement. `SimpleR2dbcRepository` uses `R2dbcEntityOperations` which makes use of entity callbacks while query methods directly use `DatabaseClient`. We need to migrate query method execution into `R2dbcEntityOperations` so we can reuse entity callbacks.

**Comment by JoseLion** [comment]
Awesome, thank you @mp911de! Entity callbacks are extremely helpful. I use them to eagerly populate relational fields (one to one, one to many, etc.), which need to be transient in the model for the time being.

Just for me to be on the lookout, it's possible to know in which version of Spring Boot will this be available?

Thank again!!

**Comment by mp911de** [comment]
The next Boot generation that will pick up these changes is going to be Spring Boot 2.6. There's new API and quite a bit of rewrite required to make this work and that bears a certain risk.

**Comment by JoseLion** [comment]
Got it, totally understandable too! I'll be on the watch for v2.6 to give it a try. Thanks again @mp911de 🙂
