### ISSUE TITLE
Unable to create repository methods

### ISSUE THREAD

**Issue by jnfeinstein** [spring-projects/spring-data-r2dbc#595]
I first noticed this while attempting to create a `ReactiveCrudRepository<Foo, UUID>` with method `Flux<Foo> findAll(Pageable pageable)`.  Bean creation fails with `PropertyReferenceException: No property findAll found for type Foo!`.

I then attempted to create a `ReactiveQueryByExampleExecutor<Foo>`, which resulted in `PropertyReferenceException: No property findAll found for type Foo!` as well, triggered by creation of `Flux<Foo> findAll(Predicate predicate)`.

There are many references in documentation to custom methods of signature `findAll(...)`, so I assume this should work without naming as `findAllBy(...)`, (especially considering vended code holds this same signature).

Here is the repro:
```java
@SpringBootApplication
@EnableR2dbcRepositories
public class DemoApplication {
	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}

class Foo {
	@Id UUID uuid;
}

interface FooRepository extends ReactiveCrudRepository<Foo, UUID>, ReactiveQuerydslPredicateExecutor<Foo> {

}
```
Triggers:
```java
Caused by: org.springframework.data.mapping.PropertyReferenceException: No property findAll found for type Foo!
```

**Comment by jnfeinstein** [comment]
The docs _do_ call this pattern out specifically.  It would be great if this caveat could be documented.
```java
public interface PagingAndSortingRepository<T, ID> extends CrudRepository<T, ID> {

  Iterable<T> findAll(Sort sort);

  Page<T> findAll(Pageable pageable);
}
```

**Comment by mp911de** [comment]
The documentation is split into two parts: The general Spring Data Repositories (Commons) part that explains how repositories work in general and the store-specific part that starts at https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#reference. Each part in the reference section refers to actually supported functionality.

**Comment by cforce** [comment]
Seem like  there is a PR for ReactiveQuerydslPredicateExecutor at QueryDSL 
https://github.com/querydsl/querydsl/pull/2610

You can vote here https://github.com/querydsl/querydsl/issues/2468#issuecomment-793542421
