### ISSUE TITLE
the field @CreatedDate and @CreatedBy save null when I update the entity by repository save

### ISSUE THREAD

**Issue by funkikylekyle** [spring-projects/spring-data-r2dbc#600]
I am using mysql db and Webflux with spring boot 2.4.5

my testing program is the following structure: 

```
   @Id
    @Column(TABLE_COLUMN_ID)
    private Long id;

    @Version
    @Column(TABLE_COLUMN_VERSION)
    private Long version;


    @PositiveOrZero
    @CreatedBy
    @Column(TABLE_COLUMN_CREATED_BY)
    private Long createdBy;


    @PositiveOrZero
    @LastModifiedBy
    @Column(TABLE_COLUMN_LAST_MODIFIED_BY)
    private Long lastModifiedBy;

    @Null
    @CreatedDate
    @Column(TABLE_COLUMN_CREATED_DATE)
    private LocalDateTime createdDate;

    @Null
    @LastModifiedDate
    @Column(TABLE_COLUMN_LAST_MODIFIED_DATE)
    private LocalDateTime lastModifiedDate;

    @Hidden
    @JsonIgnore
    @Override
    public boolean isNew() {

        return Objects.isNull(id);

    }

...
    @Bean
    ReactiveAuditorAware<Long> auditorAware() {
        return () -> Mono.just(2L);
    }
...

    public Mono<Test> saveTest(Test test) {

        return testRepository.save(test);

    }

```

1.1 first submit data

{
  "accountStatus": "A"
}

1.1 first return with data(correct data):
{
  "accountStatus": "A",
  "id": 1,
  "version": 0,
  "createdBy": 2,
  "lastModifiedBy": 2,
  "createdDate": "2021-05-16T17:58:55.713564",
  "lastModifiedDate": "2021-05-16T17:58:55.713564"
}

2.1 second submit data:
{
  "accountStatus": "DA",
  "id": 1,
  "version": 0
}

2.2 then return data :

{
  "accountStatus": "DA",
  "id": 1,
  "version": 1,
  "createdBy": null,
  "lastModifiedBy": 2,
  "createdDate": null,
  "lastModifiedDate": "2021-05-16T17:59:55.713564"
}

but 
I expect the result is 

{
  "accountStatus": "DA",
  "id": 1,
  "version": 1,
  "createdBy": 2,
  "lastModifiedBy": 2,
  "createdDate": "2021-05-16T17:58:55.713564",
  "lastModifiedDate": "2021-05-16T17:59:55.713564"
}

am I doing something wrong?

**Comment by mp911de** [comment]
The code behaves as designed. In your first example, you do not provide an `id` value therefore your code, checking whether `id` is `null` reports that the object is new. In the second request, you pass in an `id` and so the entity is considered not new hence `createDate` isn't set by the auditing framework.

This type of question is better suited for StackOverflow therefore we're closing this ticket.

**Comment by gabrilogos1985** [comment]
However it does not save null values for createdBy and createdDate columns, they must not be updatable.

R2DBC does not support it with updatable=false
