### ISSUE TITLE
R2dbcEntityTemplate selectOne limit issue

### ISSUE THREAD

**Issue by pavel-zhoidz** [spring-projects/spring-data-r2dbc#601]
Trying to select one record based on order and limit(1) results in org.springframework.dao.IncorrectResultSizeDataAccessException

`template.selectOne(
                query(
                where(InfoLiveFightsResult.Fields.competitionId).is(competitionId)
                    .and(InfoLiveFightsResult.Fields.weightCategoryCode).is(category)
                    .and(InfoLiveFightsResult.Fields.fightIndex).is(fightIndex))
                    .sort(Sort.by(Order.desc(InfoLiveFightsResult.Fields.id)))
                    .limit(1), InfoLiveFightsResult.class)`

Query details

`org.springframework.dao.IncorrectResultSizeDataAccessException: Query [SELECT info_live_fight.* FROM info_live_fight WHERE info_live_fight.competition_id = $1 AND info_live_fight.weight_category_code = $2 AND info_live_fight.fight_index = $3 ORDER BY id DESC LIMIT 2] returned non unique result.`

Actually, limit does not affect resulting SQL at all, and it seems strange.

I saw in org.springframework.data.r2dbc.core.R2dbcEntityTemplate

`	@Override
	public <T> Mono<T> selectOne(Query query, Class<T> entityClass) throws DataAccessException {
		return doSelect(query.limit(2), entityClass, getTableName(entityClass), entityClass, RowsFetchSpec::one);
	}`

limit hardcoded. What is the reason for that? And why limit method does not affect resulting query?

As workaround, definitely, the following could be used

` template.select(
                query(
                where(InfoLiveFightsResult.Fields.competitionId).is(competitionId)
                    .and(InfoLiveFightsResult.Fields.weightCategoryCode).is(category)
                    .and(InfoLiveFightsResult.Fields.fightIndex).is(fightIndex))
                    .sort(Sort.by(Order.desc(InfoLiveFightsResult.Fields.id)))
                    .limit(1), InfoLiveFightsResult.class)
                .single()`

Resulting query

`Executing SQL statement [SELECT info_live_fight.* FROM info_live_fight WHERE info_live_fight.competition_id = $1 AND info_live_fight.weight_category_code = $2 AND info_live_fight.fight_index = $3 ORDER BY id DESC LIMIT 1]`

Spring Boot version: 2.4.5
org.springframework.boot:spring-boot-starter-data-r2dbc
spring-data-r2dbc version: '1.2.8'

**Comment by mp911de** [comment]
`selectOne` is specifically designed to ensure zero or one semantics so calling code can rely on these guarantees. We use `LIMIT 2` to catch if the query results in more than one rows to propagate the exception.

You can either use the mentioned workaround or use the fluent API:

```java
    template.select(InfoLiveFightsResult.class)
      .matching(query(…))
      .first()
```

**Comment by pavel-zhoidz** [comment]
Thank for reply. Now it is clear.
