### ISSUE TITLE
Dynamic projection skipped if projection type not already registered with MappingContext

### ISSUE THREAD

**Issue by thorntonrp** [spring-projects/spring-data-r2dbc#607]
Dynamic projections don't work as documented. They only work with the @Query annotation in which case they aren't dynamic at all.

I'm trying to use dynamic projections as documented here:
https://docs.spring.io/spring-data/data-r2dbc/docs/1.3.x/reference/html/#projection.dynamic

Projections appear only to work when used in conjunction with the @Query annotation, but there is no mention in the documentation that the @Query annotation is required to use projections. Moreover, when passing in a project class for use in dynamic projections, the resulting projection is not dynamic.

**Comment by mp911de** [comment]
> Dynamic projections don't work as documented

Care to elaborate? How exactly do they work for you? 

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by thorntonrp** [comment]
[demo-r2dbc.zip](https://github.com/spring-projects/spring-data-r2dbc/files/6688701/demo-r2dbc.zip)

This demo illustrates the problem. Additional investigation provided more information about the issue. This is my repository:

```java
public interface AssetRepository extends R2dbcRepository<Asset, Long> {
    <T> Flux<T> findBy(Class<T> type);
}
```

As written, some of the tests don't pass due to the following exception:
```
java.lang.AssertionError: expectation failed (failed running expectation on signal [onNext(Asset(id=null, version=null, path=assets/java-stack-logo-24.png, size=null, lastModified=null, contentType=image/png, checksum=null))] with [java.lang.ClassCastException]:
class com.example.demor2dbc.model.Asset cannot be cast to class com.example.demor2dbc.model.PathAndContentTypeOnly (com.example.demor2dbc.model.Asset and com.example.demor2dbc.model.PathAndContentTypeOnly are in unnamed module of loader 'app'))
```

The cause of the error is that the class PathAndContentTypeOnly cannot be cast to Asset.

WORKAROUND
After additional investigation, I discovered that if I add an additional method to the interface that specifically returns the projection `PathAndContentType`, the test for the dynamic projection will pass for that projection type. Likewise, if I add an additional method for the projection `PathAndChecksum`, the test for the dynamic projection will also pass for that projection type. For example:

```java
public interface AssetRepository extends R2dbcRepository<Asset, Long> {
    <T> Flux<T> findBy(Class<T> type);
    Flux<PathAndChecksumOnly> findAllBy();
    Flux<PathAndContentTypeOnly> findAssetBy();
}
```
The two additional operations allow the dynamic `findBy(Class<T>)` to work for both projection types. But this is not ideal because I never actually intend to use those two additional operations. Is there a better way to somehow register the two projection types so that they can be handled properly?

**Comment by thorntonrp** [comment]
Here's another workaround. Also not pretty, but more palatable than the first: override the default `R2dbcMappingContext` to ensure the persistent types get added to the mapping context.

```
    @Bean
    public static R2dbcMappingContext r2dbcMappingContext(ObjectProvider<NamingStrategy> namingStrategy,
                                                   R2dbcCustomConversions r2dbcCustomConversions) {
        R2dbcMappingContext relationalMappingContext = new R2dbcMappingContext(
            namingStrategy.getIfAvailable(() -> NamingStrategy.INSTANCE));
        relationalMappingContext.setSimpleTypeHolder(r2dbcCustomConversions.getSimpleTypeHolder());

        // Make sure our DTO projections get included in the mapping context.
        // Calling `getPersistentEntity` appears to be the only way to cause classes to be added
        // to the mapping context that have not been specifically defined as return values on the
        // repository interface methods
        relationalMappingContext.getPersistentEntity(PathAndChecksumOnly.class);
        relationalMappingContext.getPersistentEntity(PathAndContentTypeOnly.class);

        return relationalMappingContext;
    }

```

**Comment by thorntonrp** [comment]
It would be helpful if 1) the "Dynamic Projections" section of the reference documentation would indicate that projection types must be registered with the mapping context, and 2) if there was a more intuitive way to add projection types to the mapping context than overriding the bean.

**Comment by mp911de** [comment]
Thanks a lot for the reproducer, that one helped to figure out that the issue is actually a bug.

**Comment by kwidjaja1312** [comment]
Hi @mp911de, i just noticed about this change and now my query is failed:

```
public interface MyRepository extends ReactiveCrudRepository<Node, String> {
  @Query("SELECT id FROM Node WHERE ...<truncated>")
  Mono<String> findById(String libraryId, ..<truncated>);
```

 -> whereas the type of `id` is `java.lang.String`.
