### ISSUE TITLE
New DatabaseClient and R2dbcRepository are not consitent when retrieving `TIMESTAMP` to Instant

### ISSUE THREAD

**Issue by xp-vit** [spring-projects/spring-data-r2dbc#608]
**Precondition**
1. PostgreSQL DB  with a table having with `TIMESTAMP` field
2. `TIMESTAMP` field mapped to `Instant`

**Issue**
When mapping `TIMESTAMP` to Instant using `org.springframework.r2dbc.core.DatabaseClient` the retrieved time get's offset, while when retrieving with R2dbcRepository there is no offset applied.

I have created repo to show this issue:
https://github.com/xp-vit/r2dbc-timestamps

Tests located in `TestEntityServiceTest.java` always pass only when running in UTC TZ, but when running in any other TZ then assertions in test using `DatabaseClient` fail due to TZ offset being applied.

**BTW**

Old, (currently deprecated) `org.springframework.data.r2dbc.core.DatabaseClient` worked correctly and haven't applied any offsets.

**Comment by mp911de** [comment]
`TIMESTAMP` in Postgres represents a timezone-less date and time, similar to `LocalDateTime` while `TIMESTAMP WITH TIMEZONE`'s closest Java representation is `OffsetDateTime`. Storing `Instant` into `TIMESTAMP` truncates the offset part hence conversion into an `Instant` from the available data is always subject to timezone adjustments.

The code in your example requests specifically `Instant` from the Postgres driver which lies outside of Spring Data. 

If you want to adjust how [R2DBC Postgres](https://github.com/pgjdbc/r2dbc-postgresql/) [creates an `Instant` from `LocalDateTime`](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/codec/InstantCodec.java#L41-L56), I suggest filing a ticket in the driver project.
