### ISSUE TITLE
Keyword as table name returns syntax error exception

### ISSUE THREAD

**Issue by kressi** [spring-projects/spring-data-r2dbc#609]
Using keywords as table names breaks SQL.

_schema.sql_
```sql
CREATE TABLE "GROUP"(ID INT);
INSERT INTO "GROUP"(ID) VALUES (1L);
```

_Entity.java_
```java
import lombok.Value;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

@Value
@Table("GROUP")
public class GroupEntity {
    @Id
    @Column("ID")
    Integer id;
}
```

When reading from this table with an `R2dbcRepository<GroupEntity, Integer>`, a SQL error is returned.

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SELECT GROUP.[*]* FROM GROUP WHERE GROUP.ID = $1 LIMIT 2"; expected "BY"; SQL statement:
SELECT GROUP.* FROM GROUP WHERE GROUP.ID = $1 LIMIT 2 [42001-200]
```

When table name is quoted in the table annotation, everything works perfectly fine.
_QuotedEntity_
```java
@Value
@Table("\"GROUP\"")
public class GroupEntity {
    @Id
    @Column("ID")
    Integer id;
}
```

Adding quotes manually to table name annotations does not feel right. Is this intended behavior or am I missing some configuration?

**Comment by mp911de** [comment]
You can enable force quoting with `R2dbcMappingContext.setForceQuote(true)` so you don't need to add quotes yourself to table- and column names.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kressi** [comment]
Thank you @mp911de! That solves what I was looking for.
