### ISSUE TITLE
Add ability to store UUID as binary(16)

### ISSUE THREAD

**Issue by Paramood** [spring-projects/spring-data-r2dbc#614]
That would be useful to have `UUID` to `binary(16)` converter like with Spring Data + Hibernate

**Comment by mp911de** [comment]
You can register your own `Converter` with the desired representation of `UUID` via `R2dbcCustomConversions`, see https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#mapping.explicit.converters.

**Comment by Paramood** [comment]
Thank you for the response. I know that I can register an own converter but such a generic thing can be implemented directly in Spring Data if possible.

**Comment by mp911de** [comment]
While creating a byte array from `UUID` is rather trivial, the actual question that arises from here is how and where to apply such conversion. Spring Data has generally no means to express the property target type for a specific annotation, rather depending on the property type and converters that are registered, a Spring Data module decides the data type that is used with a driver.
