### ISSUE TITLE
@Query Documentation Request

### ISSUE THREAD

**Issue by patientplatypus6** [spring-projects/spring-data-r2dbc#618]
This isn't a bug per se, but I haven't been able to find a simple implementation of how to use @Query in order to insert a schema without using the `save` command. This should seemingly be simple, however I haven't been able to determine the return type of the insert command (having tried several methods). Here is what I have so far
(https://stackoverflow.com/questions/68256734/r2dbc-return-type-query). Thanks for any help you could provide. The save function does work, but I would like to have the option of specifying my schema myself if there are any edge cases in the SQL code in the future. Thanks again!

**Comment by mp911de** [comment]
Check out the documentation on `@Modifying` queries: https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#r2dbc.repositories.modifying

**Comment by patientplatypus6** [comment]
Thanks so much Mark that solved the issue. I've updated the stackoverflow question. Here is the implementation for anyone else that is searching the internet on how to write raw sql using kotlin, r2dbc, and spring boot - 

From the handler or service

```
  suspend fun addBook(book: Books):List<Books>{
    println("addBooks")
    // bookRepo.save(book);
    bookRepo.saveabook(
      book.title, book.subtitle, book.publisher, 
      book.currentcopyright, book.bookedition, 
      book.uniqueid, book.authorbio, book.synopsis, book.isbn
    )
    var bookList:List<Books> = findBooks()
    return bookList;
  }
```
Inside the repository 

```
import org.springframework.data.r2dbc.repository.Query  
import org.springframework.data.r2dbc.repository.Modifying

@Repository
interface BookRepository : CoroutineCrudRepository<Books, Long> {
    

    // The result of a modifying query can be:
    // Void (or Kotlin Unit) to discard update count and await completion.
    // Integer or another numeric type emitting the affected rows count.
    // Boolean to emit whether at least one row was updated.

    @Modifying
    @Query(
    """
      insert into books (title, subtitle, publisher, currentcopyright, bookedition, uniqueid, authorbio, synopsis, isbn) values (:title, :subtitle, :publisher, :currentcopyright, :bookedition, :uniqueid, :authorbio, :synopsis, :isbn)
    """)
    suspend fun saveabook(title:String, subtitle:String, publisher:String, currentcopyright:String, bookedition:String, uniqueid:String, authorbio:String, synopsis:String, isbn:String):Void

    @Query("""
      select * from books
    """)
    suspend fun findBooks():List<Books>
}
```
