### ISSUE TITLE
spring data r2dbc use @Transaction have a cache

### ISSUE THREAD

**Issue by hero-zhanghao** [spring-projects/spring-data-r2dbc#626]
When the spring boot data r2dbc, I use the Transaction annotations to open Transaction, code when they encounter OptimisticLockingFailureException to query the database and update again.

However, I found that the data was the same every time, even if the database had changed, and this problem disappeared after the Transaction annotation was removed

The database I use is MySQL.

spring boot version : 2.5.0

Database driven：dev.miku:r2dbc-mysql.0.8.2.RELEASE

Is there anything I can do to solve this problem?

Any answer is welcome

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please provide a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by hero-zhanghao** [comment]
Look at this simple example to replicate what I'm saying @mp911de 
[r2dbc_example.zip](https://github.com/spring-projects/spring-data-r2dbc/files/6861933/r2dbc_example.zip)

**Comment by hero-zhanghao** [comment]
@mp911de Look at this simple example to replicate what I'm saying,Thanks

[r2dbc_example.zip](https://github.com/spring-projects/spring-data-r2dbc/files/6861945/r2dbc_example.zip)

**Comment by mp911de** [comment]
Thanks for the code. It makes clear why you see that behavior:

```
    @Transactional
    public Mono<Boolean> update(Integer id, String name) {
        return testRepository.findById(id)
                .doOnNext(System.out::println)
                .flatMap(test -> {
                    //Debug breakpoints here,And the value of the database version field is changed. Simulate the situation where intermediate data is modified
                    test.setName(name);
                    return testRepository.save(test);
                })
                .retryWhen(Retry.fixedDelay(3, Duration.ofMillis(100))
                        .filter(e -> e instanceof OptimisticLockingFailureException)
                )
                .map(ignore -> true);
    }
```

`retryWhen` happens inside the transaction hence the underlying resource applies isolation to the data being queried. Please move any retries to outside of the transaction.

**Comment by hero-zhanghao** [comment]
But one of the things that we do with optimistic locking is we want to redo some of the operations, like after a certain logic, subtract the inventory of the goods,If there is an optimistic locking error, get the latest cargo quantity again, and then subtract the quantity,Instead of retrying the previous logic, because the other operations do not need or cannot be done again.

**Comment by hero-zhanghao** [comment]
In your interpretation, this is the behavior of the transaction. If you can add a parameter when the transaction is opened, you can control whether the query for the same data from the database is the latest

**Comment by kwonglau** [comment]
I am seeing the same issue. I don't have the @Transactional annotation on the method and I move the retry into a new method. same thing happen. Is that an example somewhere for how to deal with OptimisticLockingException with retry for R2DBC?
