### ISSUE TITLE
rowsUpdated() returns wrong value with insert on duplicate key update in mariadb

### ISSUE THREAD

**Issue by hurahurat** [spring-projects/spring-data-r2dbc#627]
```
template.getDatabaseClient()
	.sql("INSERT INTO test_table(history_id, content)"
		+ "VALUES (1, \"aaaaaaaaa\")"
		+ "ON DUPLICATE KEY "
		+ "UPDATE content = content")
       .fetch()
       .rowsUpdated();
```

When trying to get the number of affected rows from 'insert on duplicate key' I could get 1 or 2 as returns. 
But if nothing is inserted/updated, rowsUpdated always return 1 instead of 0.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by hurahurat** [comment]
@mp911de Thank you for your response. I could reproduce the same using pure r2dbc api.

**Comment by mp911de** [comment]
Thanks for the feedback. Then please file a bug report against the MariaDB driver.
