### ISSUE TITLE
Improve `R2dbcCustomConversions` creation when using a dialect to ensure registration of driver-simple types

### ISSUE THREAD

**Issue by anuger** [spring-projects/spring-data-r2dbc#628]
springboot version: 2.4.7
spring-data-r2dbc version: 1.2.9

**entity**:
``` java
public class MessageBody {
    private String msg:
}
public class Message {
    private Integer id;
    private MessageBody body;
}
```
**Repository**
``` java
public interface MessageRepository extends R2dbcRepository<Message, Integer> {
}
```
when i call `MessageRepository.save()`, i get the **exception**:
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.dao.InvalidDataAccessApiUsageException: Nested entities are not supported
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: Nested entities are not supported
```
If change `Message.body` to `String`:
``` java
public class Message {
    private Integer id;
    private String body;
}
```
get **exception**:
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [INSERT INTO message (body) VALUES ($1)]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42804] column "body" is of type json but expression is of type character varying
Caused by: org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [INSERT INTO message (body) VALUES ($1)]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42804] column "body" is of type json but expression is of type character varying
```
after add `@WritingConverter`:
```java
public class MessageBodyWriteConverter implements Converter<MessageBody, Json> {
    @Override
    public Json convert(MessageBody messageBody) {
        return Json.of(new ObjectMapper().writeValueAsString(messageBody));
    }
}
```
get **exception**:
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.dao.DataIntegrityViolationException: executeMany; SQL [INSERT INTO message (body) VALUES ($1)]; null value in column "body" violates not-null constraint; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: [23502] null value in column "body" violates not-null constraint
Caused by: org.springframework.dao.DataIntegrityViolationException: executeMany; SQL [INSERT INTO message (body) VALUES ($1)]; null value in column "body" violates not-null constraint; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: [23502] null value in column "body" violates not-null constraint

```

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

Right now it seems that `MessageBody` is `null`, however, the entity and converter are correct.

**Comment by anuger** [comment]
@mp911de 　it's not null
![image](https://user-images.githubusercontent.com/24793128/126292845-d160178d-4d26-4135-b7b6-c226bb6837bc.png)

**Comment by anuger** [comment]
this is my config:
``` java
@Configuration
public class R2dbcConfig {

    @Bean
    public R2dbcCustomConversions customConversions() {
        List<Converter<?, ?>> converters = new ArrayList<>();
        converters.add(new MessageBodyReadConverter());
        converters.add(new MessageBodyWriteConverter());
        return new R2dbcCustomConversions(converters);
    }
}
```

**Comment by mp911de** [comment]
Remote debugging isn't the most efficient way to track down the cause. While you're already at the debugger, you can trace down the actual write value that is being stored in `OutboundRow` and the resulting binding in `ExtendedQueryPostgresqlStatement`.

**Comment by anuger** [comment]
@mp911de Null is generated here
![image](https://user-images.githubusercontent.com/24793128/126314529-966c37e3-e636-4ec8-8b6a-314e9d9bfb59.png)

**Comment by mp911de** [comment]
Does the same happen if you upgrade to 1.3?

**Comment by anuger** [comment]
@mp911de I upgraded to 1.3.2, have the same exception

**Comment by mp911de** [comment]
Without a reproducer, I'm not able to reproduce the issue which makes it impossible to diagnose what causes the issue.

**Comment by anuger** [comment]
I created a project to demonstrate this problem
[MessageServiceTest](https://github.com/anuger/r2dbc_test/blob/main/src/test/java/demo/MessageServiceTest.java)

**Comment by mp911de** [comment]
Thanks a lot. The issue happens due to `Json` not being considered as simple type. I didn't immediately spot that the dialect is missing when constructing `R2dbcCustomConversions`. `R2dbcCustomConversions` should be created as follows:

```java

List<Object> converters = new ArrayList(PostgresDialect.INSTANCE.getConverters());
converters.addAll(R2dbcCustomConversions.STORE_CONVERTERS);

return new R2dbcCustomConversions(CustomConversions.StoreConversions
		.of(PostgresDialect.INSTANCE
				.getSimpleTypeHolder(), converters), Arrays
		.asList(new MessageBodyReadConverter(), new MessageBodyWriteConverter()));
```

That isn't obvious from the constructor's signature. It makes sense to introduce a constructor taking the `Dialect` and the collection of converters and to deprecate the constructor that takes only a collection of converters.

Depending on the driver/dialect, we can register additional simple types that allow database-specific functionality.
