### ISSUE TITLE
Add support for Postgresql ARRAY constructor syntax

### ISSUE THREAD

**Issue by eldkqmfhf123** [spring-projects/spring-data-r2dbc#632]
In the postgresql official docs it is mentioned below:

The ARRAY constructor syntax can also be used:
```
INSERT INTO sal_emp
    VALUES ('Bill',
    ARRAY[10000, 10000, 10000, 10000],
    ARRAY[['meeting', 'lunch'], ['training', 'presentation']]);

INSERT INTO sal_emp
    VALUES ('Carol',
    ARRAY[20000, 25000, 25000, 25000],
    ARRAY[['breakfast', 'consulting'], ['meeting', `'lunch']]);
```
(ref. https://www.postgresql.org/docs/current/arrays.html)

The problem occurs when executing a query using namedParameter.

and here is example query
```
CREATE TABLE "test" (
     "id" SERIAL PRIMARY KEY,
     "content" VARCHAR(256)[]
);

INSERT INTO "test" ("content")
VALUES (array[':1', ':2'])
```
parseSqlStatement method in NamedParameterUtils.java is not processing `]` as a ParameterSeparator, which is part of the Array syntax, so now  `2]` is considered part of namedParameter.
and it will raise BadSqlGrammerException.

**Comment by mp911de** [comment]
You actually should be good with:

```
INSERT INTO "test" ("content")
VALUES (array[ :foo ])
```

Spring's Named Parameter Expansion is a generic utility that is SQL-dialect agnostic. It replaces singular parameters with a bind marker and collections with the appropriate number of bind markers.

The following code should do what you're looking for:

```java
databaseClient.sql("… VALUES (array[ :foo ])").bind("foo", Arrays.asList("1", "2", "3"))
```

as it expands into `… VALUES (array[ $1, $2, $3 ])`

**Comment by eldkqmfhf123** [comment]
Thank you for support. 
I used JOOQ as mapper, and it created query like that.
I resolved it by writing raw query.
