### ISSUE TITLE
org.springframework.r2dbc.core.ColumnMapRowMapper.apply(Row, RowMetadata)

### ISSUE THREAD

**Issue by Stokoloshe** [spring-projects/spring-data-r2dbc#635]
this method will cause data map error
if select column a\b\ c , the value will be ok,  if select column b\a\c, the value will not be ok, the value of b will be a's value

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
