### ISSUE TITLE
Bind collection of tuples

### ISSUE THREAD

**Issue by junglie85** [spring-projects/spring-data-r2dbc#642]
The following query executes in Oracle DB:

```sql
SELECT *
FROM orders orders
LEFT JOIN events events ON orders.order_id = events.event_id
WHERE (orders.order_id, events.event_id) in (('1234', 'abcd'), ('5678', 'efgh'))
```

I want to execute this query, but it returns an `IllegalArgumentException: Unsupported java type`.

```java
List<OrderAndEventId> orderAndEventIds = List.of(OrderAndEventId("1234", "abcd"), ...);

client.sql(...)
    .bind("order_and_event_ids", orderAndEventIds)
    .map(...)
    .all();
```

Is this functionality supported? If so, what's the API for using it?

**Comment by mp911de** [comment]
Tuples can be bound for `IN` conditions by providing a `Collection<Object[]>`. Having a pojo type such as `OrderAndEventId ` doesn't allow for determining the parameter order.

**Comment by junglie85** [comment]
Thanks :+1:
