### ISSUE TITLE
`SELECT FOR UPDATE` - Do we have support for this? 

### ISSUE THREAD

**Issue by sougat818-streamotion** [spring-projects/spring-data-r2dbc#643]
Hi everyone, 

Been using this for a couple of months and been great. We have a requirement to run queries like `SELECT FOR UPDATE` . I can't find any way to do this via the r2dbc library. Can someone please confirm this or point me in the right direction. 🙏🏽

Appreciate any help! Thanks

**Comment by mp911de** [comment]
You can provide your own SQL if you need to run queries that aren't supported yet by our SQL builder. Note that there's also https://github.com/spring-projects/spring-data-jdbc/issues/1041 that duplicates this one.
