### ISSUE TITLE
Add Support for UUID Id types.

### ISSUE THREAD

**Issue by rieger-jared** [spring-projects/spring-data-r2dbc#662]
Hi all, 
I'm currently running these dependencies with Postgres
```text
    implementation("org.springframework.boot:spring-boot-starter-data-r2dbc:2.4.2")
    implementation("io.r2dbc:r2dbc-postgresql:0.8.10.RELEASE")
 ```
 Using a simple repository like so
 ```kotlin
 interface PersonRepository : R2dbcRepository<Person, UUID>
```

```kotlin
data class Person(@Id val id: UUID, val name: String)
```

Will cause an issue when attempting to save a new Person 
```kotlin
repository.save(Person(name = "Jeff")
``` 
an error will be thrown stating 
```text
org.springframework.dao.TransientDataAccessResourceException: Failed to update table [person]. Row with Id [0c7da262-7e71-495c-be35-404b7f14aca2] does not exist.
```

This happens because in your repository save method
```java
public class SimpleR2dbcRepository<T, ID> implements ReactiveSortingRepository<T, ID> {
     ....
     	/* (non-Javadoc)
	 * @see org.springframework.data.repository.reactive.ReactiveCrudRepository#save(S)
	 */
	@Override
	@Transactional
	public <S extends T> Mono<S> save(S objectToSave) {

		Assert.notNull(objectToSave, "Object to save must not be null!");

		if (this.entity.isNew(objectToSave)) {
			return this.entityOperations.insert(objectToSave);
		}

		return this.entityOperations.update(objectToSave);
}
```

The `isNew()` method will return false as the `PersistentEntityIsNewStrategy`'s `isNew()`  method does not support non primitive types
```java
class PersistentEntityIsNewStrategy implements IsNewStrategy {
	.....
	@Override
	public boolean isNew(Object entity) {

		Object value = valueLookup.apply(entity);

		if (value == null) {
			return true;
		}

		if (valueType != null && !valueType.isPrimitive()) {
			return false;
		}

		if (value instanceof Number) {
			return ((Number) value).longValue() == 0;
		}

		throw new IllegalArgumentException(
				String.format("Could not determine whether %s is new! Unsupported identifier or version property!", entity));
	}
}
```

Have I messed up my implementation, or is `spring-data-r2dbc` not supporting UUIDs as Id fields for now? 

FYI.  I can get this implementation to work, so long as I have my db set the ID field and my `Person` data class allows for nullable ID fields. Whilst this works, several colleagues do not like the idea of having a nullable field on a data type.

**Comment by mp911de** [comment]
The exception message doesn't fit the data model. `Person(name = "Jeff")` isn't expected to provide `UUID` however, the exception message mentions an UUID. Care to recheck what's going on?

>  method does not support non primitive types

That's not true, any non-null non-primitive value indicates an existing object (`valueType != null && !valueType.isPrimitive()`).

Generally, a `null` Identifier is considered to indicate a new object (see https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#is-new-state-detection).

**Comment by rieger-jared** [comment]
Hmm, ok. I guess that does make sense. I think the issue here is that I'm using Kotlin, which requires the definition of a field to be nullable or not. Internally people thought that an `@Id` field should never be null i.e., `@Id val id: UUID` *not* `@Id val id: UUID?`. In Java `@Id UUID id` would translate to the nullable case.

**Comment by mp911de** [comment]
A non-null complex object indicates that the entity is associated with an identifier (`UUID`, `Long`, any other object). Objects with an identifier can be updated or deleted. Objects without an identifier cannot be updated or deleted, only inserted. Part of that expectation is that the database generates the identifier that is then populated back into the actual object.

I'm closing this ticket since this ticket isn't actionable.
