### ISSUE TITLE
Entities without @ID fail to insert and count

### ISSUE THREAD

**Issue by marioburatto** [spring-projects/spring-data-r2dbc#672]
I have a Many-To-Many relation entity that fails to insert and count because R2dbcEntityTemplate requires a mandatory idProperty. 

I came to this issue while trying to workaround the lack of a Multi Id / Composite Id feature. The solution I found was have no @ID annotation and rely on the high flexibility provided by R2dbcEntityTemplate to create my repository (which was very easy by the way, as you can see [here](https://github.com/marioburatto/class-schedule/blob/v2.0-web_flux-r2dbc-based/src/main/java/com/philips/classschedule/repository/ScheduleRepository.java)).

The limitation I found was that part of the R2dbcEntityTemplate implementation forces a required idProperty with no reason for that during the insert and count operations. Please see bellow the details:

**_Insert Failure_**
As I'm using Postgres, all the insert statements have a ["RETURNING" clause appended](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/util/GeneratedValuesUtils.java#L51) to the [operation](https://github.com/spring-projects/spring-data-r2dbc/blob/main/src/main/java/org/springframework/data/r2dbc/core/R2dbcEntityTemplate.java#L634). When there is no ID, it appends "RETURNING *". With these data being returned back during the insert operation the entity template tries to [`populateIdIfNecessary`](https://github.com/spring-projects/spring-data-r2dbc/blob/main/src/main/java/org/springframework/data/r2dbc/convert/MappingR2dbcConverter.java#L603), but instead of just ignoring it because it's not necessary, it fails complaining the required idProperty. In the way I see, [MappingR2dbcConverter](https://github.com/spring-projects/spring-data-r2dbc/blob/main/src/main/java/org/springframework/data/r2dbc/convert/MappingR2dbcConverter.java#L603) could simply skip populateIdIfNecessary when the idProperty is null:

```
RelationalPersistentProperty idProperty = entity.getIdProperty();
if(idProperty == null){
    return object;
}
```
**_Count Failure_**
During the `doCount` operation [R2dbcEntityTemplate](https://github.com/spring-projects/spring-data-r2dbc/blob/main/src/main/java/org/springframework/data/r2dbc/core/R2dbcEntityTemplate.java#L324) submits a `Function.count()` to the projection and it fails because it requires the idProperty to be counted. The same issue supposed to happen with [`doExists`](https://github.com/spring-projects/spring-data-r2dbc/blob/main/src/main/java/org/springframework/data/r2dbc/core/R2dbcEntityTemplate.java#L358) operation, but the idProperty was already made optional there using a "*" field instead. I guess the same could be applied here by projecting a `count(*)` when there is no idProperty, like this:

```
SqlIdentifier columnName = entity.hasIdProperty() ? entity.getRequiredIdProperty().getColumnName()
                : SqlIdentifier.unquoted("*");

StatementMapper.SelectSpec selectSpec = statementMapper //
        .createSelect(tableName) //
        .doWithTable((table, spec) -> {
            return spec.withProjection(Functions.count(table.column(columnName)));
        });
```

If you want to, I can submit a PR with the fixes and a couple test cases.

Please let me know your thoughts.
 
Thanks, Mario.

**Comment by mp911de** [comment]
That issue was fixed with #711 since version `1.3.9`.
