### ISSUE TITLE
Threading model inside r2dbc stuff

### ISSUE THREAD

**Issue by polyoxidonium** [spring-projects/spring-data-r2dbc#677]
Consider following code snippets:

`public interface FooRepository extends ReactiveCrudRepository<Foo, String> { }`

```
   public class FooService {

    @Transactional
    public Mono<Foo> createFoo(Foo foo) {
        System.out.println("Before calling save " + Thread.currentThread().getName());

        return fooRepository.save(foo)
                .doOnNext(f -> System.out.println("After calling save " + Thread.currentThread().getName()));

    }
}
```

```
@WritingConverter
public class FooWriteConverter implements Converter<Foo, OutboundRow> {


    @Override
    public OutboundRow convert(Foo foo) {
        OutboundRow row = new OutboundRow();

            for (int i = 0; i <= 5000000; i++) { // time-consuming operation for testing purposes
                String id = UUID.randomUUID().toString();
                if (i == 5000000 ) {

                    System.out.println("In converter " + Thread.currentThread().getName());
                }
            }

        // further row manipulation logic
        return row;
    }
}
```

```
   @PostMapping(....)
    Mono<ResponseEntity<Foo>> createFoo(@RequestBody Mono<Foo> fooMono) {

        StopWatch stopWatch = new StopWatch();
        stopWatch.start();
        System.out.println("Started at:" + LocalDateTime.now() + " " + thread());

        return fooMono
                .flatMap(fooService::createFoo)
                .doOnNext(e -> {
                            stopWatch.stop();
                            System.out.println("TOTAL TIME: " + stopWatch.getTotalTimeSeconds() + " " + thread());
                        }
                )
                .map(ResponseEntity::ok);
    }
```

Test ran by 20 concurrent requests: 
`ab -c 20 -n 20 -p post.json -T application/json http://localhost:8080/foo`

**Number of cores:** 16
**Platform:** Mac OS

**Output for first x calls:**

> Started at:2021-11-03T09:04:11.033824 reactor-http-nio-2
> Before calling save reactor-http-nio-2
> In converter reactor-http-nio-2
> After calling save reactor-http-nio-2
> TOTAL TIME: 11.010088477 reactor-http-nio-2
> Started at:2021-11-03T09:04:22.091817 reactor-http-nio-3 // concurrent requests start here
> Started at:2021-11-03T09:04:22.091818 reactor-http-nio-4
> Started at:2021-11-03T09:04:22.091817 reactor-http-nio-5
> Started at:2021-11-03T09:04:22.093122 reactor-http-nio-6
> Started at:2021-11-03T09:04:22.105295 reactor-http-nio-7
> Started at:2021-11-03T09:04:22.118826 reactor-http-nio-9
> Started at:2021-11-03T09:04:22.118570 reactor-http-nio-8
> Started at:2021-11-03T09:04:22.135115 reactor-http-nio-10
> Started at:2021-11-03T09:04:22.142527 reactor-http-nio-14
> Started at:2021-11-03T09:04:22.142240 reactor-http-nio-11
> Started at:2021-11-03T09:04:22.142691 reactor-http-nio-13
> Started at:2021-11-03T09:04:22.142721 reactor-http-nio-12
> Started at:2021-11-03T09:04:22.143177 reactor-http-nio-15
> Before calling save reactor-http-nio-2
> Started at:2021-11-03T09:04:22.151494 reactor-http-nio-16
> Started at:2021-11-03T09:04:22.151667 reactor-http-nio-1
> Started at:2021-11-03T09:04:22.155935 reactor-http-nio-3
> Started at:2021-11-03T09:04:22.155943 reactor-http-nio-5
> Started at:2021-11-03T09:04:22.156003 reactor-http-nio-4
> In converter reactor-http-nio-2
> After calling save reactor-http-nio-2
> TOTAL TIME: 11.495113162 reactor-http-nio-2
> Before calling save reactor-http-nio-2
> In converter reactor-http-nio-2
> After calling save reactor-http-nio-2
> TOTAL TIME: 22.697217733 reactor-http-nio-2
> Before calling save reactor-http-nio-2
> In converter reactor-http-nio-2
> After calling save reactor-http-nio-2
> TOTAL TIME: 34.253708362 reactor-http-nio-2
> Before calling save reactor-http-nio-2
> In converter reactor-http-nio-2
> After calling save reactor-http-nio-2
> TOTAL TIME: 45.456054985 reactor-http-nio-2

**Thread dump:** 
![image](https://user-images.githubusercontent.com/93198297/140026673-f6552d3f-cd6e-40ea-8894-ba2244d4caaf.png)

**Now finally the question:**
Why is everything inside r2dbc stuff happening on one thread and the other threads are idle? 
 So even blocking operation is not explicitly blocking as i can reuse other threads for let's say another http calls. 
My teammate made assumption that it has something to do the with Transactional stuff, so we tried to remove it. 
After removing `@Transactional`
line `System.out.println("Before calling save " + Thread.currentThread().getName());` inside `createFoo(..)` 
was not printing the same thread for different request anymore, contrariwise it behaved exactly as in the line
`System.out.println("Started at:" + LocalDateTime.now() + " " + thread());`

However, things happening after calling .save()  - like inside converters, were still happening sequentially on the same thread delaying each concurrent request by processing time of the previous request. (see TOTAL TIME) 

Are we doing something wrong or is this a correct behavior? Could someone please explain?
If we try to use `publishOn(Schedulers.boundedElastic())` inside `createFoo(..)` method it behaves just the same - same thread used for r2dbc stuff but its boundedElastic-X
If we try to use `subscribeOn(Schedulers.boundedElastic())` inside `createFoo(..)` method it spawns X boundedElastic threads and they are concurrently accessing SecureRandom so each moment 1 is working with it and others are blocked. 

Thank you for any reasonable explanations.

**Comment by mp911de** [comment]
Check out https://spring.io/blog/2019/12/13/flight-of-the-flux-3-hopping-threads-and-schedulers. Running workloads on the same thread makes the most sense and the framework cannot reason what type of work you're performing so it cannot assume any context switches. Moreover, there's no way to interrupt or yield work from within a library.

**Comment by saquibmian** [comment]
@mp911de Am I understanding correctly that, at some point, all R2DBC operations are multiplexed onto a single thread? So there is not really any parallelism? Does this apply at the connection level only, or across all connections?
If so, what happens if r2dbc-pool is being used?
