### ISSUE TITLE
Failed to obtain R2DBC, this publisher does not support multiple subscribers

### ISSUE THREAD

**Issue by Shen94** [spring-projects/spring-data-r2dbc#681]
Hi , 

Please see issue :- https://github.com/oracle/oracle-r2dbc/issues/47 

Is there a plan to upgrade to Oracle R2dbc 0.3.0 to support the above?

**Comment by mp911de** [comment]
You should be able to upgrade to Oracle's driver in your own project. Make sure to also upgrade the SPI version as Oracle has upgraded to R2DBC 0.9 as of Oracle R2DBC 0.2.0+.

**Comment by Shen94** [comment]
Yeah , that is possible , but I am getting the following exception(UnsupportedOperationException(
        "This method is deprecated for removal")) when trying to use Spring with Oracle 0.3.0. 

Doing some debugging , I noticed that Oracle 0.3.0 updated their method to this.

https://github.com/oracle/oracle-r2dbc/blob/main/src/main/java/oracle/r2dbc/impl/ReadablesMetadata.java#L252

    @Override
    public Collection<String> getColumnNames() {
      throw new UnsupportedOperationException(
        "This method is deprecated for removal");
    }

**Comment by mp911de** [comment]
It would make sense to update our code to not use deprecated methods. I filed #683.

**Comment by rmalired** [comment]
> You should be able to upgrade to Oracle's driver in your own project. Make sure to also upgrade the SPI version as Oracle has upgraded to R2DBC 0.9 as of Oracle R2DBC 0.2.0+.

@mp911de  how do I specify to use the 0.9 SPI version. i have the following dependency config in pom.xml, but still running into same error as beginning of the thread.

               <dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-r2dbc</artifactId>
			<version>1.4.3</version>
		</dependency>
		<dependency>
			<groupId>com.oracle.database.r2dbc</groupId>
			<artifactId>oracle-r2dbc</artifactId>
			<version>0.4.0</version>
		</dependency>
		<dependency>
			<groupId>io.r2dbc</groupId>
			<artifactId>r2dbc-spi</artifactId>
			<version>0.9.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>io.r2dbc</groupId>
			<artifactId>r2dbc-pool</artifactId>
			<version>0.9.0.RELEASE</version>
		</dependency>

**Comment by Bishree** [comment]
@rmalired You are using the last updated oracle driver `<version>0.9.1.RELEASE</version>` and I have the same problem did you solve it? if you did appreciate sharing the solution.
