### ISSUE TITLE
R2dbc-mssql Failed to obtain R2DBC Connection: ConnectionTimeOutException

### ISSUE THREAD

**Issue by psishodhiya** [spring-projects/spring-data-r2dbc#692]
We are using R2dbcEntityTemplate to fetch/read custom query resultset  into the flux. We are consuming this stream of flux using rest service , flow is working fine but the issue is for the same request we are getting connection timeout exception though Database connectivity is fine.
Due to this our api is not stable , could you please suggest here what could be wrong here.

We are creating connectionfactory by using below : 
new MssqlConnectionFactory(MssqlConnectionConfiguration.builder().host(url).port(port).database().username().password().build());

**Comment by mp911de** [comment]
That sounds like a database issue. If you can provide a minimal reproducer along with debug logs, then feel free to file an issue at https://github.com/r2dbc/r2dbc-mssql/issues.

**Comment by psishodhiya** [comment]
Thanks for replying.
Actually due to company policy i can not upload stack trace , but i have attached the image of stack trace.
We are running on mssql availability group .
Not using any r2dbc pooling.
I have tried same request hitting multiple times , pattern is like first request returns data then 2nd request stuck for 30seconds and throws exception ,then for 3rd request after few min again it goes success.
For the same request behaviour is different.
Could you please suggest what wrong i might be doing.
If requires i will post same query on your suggested thread.
![20211214_160740](https://user-images.githubusercontent.com/29621896/145983225-f1555661-ec91-492e-a0fa-c6ed0a8d1394.jpg)

**Comment by psishodhiya** [comment]
Actually due to company policy i can not upload stack trace , but i have attached the image of stack trace.
We are running on mssql availability group .
Not using any r2dbc pooling.
I have tried same request hitting multiple times , pattern is like first request returns data then 2nd request stuck for 30seconds and throws exception ,then for 3rd request after few min again it goes success.
For the same request behaviour is different.
Could you please suggest what wrong i might be doing.
If requires i will post same query on your suggested thread.
![20211214_161700](https://user-images.githubusercontent.com/29621896/145984015-b2bc480e-2dc6-44bb-9dc9-806cfeeea0c6.jpg)

**Comment by psishodhiya** [comment]
Actually due to company policy i can not upload stack trace , but i have attached the image of stack trace.
We are running on mssql availability group .
Not using any r2dbc pooling.
I have tried same request hitting multiple times , pattern is like first request returns data then 2nd request stuck for 30seconds and throws exception ,then for 3rd request after few min again it goes success.
For the same request behaviour is different.
Could you please suggest what wrong i might be doing.
If requires i will post same query on your suggested thread.
![20211214_162317](https://user-images.githubusercontent.com/29621896/145984896-4bab8806-d224-4a0e-884b-6d83c65bb2a3.jpg)
