### ISSUE TITLE
Nested aggregations that used to work with 1.3.6 no longer work with 1.4.0

### ISSUE THREAD

**Issue by mariusstaicu** [spring-projects/spring-data-r2dbc#695]
After upgrading spring-data-r2dbc from 1.3.6 to 1.4.0 (spring boot upgrade from 2.5.6 to 3.6.1), the queries with nested aggregate objects no longer work.

example:

```
data class TimezoneAgg(
    val device: DeviceAgg,
    val name: DevicePropertyName,

    @Column("value")
    val timezone: Long
)

data class DeviceAgg(
    val id: Long,
    val name: String
)

interface DevicePropertyRepository : CoroutineCrudRepository<DeviceProperty, Long> {
    @Query("""select d.id as device_id, d.name as device_name, dp.name, dp.value from device d inner join device_property dp 
        on d.id = dp.device_id where dp.name = 'TIMEZONE' and d.id in (:devices)""")
    suspend fun getTimezones(ids: List<Long>): List<TimezoneAgg>
}
```

before upgrade produced this result:

```
[
  {
    "device": {
      "id": 7,
      "name": "device1"
    },
    "name": "timezone",
    "timezone": 180
  },
  {
    "device": {
      "id": 6,
      "name": "device2"
    },
    "name": "timezone",
    "timezone": 120
  }
]
```

and after upgrade throws this exception:
```
Failed to instantiate ro.wstudios.r2dbc.device.TimezoneAgg using constructor fun <init>(ro.wstudios.r2dbc.device.DeviceAgg, ro.wstudios.r2dbc.device.DevicePropertyName, kotlin.Long): ro.wstudios.r2dbc.device.TimezoneAgg with arguments null,timezone,180
org.springframework.data.mapping.model.MappingInstantiationException: Failed to instantiate ro.wstudios.r2dbc.device.TimezoneAgg using constructor fun <init>(ro.wstudios.r2dbc.device.DeviceAgg, ro.wstudios.r2dbc.device.DevicePropertyName, kotlin.Long): ro.wstudios.r2dbc.device.TimezoneAgg with arguments null,timezone,180
```

**Comment by elefeint** [comment]
Drive-by comment: try adding a constructor to `TimezoneAgg` that omits `device` field from being auto-constructed. We just had a [completely unrelated (not R2DBC) but similar issue](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/774) because the underlying library was setting "magic" properties in post-construction.

**Comment by mp911de** [comment]
Spring Data R2DBC generally does not support nested objects when trying to materialize these from a `JOIN`. Nested objects only work when using custom converters.

**Comment by mariusstaicu** [comment]
I wondered also why it wasn't documented properly, however it was a very nice feature to have.

**Comment by mariusstaicu** [comment]
> Drive-by comment: try adding a constructor to `TimezoneAgg` that omits `device` field from being auto-constructed. We just had a [completely unrelated (not R2DBC) but similar issue](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/774) because the underlying library was setting "magic" properties in post-construction.

I will try, however if it is not supposed to be supported, I wouldn't go this way at all.

**Comment by schauder** [comment]
As @mp911de mentioned. This was not intended to have worked in the first place since R2DBC does not support JOIN right now.
