### ISSUE TITLE
MSSQL: Using IsTrue or True in Query Method doesn't work on BIT columns

### ISSUE THREAD

**Issue by jsmwoolf** [spring-projects/spring-data-r2dbc#698]
Provided the following schema and Java code:

Schema
```sql
CREATE TABLE Books
(
  ID INTEGER,
  available BIT DEFAULT 1,
  Title NVARCHAR(128) NOT NULL,
  PRIMARY KEY (ID)
)
```

Book DTO
```java
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Table(value = "Books")
public class Book {
    @Id
    private Integer id;
    private String name;
    private Boolean available;
}

```

Book Repository
```java
public interface BookRepository extends R2dbcRepository<Book, Integer > {
    Mono<Boolean> existsByIdAndAvailableTrue(Integer id);
}
```

Any attempts to call `existsByIdAndAvailableTrue()` throws the following error:
`io.r2dbc.mssql.ExceptionFactory$MssqlBadGrammarException: Invalid column name 'TRUE'.`

The query that the function generates is as follows:
`SELECT Books.id, Books.name, Books.available FROM Books WHERE Books.id = @P0_id AND (Books.available = TRUE)`

The expected behavior should be that, given a BIT column mapped to a Java Boolean value, Spring Data R2DBC should be able to correctly check whether the BIT column is `TRUE` or `FALSE`.

**Comment by mp911de** [comment]
See also spring-projects/spring-data-jdbc#908
