### ISSUE TITLE
Skipping Test using TestContainers in case docker not present

### ISSUE THREAD

**Issue by DiegoKrupitza** [spring-projects/spring-data-r2dbc#718]
I wanted to build the project locally with `mvn clean install` and at the test stage it fails, since for integration tests docker is required (so testcontainers can be started). 

The following tests failed:
```
[ERROR] Errors: 
[ERROR]   MariaDbDatabaseClientIntegrationTests » UnsupportedOperation NoAvailableDataba...
[ERROR]   MariaDbTransactionalDatabaseClientIntegrationTests » UnsupportedOperation NoAv...
[ERROR]   PostgresDatabaseClientIntegrationTests » UnsupportedOperation NoAvailableDatab...
[ERROR]   PostgresIntegrationTests » UnsupportedOperation NoAvailableDatabase
[ERROR]   PostgresTransactionalDatabaseClientIntegrationTests » UnsupportedOperation NoA...
[ERROR]   MariaDbR2dbcRepositoryIntegrationTests » UnsupportedOperation NoAvailableDatab...
[ERROR]   MariaDbR2dbcRepositoryWithMixedCaseNamesIntegrationTests » UnsupportedOperation
[ERROR]   PostgresR2dbcRepositoryIntegrationTests » UnsupportedOperation NoAvailableData...
[ERROR]   PostgresR2dbcRepositoryWithMixedCaseNamesIntegrationTests » UnsupportedOperation
[ERROR]   PostgresSimpleR2dbcRepositoryIntegrationTests » UnsupportedOperation NoAvailab...
[ERROR] Tests run: 619, Failures: 0, Errors: 10, Skipped: 4
```

Is it possible to skip those tests who require test containters, in case docker is not present?

**Comment by mp911de** [comment]
Our tests accept either a locally running database or use Docker to spin up databases. If both are not available, then the tests fail. We do not want to silently skip those tests as the risk that things go unnoticed is high. 

We've abstracted the database availability in the `ExternalDatabase` base class which could be used as extension point to conditionally skip the entire test class if someone wants to skip tests if the infrastructure is not provided.

**Comment by DiegoKrupitza** [comment]
> Our tests accept either a locally running database or use Docker to spin up databases. If both are not available, then the tests fail. We do not want to silently skip those tests as the risk that things go unnoticed is high.
> 
> We've abstracted the database availability in the `ExternalDatabase` base class which could be used as extension point to conditionally skip the entire test class if someone wants to skip tests if the infrastructure is not provided.


Ok thank you for clarifying! 👍🏽
