### ISSUE TITLE
Impossible to get Related entity with MappingR2dbcConverter

### ISSUE THREAD

**Issue by myosotys** [spring-projects/spring-data-r2dbc#737]
Hello,

I have a small problem, i use MappingR2dbcConverter to map my entity, but I recently update the version (1.2.15 but i think the problem is always present) and i have a problem with related entity. I think the problem (if the problem is not me) is in this code

	private Object readFrom(Row row, @Nullable RowMetadata metadata, RelationalPersistentProperty property,
			String prefix) {

		String identifier = prefix + property.getColumnName().getReference();

		try {

			Object value = null;
			if (metadata == null || RowMetadataUtils.containsColumn(metadata, identifier)) {
				value = row.get(identifier);
			}

			if (value == null) {
				return null;
			}

			if (getConversions().hasCustomReadTarget(value.getClass(), property.getType())) {
				return readValue(value, property.getTypeInformation());
			}

			if (property.isEntity()) {
				return readEntityFrom(row, metadata, property);
			}

			return readValue(value, property.getTypeInformation());

		} catch (Exception o_O) {
			throw new MappingException(String.format("Could not read property %s from column %s!", property, identifier),
					o_O);
		}
	}

In case of related entity, the code never go to "readEntityFrom" because "RowMetadataUtils.containsColumn(metadata, identifier)" cannot be true
Work before cause "property.isEntity()" was checked before return null.

Example:

	User{
		String id;
		Client client;
	}
	Client{
		String id;
		String name;
	}

The row returned container column: id, client_id and client_name but the function readFrom search an identifier "client" that doest not exist.

Am I missing something ?

**Comment by mp911de** [comment]
This is a known limitation. Nested entities are not supported, see #288

**Comment by myosotys** [comment]
it was not a limitation before (at least for this class). My example work fine in 1.2.14, not in 1.2.15 and higher
