### ISSUE TITLE
Add support for MySQL

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-r2dbc#75]
We should add support for MySQL (dialect and tests) and use the https://github.com/jasync-sql/jasync-sql/ driver that wraps their asynchronous driver with an R2DBC facade.

**Comment by mp911de** [comment]
Open issues:

* jasync-sql/jasync-sql#105
* jasync-sql/jasync-sql#106

Beyond that, the driver does not yet support batching and `ConnectionFactoryDiscovery`

**Comment by oshai** [comment]
I am not sure what you mean by discovery. The driver do support parsing a url like this: `com.github.jasync.sql.db.mysql.util.URLParser.parseOrDie(url)`.

Just in case it helps somehow.

**Comment by mp911de** [comment]
R2DBC has a built-in `ConnectionFactory` discovery through `io.r2dbc.spi.ConnectionFactories.get(…)` (and as soon as r2dbc/r2dbc-spi#48 gets merged also an URL-based variant). This allows a consistent configuration that is independent from the driver. 

All it requires on the driver side is a [`ConnectionFactoryProvider`](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/java/io/r2dbc/postgresql/PostgresqlConnectionFactoryProvider.java) implementation and registration for [Java Service Loader](https://github.com/r2dbc/r2dbc-postgresql/blob/master/src/main/resources/META-INF/services/io.r2dbc.spi.ConnectionFactoryProvider).

**Comment by mp911de** [comment]
Here's a link to a working example: https://gist.github.com/mp911de/ace06d31527dcbb245d63f03a7f9322a

The linked artifact references a branch build. Once this ticket gets resolved, the support will be merged to `master` and support will be available from regular builds.

**Comment by oshai** [comment]
Add Connection factory here: https://github.com/jasync-sql/jasync-sql/pull/112

**Comment by schauder** [comment]
Done.
