### ISSUE TITLE
PostgreSQL:How to display SQL parameters correctly

### ISSUE THREAD

**Issue by maojx0630** [spring-projects/spring-data-r2dbc#752]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/37826107/163780940-40823c40-3eba-4ecf-b902-52044b7a13b4.png">
<img width="964" alt="image" src="https://user-images.githubusercontent.com/37826107/163781059-f1c99c70-ab26-4282-9479-a16c06218a4a.png">

`
@Autowired private R2dbcEntityTemplate template;

  public Flux<Test> getTest() {
    return template
        .getDatabaseClient()
        .sql("select * from test a where name like :name")
        .bind("name", "%t%")
        .fetch()
        .all()
        .flatMap(map -> TestService.as(map, Test.class));
  }
`

How do I get it to display the parameter values normally？

**Comment by mp911de** [comment]
With the 3.0 version, we're using R2DBC SPI 0.9 with its `Parameter` abstraction. `Parameter.toString()` does not expose the value to prevent accidental logging. The actual logging is invoked by the driver. You can either submit a pull request to update `BindingLogger` or file simply a ticket at https://github.com/pgjdbc/r2dbc-postgresql/issues.
