### ISSUE TITLE
Release 1.5 GA (2021.2.0)

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-r2dbc#753]

**Comment by linghengqian** [comment]
I noticed that springboot 2.7.0 has started to use spring data r2dbc 1.5.0, but the r2dbc driver introduced for mysql on start.spring.io is still dev.miku:r2dbc-mysql of R2DBC SPI 0.8.2.RELEASE. Is it also expected behavior?

**Comment by sp00m** [comment]
> I noticed that springboot 2.7.0 has started to use spring data r2dbc 1.5.0, but the r2dbc driver introduced for mysql on start.spring.io is still dev.miku:r2dbc-mysql of R2DBC SPI 0.8.2.RELEASE. Is it also expected behavior?

Just noticed the same, I used to have the following working:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-r2dbc</artifactId>
</dependency>
<dependency>
    <groupId>dev.miku</groupId>
    <artifactId>r2dbc-mysql</artifactId>
</dependency>
```

But I now get:

```
'dependencies.dependency.version' for dev.miku:r2dbc-mysql:jar is missing.
```

What's the recommended config from now on?
