### ISSUE TITLE
io.r2dbc.spi.Row.get(...) from Postgres Array<varchar> to Kotlin List<URI> conversion

### ISSUE THREAD

**Issue by Matt8654** [spring-projects/spring-data-r2dbc#771]
Using Postgres 12 and r2dbc 0.9.1
The field is a Postgres array type holding varchars.

I can use `row.get("examples", Array<URI>::class.java)`  to retrieve a java array type, but my data type is the kotlin list.
This forces me to use `row.get("examples", Array<URI>::class.java)?.toList()`

I can't get the correct class because of the issue mentioned in [this SO link: ](https://stackoverflow.com/questions/39679180/kotlin-call-java-method-with-classt-argument/39688441#39688441)
I've tried using things like the following to grab the class of the list of URIs
`val listOfURIClass: Class<List<URI>> = listOf<URI>().javaClass`
but run into class cast exceptions.
```
java.lang.ClassCastException: Cannot cast [Ljava.lang.String; to kotlin.collections.EmptyList
	at java.base/java.lang.Class.cast(Class.java:3921)
```

Is this a known issue or am I using the conversion incorrectly? 

Thanks in advance!

**Comment by mp911de** [comment]
This seems to be a usage problem within Kotlin. Apart from that, the type `io.r2dbc.spi.Row` belongs to the R2DBC specification. This repository addresses only concerns regarding Spring Data R2DBC.
