### ISSUE TITLE
The code that initializes the mapping of enums of the DB-JVM is processed once

### ISSUE THREAD

**Issue by geliotropv** [spring-projects/spring-data-r2dbc#772]
There is a service that starts before the connection to the database appears, after the connection appears, this situation occurs:
EnumCodec is created after the connection is received and the code that initializes the DB-JVM enum mapping has already completed. Because we have a pool and this mapping seems to be called only once. The first launch of the service cannot be successful.
How to start this mapping process again after receiving the connection?

**Comment by mp911de** [comment]
I do not understand what you're trying to achieve or what the problem is. `EnumCodec` is also not a class of Spring Data R2DBC.

**Comment by geliotropv** [comment]
Maybe it qustion to r2dbc-postgresql If so, I'll add this discussion there.
I am using below given dependencies
```
org.springframework.data:spring-data-r2dbc
org.postgresql:r2dbc-postgresql
io.r2dbc:r2dbc-pool
```
The service itself uses in k8s with postgres pod that start after service
This servise have several of enums that I connect via R2dbcCustomConversions + EnumCodec.builder() from r2dbc posgresql
In the base itself I have a created `TYPE myenum AS ENUM`
And after reading the records from the database, I see errors related to the fact that there is no codec that could read the enum from postgresql
When starting the service now I see the following error
`EnumCodec : Could not lookup enum types for: [myenum]`
And after service start read row from db show next exception
`Caused by: java.lang.IllegalArgumentException: Cannot decode value of type test.package.MuClass$MyEnum with OID 16418
at io.r2dbc.postgresql.codec.DefaultCodecs.decode(DefaultCodecs.java:222) ~[r2dbc-postgresql-0.9.1.RELEASE.jar:0.9.1.RELEASE]`
I'm looking for a way to restart mapping these enums after getting a database connection.
A little later I will make a project example with this problem
I'll probably move the discussion to r2dbc-postgresql

**Comment by geliotropv** [comment]
Move the discussion to r2dbc-postgresql
