### ISSUE TITLE
[2.7.2] Add Support for Kotlin Value Classes

### ISSUE THREAD

**Issue by rowi1de** [spring-projects/spring-data-r2dbc#779]
- Issue from spring-data-commons https://github.com/spring-projects/spring-data-commons/issues/1947 https://github.com/spring-projects/spring-data-relational/issues/1093#issuecomment-972917101
- Spring + Dependencies 2.7.2 
```kotlin
@Repository
interface ValueRepository : CoroutineCrudRepository<DbValue UUID> {}

@Table("value")
class DbValue( val someValue: SomeValue )

@JvmInline
value class SomeValue(val value: String)

```

**Comment by schauder** [comment]
Duplicate of https://github.com/spring-projects/spring-data-relational/issues/1093
