### ISSUE TITLE
Bad SQL grammar - Spring data R2DBC with Oracle

### ISSUE THREAD

**Issue by alessiofiore** [spring-projects/spring-data-r2dbc#782]
Hi,
I'm using Spring Data R2DBC with Oracle and I have the following error using method `findById `of `R2dbcCrudRepository`

    executeMany; bad SQL grammar [SELECT GAME_PHASE.* FROM GAME_PHASE WHERE GAME_PHASE.ID = :P0_id FETCH FIRST 2 ROWS ONLY]

This is the repository declaration

    public interface ReactiveGamePhaseRepository extends R2dbcRepository<GamePhase, Long> {
    }

I don't understand why FETCH FIRST 2 ROWS ONLY is added to the query and it's the cause of problem.

I have the same problem writing the query using R2dbcEntityTemplate like below:

    r2dbcEntityTemplate.selectOne(query(where("id").is(id)), GamePhase.class);

And these are the used dependancies:

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-r2dbc</artifactId>
        <version>2.5.12</version>
    </dependency>

    <dependency>
        <groupId>com.oracle.database.r2dbc</groupId>
        <artifactId>oracle-r2dbc</artifactId>
        <version>1.0.0</version>
    </dependency>

**Comment by mp911de** [comment]
Spring Data uses ANSI-style limit/offset clauses; See [`AnsiDialect`](https://github.com/spring-projects/spring-data-relational/blob/main/spring-data-relational/src/main/java/org/springframework/data/relational/core/dialect/AnsiDialect.java#L41.)

If you're using a database version that doesn't support that style, please subclass the `OracleDialect` and provide a `LimitClause` implementation that uses a syntax that is supported.

Dialects are selected on the driver and we do not connect to the database to obtain e.g. database versions for the dialect selection process.

Paging also @schauder

**Comment by schauder** [comment]
Older versions of Oracle did require various ways to implement pagination. Spring Data JDBC&R2DBC only explicitly support Oracle 18+.

Oracle 12 can be made work by implementing and registering a custom Dialect. See the discussion here: https://stackoverflow.com/questions/67036621/oracle-dialect-for-pagination

Oracle 11 and before require an inner select which can't be implemented with our current infrastructure. For those cases you'd have to write custom queries.

We will not add support for these versions.

If you are indeed run a 18+version of Oracle and see these problems, please reopen with a reproducer.
