### ISSUE TITLE
Exhaust allocated connections of pool when database shuts down

### ISSUE THREAD

**Issue by hypr2771** [spring-projects/spring-data-r2dbc#783]
## Context

`mvn dependency:tree` gives the following output:

```
[INFO] |  +- io.r2dbc:r2dbc-spi:jar:0.8.6.RELEASE:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  \- io.r2dbc:r2dbc-pool:jar:0.8.8.RELEASE:compile
[INFO] |     \- io.projectreactor.addons:reactor-pool:jar:0.2.8:compile
```

## Issue

When rolling out database while pool already allocated connections, we can see the following log X times (X being the number of allocated connections):

```log
2022-09-07 19:00:24.377  WARN 2103364 --- [tor-tcp-epoll-1] i.r.p.client.ReactorNettyClient          :
Error: SEVERITY_LOCALIZED=FATAL, SEVERITY_NON_LOCALIZED=FATAL, CODE=57P01,
       MESSAGE=terminating connection due to administrator command, FILE=postgres.c,
       LINE=3094, ROUTINE=ProcessInterrupts
```

When starting the new database, these allocated connections keeps being used, resulting in the following error:

```log
org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection;
nested exception is io.r2dbc.spi.R2dbcNonTransientResourceException: Connection validation failed
```

I tried using `validation-depth: REMOTE` and `validation-query: "SELECT 1"`, but it does not seem to be enough, connections are not being validated and exhausted upon failing.

## Suggestion

Since we can detect connection failing (indeed, we have those `ReactorNettyClient` logs), could we also exhaust these connections from the pool, so that upon new database starting up, we could immediately acquire fresh connections for the pool and use them?

## Workaround

If this is not doable or too complex, is there any possible workarounds (apart from disabling connection pooling)?

**Comment by mp911de** [comment]
Connection pooling is handled by https://github.com/r2dbc/r2dbc-pool. R2DBC Pool uses Reactor Pool for object pooling and the underlying implementation does not provide a mechanism to clear the pool.

**Comment by hypr2771** [comment]
> Connection pooling is handled by https://github.com/r2dbc/r2dbc-pool. R2DBC Pool uses Reactor Pool for object pooling and the underlying implementation does not provide a mechanism to clear the pool.

If I understand correctly, the only way to actually handle such cases would be to have a retry back-off to create a new connection upon detecting such cases?
Or would you suggest another method?
