### ISSUE TITLE
Empty collection not converted to correct type when using element-wise converters

### ISSUE THREAD

**Issue by jurriaan** [spring-projects/spring-data-r2dbc#796]
We're using java `Duration` types that get converted to `Interval` using Reading/WritingConverters:

```kotlin
@WritingConverter
object DurationToIntervalConverter : Converter<Duration, Interval> {
    override fun convert(source: Duration): Interval = Interval.of(source)
}
```

This seems to work fine for columns of type `Duration`, however it does not work on `List<Duration>` when that list is an empty list.
When trying to persist an empty list I get the following error:

```
java.lang.IllegalArgumentException: Cannot encode parameter of type [Ljava.time.Duration; ([Ljava.time.Duration;@45b7445b)
	at io.r2dbc.postgresql.codec.DefaultCodecs.encodeParameterValue(DefaultCodecs.java:276)
	at io.r2dbc.postgresql.codec.DefaultCodecs.encode(DefaultCodecs.java:250)
	at io.r2dbc.postgresql.PostgresqlStatement.bind(PostgresqlStatement.java:107)

```

This can be tracked down to this part of spring-data-r2dbc:
https://github.com/spring-projects/spring-data-r2dbc/blob/fbe3bfb63ebb2aee8fa0efed25083e3fa5643851/src/main/java/org/springframework/data/r2dbc/core/DefaultReactiveDataAccessStrategy.java#L248-L259

For collections it first tries to find a common type based on the elements using `CollectionUtils.findCommonElementType((Collection<?>) value.getValue())` (which are already converted if there were elements in the array). 

This means that for non-empty collections it will correctly use the `Interval` type, but for empty collections it will actually use `converter.getTargetType(actualType)`, which returns `Duration`.

Is there a way to get converters to work properly? 

Especially since the docs say that per-element converters is the way to go:

> Please note that converters get applied on singular properties. Collection properties (e.g. Collection<Person>) are iterated and converted element-wise.

**Comment by mp911de** [comment]
That's fixed and forward-ported now.
