### ISSUE TITLE
exchange() should allow to deal with DROP or  CREATE requests

### ISSUE THREAD

**Issue by sdeleuze** [spring-projects/spring-data-r2dbc#8]
Like `exchange()` provides a generic way to deal with requests in `WebClient` even those with no body, I would expect `DatabaseClient` variant to do the same. Maybe by providing in `SqlResult` methods suitable to deal with request with no rows like `DROP` or ` CREATE` ones.

**Comment by mp911de** [comment]
My gut feeling says we should get rid of `exchange()` for the time being. `exchange` currently only adds an indirection via ` Mono.just(new SqlResult(…))`. The implication is that if no subscriber ever subscribes to `Publisher`s supplied via `SqlResult`, then no query is executed at all.

We could instead replace `exchange()` with `Mono<Void> then()` to initiate execution and discard the results for the time being.

Thoughts? /cc @nebhale @gregturn @odrotbohm @schauder

**Comment by sdeleuze** [comment]
I tend to agree. The use case here is different from HTTP where we need to analyze status code or headers to know if we want to process the body or not. Here it mainly depends on this kind of request, so if I understand the proposal correctly, it would be less confusing for users to get rid of `exchange()` and provide directly at `GenericExecuteSpec` level the various choices possible including a method that returns `Mono<Void> `.

**Comment by nebhale** [comment]
Concur.  Something returning `Mono<Void>` is the idiomatic way of indicating a behavior with no return value, but still signaling completion.

**Comment by mp911de** [comment]
I pushed 534b76feb14ecdc19b7ed13a59c3d550953ec7bb to a feature branch that introduces a generic `then()` method for insert and execute statements via `DatabaseClient`. This change also removes the `exchange` method and moves result extraction specification a level up so we have now `map(…)` methods in select/insert/execute paths which reads as follows:

Insert:

* `insert()…map((row, metadata) -> …).first()/one()/all()`
* `insert()…fetch().first()/one()/all()/rowsUpdated()`

Execute:

* `execute()…map((row, metadata) -> …).first()/one()/all()`
* `execute()…fetch().first()/one()/all()/rowsUpdated()`

Select:

* `select()…map((row, metadata) -> …).first()/one()/all()`
* `select()….as(Person.class).fetch().first()/one()/all()`
* `select()…fetch().first()/one()/all()`

The main difference between `fetch()` and `map(…)` is that `fetch()` emits `Map<String, Object>` as default result type.

```java
Flux<Integer> ids = databaseClient.insert()
				.into("legoset")
				.value("id", 42055)
				.value("name", "Description")
				.nullValue("manual", Integer.class)
				.map((r, m) -> r.get("id", Integer.class)
				.all();

Mono<Void> completion = databaseClient.insert()
				.into(LegoSet.class)
				.using(legoSet)
				.then();
```

Thoughts?

**Comment by schauder** [comment]
Done.
