### ISSUE TITLE
Repository's save method throws class java.lang.Long cannot be cast to class java.lang.Integer exception

### ISSUE THREAD

**Issue by vmonastyrov** [spring-projects/spring-data-r2dbc#812]
Language: Kotlin
Spring R2dbc Version: spring-boot-starter-data-r2dbc:2.7.8
Driver Version: r2dbc-h2:1.0.0.RELEASE

My code:

```
interface ProducerRepository : CoroutineCrudRepository<cProducerEntity, Long> {}
```
```
@Table(name = TABLE_NAME)
data class ProducerEntity(
  @Id
  @Column("${FIELD_PREFIX}_id")
  val id: Long,

  @Column("${FIELD_PREFIX}_name")
  val name: String?,

  @Column("${FIELD_PREFIX}_description")
  val description: String?,

  @Column("${FIELD_PREFIX}_registered")
  val registered: Boolean,

  @Column("${FIELD_PREFIX}_writer_id")
  val writerId: Long,

  @Column("${FIELD_PREFIX}_url")
  val url: String,

  @Column("${FIELD_PREFIX}_created_at")
  val createdAt: LocalDateTime,

  @Column("${FIELD_PREFIX}_updated_at")
  @LastModifiedDate
  val updatedAt: LocalDateTime
)
```
```
suspend fun unregisterProducer(id: Long): Result<ProducerEntity> {
    val producer = repo.findById(id) ?: return Result.failure(Throwable("Producer can not be null"))
    return writerClient.unregisterProducer(producer.writerId).map { 
      repo.save(producer.copy(registered = false, writerId = 0L))
    }
  }
```
It throws `Exception: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at java.base/java.util.stream.Collectors.lambda$summingInt$19(Collectors.java:673)`
Despite the exception row in DB is updated.

**Comment by mp911de** [comment]
Spring Boot 2.7 supports only R2DBC 0.9. Please either downgrade your driver or upgrade to Spring Boot 3.0.

**Comment by vmonastyrov** [comment]
Thank you a lot for your answer. Unfortunately I cannot upgrade to Spring Boot 3.0 therefore I downgraded h2 driver and the save method works now.
