### ISSUE TITLE
Superfluous `Arrays.fill(…)` in `ArrayUtils.getArrayClass(…)`

### ISSUE THREAD

**Issue by mitu2** [spring-projects/spring-data-r2dbc#813]
https://github.com/spring-projects/spring-data-r2dbc/blob/c3301f500c514682f37c473a6c9648add53dd8f5/src/main/java/org/springframework/data/r2dbc/support/ArrayUtils.java#L77
What is the purpose of using this? Isn't the default value of int [] 0? Why fill 0 once

**Comment by mp911de** [comment]
Good catch, seems like an oversight on our side.
