### ISSUE TITLE
How to select some properties with lambda function?

### ISSUE THREAD

**Issue by pigping88** [spring-projects/spring-data-r2dbc#814]
Repository.findBy(Example.of(Member), reactiveFluentQuery -> {
             reactiveFluentQuery.project(Member::getID() ....)
        });

Now,
Repository.findBy(Example.of(Member), reactiveFluentQuery -> {
             reactiveFluentQuery.project("id")
        });
When will support it?

**Comment by mp911de** [comment]
Since version 1.4, see #663
