### ISSUE TITLE
`IS NOT` `StringMatcher` using Query by Example

### ISSUE THREAD

**Issue by pigping88** [spring-projects/spring-data-r2dbc#815]
How to findby neq by using r2dbcRepository ?

`r2dbcRepository.findBy(Example.of(T,  ExampleMatcher), queryFuction -> {})`

**Comment by mp911de** [comment]
`StringMatcher` does not provide a constant for not equals, it supports only exact/ starting/ending/containing modes.

**Comment by pigping88** [comment]
And , i need the conditional querying with R2dbcRepository. such as:
`@Query("select * from table t where if conditionA ?  t.x = xx : t.y = xx")`

**Comment by mp911de** [comment]
Query by Example is not intended for `IS NOT EQUAL TO` queries (`!=`), but rather to match an example.
