### ISSUE TITLE
Use multiple connection factories

### ISSUE THREAD

**Issue by GeorgiPetkov** [spring-projects/spring-data-r2dbc#829]
How can I use multiple connection factories in a Spring Boot app? Looking at the autoconfigurations everything is package private, with hardcoded properties paths and not allowing multiple connection factory beans.
More precisely, I need a reusable form of `org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations` allowing for multiple `ConnectionFactory` beans. This is already available for data sources as described here - https://www.baeldung.com/spring-boot-configure-multiple-datasources.

**Comment by mp911de** [comment]
This is a question for Spring Boot. Please file your ticket at https://github.com/spring-projects/spring-boot/issues

**Comment by GeorgiPetkov** [comment]
Sure, I've created one there - https://github.com/spring-projects/spring-boot/issues/35650.
