### ISSUE TITLE
`bindProperties` throws error when entities contain enum fields

### ISSUE THREAD

**Issue by detomarco** [spring-projects/spring-data-r2dbc#854]
It seems like entities cannot have enum fields when saving using `bindProperties` or `bind` APIs

Spring boot 3.2.2

```java

@Table("cars")
public class Car {
    @Id
    private UUID id;
    private String name;
    private Language language;
   
   // getters - setters
}

public enum Language {
    EN, NL
}

@Repository
public class CarRepository {

    private final DatabaseClient databaseClient;

    public CarRepository(DatabaseClient databaseClient) {
        this.databaseClient = databaseClient;
    }

    public Car save(Car car) {

        databaseClient.sql("INSERT INTO cars(id,name, language) VALUES(:id,:name, :language)")
                .bindProperties(car)
                .fetch()
                .one()
                .block();

        return car;

    }
}

@Test
void contextLoads() {
    Car car = new Car();
    car.setId(UUID.randomUUID());
    car.setName("BMW");
    car.setLanguage(Language.EN);

    carRepository.save(car);

}

```

This test throws this exception

```
java.lang.IllegalArgumentException: Cannot encode parameter of type io.r2dbc.spi.Parameters$InParameter (EN)
	at io.r2dbc.postgresql.codec.DefaultCodecs.encodeParameterValue(DefaultCodecs.java:290)
	at io.r2dbc.postgresql.codec.DefaultCodecs.encode(DefaultCodecs.java:264)
	at io.r2dbc.postgresql.PostgresqlStatement.bind(PostgresqlStatement.java:108)
	at io.r2dbc.postgresql.PostgresqlStatement.bind(PostgresqlStatement.java:59)
```

Would it be possible to support enumeration in `bindProperties` api?

Full code [here](https://github.com/detomarco/spring-data-r2dbc-uuid/tree/persist-issue)

**Comment by mp911de** [comment]
Thanks for reaching out. `DatabaseClient` is part of Spring Framework. It isn't opinionated about enum representations (ordinal vs. name) therefore the value is passed on directly as-is.

I suggest reaching out to [Spring Framework](https://github.com/spring-projects/spring-framework/issues) and filing a ticket for discussion.

Furthermore, you can use [Postgres Enum Types](https://github.com/pgjdbc/r2dbc-postgresql?tab=readme-ov-file#postgres-enum-types) to serialize Java enums to Postgres enums if you wish. However, that requires a bit of driver configuration.
