### ISSUE TITLE
Using multiple Spring Data modules no longer creates repository implementation 

### ISSUE THREAD

**Issue by roboticscm** [spring-projects/spring-data-r2dbc#88]
When I intergrate Spring-data-r2dbc and Reactive Redis, start Jetty containter, it throws Exception like this

_

> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2019-04-03 19:52:55.444 ERROR 2332 --- [  restartedMain] o.s.b.d.LoggingFailureAnalysisReporter   : 
> 
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Parameter 0 of constructor in vn.com.sky.DataLoader required a bean of type 'vn.com.sky.RoleRepo' that could not be found.
> 
> 
> Action:
> 
> Consider defining a bean of type 'vn.com.sky.RoleRepo' in your configuration.

_

[https://stackoverflow.com/questions/55495708/is-spring-data-r2dbc-conflicts-with-reactive-redis](https://stackoverflow.com/questions/55495708/is-spring-data-r2dbc-conflicts-with-reactive-redis)

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by roboticscm** [comment]
I'm sorry about that

Here is the source code demo

[https://github.com/roboticscm/r2dbc-reactive-redis.git](https://github.com/roboticscm/r2dbc-reactive-redis.git)

**Comment by mp911de** [comment]
Thanks for a lot the code. 

When you add multiple Spring Data modules to one project that support repositories, then Spring Data enters [strict configuration mode](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.multiple-modules). Without further indication, modules aren't able to figure out which repository to implement.

In your case, adding `@Table` to `Role` sorts out the issue as Spring Data R2DBC identifies `Role` as a type that it should implement repositories for. Note that Spring Data Redis also supports repositories.

**Comment by roboticscm** [comment]
Thanks for your helping
