### ISSUE TITLE
Could not map database 'Char' datatype to Java String data type

### ISSUE THREAD

**Issue by cleveyeo** [spring-projects/spring-data-r2dbc#92]
Hi,

I created my database with the following sql statement in Postgres.
`CREATE TABLE CUSTOMERS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);`

I have created a POJO class with 
`private String address` and so on.

My repo code:
`public interface CustomerRepository extends ReactiveCrudRepository<Customer, Long> {
@Query("select * from CUSTOMERS")
Mono<Customer> findByLastnameLike();
}`

However, when i run my program, i get the following error,
`org.springframework.data.mapping.MappingException: Could not read property private java.lang.String com.sc.wm.omf.order.service.Customer.address from result set!`

**Comment by mp911de** [comment]
Can you please post the full stack trace?

**Comment by mp911de** [comment]
Any update on this ticket?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
