### ISSUE TITLE
Add support for Optimistic Locking using @Version

### ISSUE THREAD

**Issue by roboticscm** [spring-projects/spring-data-r2dbc#93]
I have an entity bellow: 
```
@Data 
@NoArgsConstructor
@Table
public class Role {
	@Id
	private Long id;
	private String name;
	@Version
	private Long version = 0L;
	public Role(String name) {
		this.name = name;
	}
}
```

And controller like this:
```
@RequestMapping("/api/role/save")
public Mono<Role> save(@RequestBody Role role){
	return roleRepo.save(role);
}
```

When I save a Role without @Version everything is fine
But when I add @Version, it throws exception like this:

```
java.lang.IllegalArgumentException: Could not obtain required identifier from entity Role(id=null, name=ADMIN, version=0)!
	at org.springframework.data.repository.core.EntityInformation.getRequiredId(EntityInformation.java:65) ~[spring-data-commons-2.2.0.M2.jar:2.2.0.M2]
	at org.springframework.data.r2dbc.repository.support.SimpleR2dbcRepository.save(SimpleR2dbcRepository.java:72) ~[spring-data-r2dbc-1.0.0.M1.jar:1.0.0.M1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_201]
```

Source code demo:
[https://github.com/roboticscm/r2dbc-reactive-redis.git](https://github.com/roboticscm/r2dbc-reactive-redis.git)

**Comment by mp911de** [comment]
Please checkout how to [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to keep the issue readable. Thank you.

**Comment by mp911de** [comment]
Possibly related to #87.

**Comment by roboticscm** [comment]
Maybe the #87 and #93 are the same. Exceptions occured after I add @Version, the @Id works fine.

**Comment by mp911de** [comment]
Still, we need to sort out two things: The one is a bug that happens when you add `@Version`. The other issue is optimistic locking support which is not in place yet.

**Comment by schauder** [comment]
This relates to https://jira.spring.io/browse/DATAJDBC-219

There is even someone working on it already https://github.com/spring-projects/spring-data-jdbc/pull/124

**Comment by vuck3o** [comment]
https://github.com/spring-projects/spring-data-jdbc supports optimistic locking since version 2. Is there any information when optimistic locking will also be available for spring data r2dbc?

**Comment by RobMaskell** [comment]
Same problem, but looks like a different exception, looking forward to this being added

**Comment by schauder** [comment]
Done.
