### ISSUE TITLE
Add support for AbstractRoutingConnectionFactory

### ISSUE THREAD

**Issue by zahidraza** [spring-projects/spring-data-r2dbc#98]
In non-reactive spring application, ORM tool like Hibernate provides a way to resolve tenant and thereby make the call to appropriate database or schema. Multi-Tenancy is achieved by implementing `MultiTenantConnectionProvider` and `CurrentTenantIdentifierResolver` interfaces.

Is there a way to implement multi-tenancy using r2dbc. Is it supported as of now? 
If no, what is the roadmap going forward for this feature?

**Comment by mp911de** [comment]
`CurrentTenantIdentifierResolver` is a resource-factory-level callback that returns a tenant-id from a parameter-less method. Typically, implementations use `ThreadLocal` storage to configure routing.

In Reactive Streams, we no longer can use `ThreadLocal` to pass items between involved components. Project Reactor introduced a custom abstract, the Subscriber `Context` that can be used to attach contextual values to a subscription.

Based on `Context`, we could provide an `AbstractRoutingConnectionFactory` that does the exact same as `AbstractRoutingDataSource` by fetching a lookup value from `Context` to give you the appropriate tenant-specific connection.

Do you want to have a look at `AbstractRoutingDataSource` and come up with a pull request?

Connection routing isn't currently on our roadmap. If we receive a pull request, then we can include that feature.

**Comment by simontb** [comment]
I think when used in conjuction with [r2dbc-pool](https://github.com/r2dbc/r2dbc-pool), a tenant-specific connection might not be the ideal solution depending on the implementation of tenant separation. This would make most sense when each tenant resides on his own database. When tenants are identified by schema or column, the same db connection could be used for multiple tenants.

**Comment by mp911de** [comment]
There's a vast amount of design patterns for multi-tenancy, connection/database/schema per tenant is one of them. From a consistency point of view, it makes a lot of sense to provide a routing `ConnectionFactory`.

**Comment by schauder** [comment]
This is resolved by e3aae61
